CREATE TABLE infra_object_level_crossing (
	id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	obj_id varchar(255) NOT NULL,
	data jsonb NOT NULL,
	infra_id int8 NOT NULL REFERENCES infra(id) ON DELETE CASCADE,
	UNIQUE (infra_id, obj_id)
);

CREATE TABLE infra_layer_level_crossing (
	id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	obj_id varchar(255) NOT NULL,
	geographic geometry(multipoint, 3857) NOT NULL,
	infra_id int8 NOT NULL REFERENCES infra(id) ON DELETE CASCADE,
	UNIQUE (infra_id, obj_id)
);

CREATE INDEX infra_layer_level_crossing_geographic ON infra_layer_level_crossing USING gist (geographic);
