# Helm overrides
nameOverride: ""
fullnameOverride: ""

# Common parameters. Will be applied everywhere can be
# overriden within the "services" section.
# @schema
# additionalProperties: true
# @schema
annotations: {}
# @schema
# additionalProperties: true
# @schema
labels: {}
# @schema
# additionalProperties: true
# @schema
nodeSelector: {}
tolerations: []
# @schema
# additionalProperties: true
# @schema
affinity: {}

# Endpoints used by the application.
# The variables can be either a string or directly an object that would be used
# in the env variable that uses it (merged directly).
endpoints:
  # -- (string) Public url of the application
  public: https://my-osrd-instance.org
  # -- (object) amqp configuration
  amqp:
    # @schema
    # type: [string, object]
    # @schema
    # --(string, object) amqp server url text or reference to a secret
    url: "amqp://osrd:password@rabbitmq:5672/%2f"
    # @schema
    # type: [string, object]
    # @schema
    # -- (string, object) amqp management url
    management: "http://osrd:password@rabbitmq:15672"
    # @schema
    # type: [string, object]
    # @schema
    # -- (string, object) amqp management url including vhost
    managementWithVhost: "http://osrd:password@rabbitmq:15672/%2f"
  # @schema
  # type: [string, object]
  # @schema
  # -- (string, object) postgresql url
  postgresql: "postgres://osrd:password@postgres:5432/osrd"
  # @schema
  # type: [string, object]
  # @schema
  # -- (string, object) postgresql url for openFGA
  postgresqlOpenFGA: "postgres://osrd:password@postgres:5432/osrd?search_path=openfga"
  # @schema
  # type: [string, object]
  # @schema
  # -- (string, object) redis/valkey url
  redis: redis://username:pwd@redis:6379/0

# Container images related settings
# -- (list) list of imagePullSecrets to use
imagePullSecrets: []
pullPolicy: IfNotPresent
images:
  editoast: ghcr.io/openrailassociation/osrd-REPOSITORY_VERSION_REPLACE_ME/osrd-editoast:IMAGES_VERSION_REPLACE_ME
  gateway: ghcr.io/openrailassociation/osrd-REPOSITORY_VERSION_REPLACE_ME/osrd-gateway:IMAGES_VERSION_REPLACE_ME-front
  core: ghcr.io/openrailassociation/osrd-REPOSITORY_VERSION_REPLACE_ME/osrd-core:IMAGES_VERSION_REPLACE_ME
  osrdyne: ghcr.io/openrailassociation/osrd-REPOSITORY_VERSION_REPLACE_ME/osrd-osrdyne:IMAGES_VERSION_REPLACE_ME
  openfga: openfga/openfga:v1.8.6

# -- (object) Services direct settings and overides
services:
  openfga:
    enabled: false
    replicaCount: 2
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080
    readinessProbe:
      disabled: false
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 3
    # @schema
    # additionalProperties: true
    # @schema
    annotations: {}
    # @schema
    # additionalProperties: true
    # @schema
    labels: {}
    # @schema
    # additionalProperties: true
    # @schema
    nodeSelector: {}
    tolerations: []
    # @schema
    # additionalProperties: true
    # @schema
    affinity: {}
    # @schema
    # additionalProperties: true
    # @schema
    resources: {}
    env: []

  osrdyne:
    enabled: true
    replicaCount: 1
    service:
      type: ClusterIP
      port: 80
      targetPort: 80
    livenessProbe:
      disabled: false
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 3
    readinessProbe:
      disabled: false
    # @schema
    # type: object
    # description: osrdyne configuration
    # properties:
    #   pool_id:
    #     type: string
    #   api_address:
    #     type: string
    #   default_message_ttl:
    #     type: [integer, null]
    #     required: false
    #   max_length:
    #     type: [integer, null]
    #     required: false
    #   max_length_bytes:
    #     type: [integer, null]
    #     required: false
    # @schema
    config:
      pool_id: "core"
      api_address: "0.0.0.0:80"
      default_message_ttl:
      max_length:
      max_length_bytes:
    # @schema
    # additionalProperties: true
    # @schema
    annotations: {}
    # @schema
    # additionalProperties: true
    # @schema
    labels: {}
    # @schema
    # additionalProperties: true
    # @schema
    nodeSelector: {}
    tolerations: []
    # @schema
    # additionalProperties: true
    # @schema
    affinity: {}
    # @schema
    # additionalProperties: true
    # @schema
    resources: {}
    env: []

  images:
    replicaCount: 1
    enabled: true
    service:
      type: ClusterIP
      port: 80
      targetPort: 80
    # @schema
    # additionalProperties: true
    # @schema
    annotations: {}
    # @schema
    # additionalProperties: true
    # @schema
    labels: {}
    # @schema
    # additionalProperties: true
    # @schema
    nodeSelector: {}
    tolerations: []
    # @schema
    # additionalProperties: true
    # @schema
    affinity: {}
    # @schema
    # additionalProperties: true
    # @schema
    resources: {}
    env: []

  core:
    # @schema
    # additionalProperties: true
    # @schema
    annotations: {}
    # @schema
    # additionalProperties: true
    # @schema
    labels: {}
    # @schema
    # additionalProperties: true
    # @schema
    nodeSelector: {}
    tolerations: []
    # @schema
    # additionalProperties: true
    # @schema
    affinity: {}
    # @schema
    # additionalProperties: true
    # @schema
    resources: {}
    # @schema
    # required: false
    # type: [string, null]
    # @schema
    # -- (string, null) Service account name to mount in case of kubernetes deployment
    service_account_name: null
    env: []
    config:
      # @schema
      # type: [null, string]
      # @schema
      telemetry: null
    # @schema
    # properties:
    #  activation_value:
    #    type: [string, integer]
    #  cooldown_period:
    #    type: integer
    #  min_replicas:
    #    type: integer
    #  max_replicas:
    #    type: integer
    #  mode:
    #    type: string
    #  polling_interval:
    #    type: integer
    #  use_cached_metrics:
    #    type: boolean
    #  value:
    #    type: [string, integer]
    #  metric_type:
    #    type: string
    #  type:
    #    enum: [NoScaling, Keda, Hpa]
    # @schema
    # -- (object) autoscaling configuration of osrdyne KubernetesDriver detail in https://github.com/OpenRailAssociation/osrd/blob/dev/osrdyne/src/drivers/kubernetes.rs
    autoscaling:
      # -- (string) Type of autoscaling
      type: NoScaling

  gateway:
    enabled: true
    replicaCount: 1
    service:
      type: ClusterIP
      port: 80
      targetPort: 80
    # -- (object) Gateway ingress configuration
    ingress:
      enabled: false
      className: ""
      # -- (list) List of domains to serve
      domains:
        - osrd.local
      # -- (string) Secret containing the tls certificates can be null
      secretName: osrd-gateway-tls
    # @schema
    # additionalProperties: true
    # @schema
      annotations: {}
      tls: []
    # -- (object) gateway authentication configuration see https://github.com/OpenRailAssociation/osrd/blob/dev/gateway/README.md
    config:
      # @schema
      # properties:
      #   providers:
      #     type: array
      #   default_provider:
      #     type: [string, null]
      #     description: default provider
      #   session_namespace:
      #     type: [string, null]
      #     description: namespace for sesson
      # @schema
      auth:
        # @schema
        # items:
        #   type: object
        #   properties:
        #     type:
        #       type: string
        #       enum: [Mocked, Oidc]
        #     username:
        #       type: string
        #       required: false
        #   additionalProperties: true
        # @schema
        # -- (array) List of authentication providers
        providers:
          - type: "Mocked"
            provider_id: "mocked"
            username: "osrd-admin"
      railway_manager_interface:
        enabled: false
        prefix: "/railway-manager"
        upstream: ""
      # secret_key: "NOT+A+SECRET++NOT+A+SECRET++NOT+A+SECRET++NOT+A+SECRET++NOT+A+SECRET++NOT+A+SECRET++NOT+A+SECRET"
      # See https://github.com/OpenRailAssociation/osrd/blob/dev/gateway/README.md#config
      tracing:
        enabled: false
        type: ""
        # @schema
        # additionalProperties: true
        # @schema
        config: {}
      trusted_proxies:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
    livenessProbe:
      disabled: false
    readinessProbe:
      disabled: false
    # @schema
    # additionalProperties: true
    # @schema
    annotations: {}
    # @schema
    # additionalProperties: true
    # @schema
    labels: {}
    # @schema
    # additionalProperties: true
    # @schema
    nodeSelector: {}
    tolerations: []
    # @schema
    # additionalProperties: true
    # @schema
    affinity: {}
    # @schema
    # additionalProperties: true
    # @schema
    resources: {}
    env: []
    volumes: []
    volumeMounts: []

  editoast:
    enabled: true
    replicaCount: 2
    service:
      type: ClusterIP
      port: 80
      targetPort: 80
    livenessProbe:
      disabled: false
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 3
    readinessProbe:
      disabled: false
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 3
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
      # @schema
      # additionalProperties: true
      # @schema
      annotations: {}
      # @schema
      # additionalProperties: true
      # @schema
      labels: {}
    # @schema
    # additionalProperties: true
    # @schema
    annotations: {}
    # -- (object) Init job configuration
    init:
      # -- (bool) Wheter to run editoast init pod for diesel migration
      enabled: true
      # -- (string) Command to run after diesel migration
      extend: ""
      # @schema
      # type: [object]
      # required: false
      # additionalProperties: true
      # @schema
      # -- (object) Labels for init pod
      labels: {}
    # -- (object) cronjob configuration. Runs editoast gc
    cronjob:
      # @schema
      # type: [string, null]
      # @schema
      # -- (string, null) cronjob format time of execution. Set to null to disable
      schedule: "3 1 * * mon-fri"
      # @schema
      # type: [string, null]
      # @schema
      # -- (string, null) shell commands to be executed before editoast gc
      extend: ""
      # -- (list) list of env variable to pass to cronjob script. Editoast default service variables are already set
      env: []
    # @schema
    # type: [string, null]
    # @schema
    # -- (string, null) size in Kubernetes format for editoast shared storage mount in all hosts. null to disable permanent storage
    permanent_storage_size: null
    # @schema
    # type: [string, null]
    # @schema
    # -- (string, null) storage class for permanent storage
    permanent_storage_class: null
    # @schema
    # additionalProperties: true
    # @schema
    labels: {}
    # @schema
    # additionalProperties: true
    # @schema
    nodeSelector: {}
    tolerations: []
    # @schema
    # additionalProperties: true
    # @schema
    affinity: {}
    # @schema
    # additionalProperties: true
    # @schema
    resources: {}
    env: []

  statefulEditoast:
    enabled: true
    replicaCount: 1
    service:
      type: ClusterIP
      port: 80
      targetPort: 80
    livenessProbe:
      disabled: false
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 3
    readinessProbe:
      disabled: false
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 3
    # @schema
    # additionalProperties: true
    # @schema
    annotations: {}
    # @schema
    # additionalProperties: true
    # @schema
    labels: {}
    # @schema
    # additionalProperties: true
    # @schema
    nodeSelector: {}
    tolerations: []
    # @schema
    # additionalProperties: true
    # @schema
    affinity: {}
    # @schema
    # additionalProperties: true
    # @schema
    resources: {}
    env: []
