-- DO NOT EDIT THIS FILE MANUALLY!
-- To change the migration's content, use `editoast search make-migration`.
-- To add custom SQL code, check out `#[derive(Search)]` attributes `prepend_sql` and `append_sql`.

DROP TABLE IF EXISTS "search_operational_point";

CREATE TABLE "search_operational_point" (
    id BIGINT PRIMARY KEY REFERENCES "infra_object_operational_point"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "obj_id" varchar(255),
    "infra_id" integer,
    "uic" integer,
    "main_code" varchar(255),
    "secondary_code" text,
    "name" text,
    "is_passenger_station" boolean,
    "secondary_name" text,
    "country_code" text
);

CREATE INDEX "search_operational_point_obj_id" ON "search_operational_point" ("obj_id");
CREATE INDEX "search_operational_point_infra_id" ON "search_operational_point" ("infra_id");
CREATE INDEX "search_operational_point_uic" ON "search_operational_point" ("uic");
CREATE INDEX "search_operational_point_main_code" ON "search_operational_point" ("main_code");
CREATE INDEX "search_operational_point_secondary_code" ON "search_operational_point" ("secondary_code");
CREATE INDEX "search_operational_point_name" ON "search_operational_point" USING gin ("name" gin_trgm_ops);
CREATE INDEX "search_operational_point_is_passenger_station" ON "search_operational_point" ("is_passenger_station");
CREATE INDEX "search_operational_point_secondary_name" ON "search_operational_point" ("secondary_name");
CREATE INDEX "search_operational_point_country_code" ON "search_operational_point" ("country_code");

CREATE OR REPLACE FUNCTION search_operational_point__ins_trig_fun()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO "search_operational_point" (id, obj_id, infra_id, uic, main_code, secondary_code, name, is_passenger_station, secondary_name, country_code)
        SELECT "infra_object_operational_point".id AS id, (infra_object_operational_point.obj_id) AS obj_id,
    (infra_object_operational_point.infra_id) AS infra_id,
    ((infra_object_operational_point.data->>'uic')::integer) AS uic,
    (infra_object_operational_point.data->>'main_code') AS main_code,
    (infra_object_operational_point.data->>'secondary_code') AS secondary_code,
    osrd_prepare_for_search(infra_object_operational_point.data->>'name') AS name,
    ((infra_object_operational_point.data->>'is_passenger_station')::boolean) AS is_passenger_station,
    (infra_object_operational_point.data->>'secondary_name') AS secondary_name,
    (infra_object_operational_point.data->>'country_code') AS country_code
        FROM (SELECT NEW.*) AS "infra_object_operational_point"
        ;
    RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER search_operational_point__ins_trig
AFTER INSERT ON "infra_object_operational_point"
FOR EACH ROW EXECUTE FUNCTION search_operational_point__ins_trig_fun();


CREATE OR REPLACE FUNCTION search_operational_point__upd_trig_fun()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE "search_operational_point"
        SET "obj_id" = (infra_object_operational_point.obj_id),
        "infra_id" = (infra_object_operational_point.infra_id),
        "uic" = ((infra_object_operational_point.data->>'uic')::integer),
        "main_code" = (infra_object_operational_point.data->>'main_code'),
        "secondary_code" = (infra_object_operational_point.data->>'secondary_code'),
        "name" = osrd_prepare_for_search(infra_object_operational_point.data->>'name'),
        "is_passenger_station" = ((infra_object_operational_point.data->>'is_passenger_station')::boolean),
        "secondary_name" = (infra_object_operational_point.data->>'secondary_name'),
        "country_code" = (infra_object_operational_point.data->>'country_code')
        FROM (SELECT NEW.*) AS "infra_object_operational_point"
        
        WHERE "infra_object_operational_point".id = "search_operational_point".id;
    RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER search_operational_point__upd_trig
AFTER UPDATE ON "infra_object_operational_point"
FOR EACH ROW EXECUTE FUNCTION search_operational_point__upd_trig_fun();



INSERT INTO "search_operational_point" (id, "obj_id", "infra_id", "uic", "main_code", "secondary_code", "name", "is_passenger_station", "secondary_name", "country_code")
SELECT
    "infra_object_operational_point"."id" AS id,
    (infra_object_operational_point.obj_id) AS obj_id
,    (infra_object_operational_point.infra_id) AS infra_id
,    ((infra_object_operational_point.data->>'uic')::integer) AS uic
,    (infra_object_operational_point.data->>'main_code') AS main_code
,    (infra_object_operational_point.data->>'secondary_code') AS secondary_code
,    osrd_prepare_for_search(infra_object_operational_point.data->>'name') AS name
,    ((infra_object_operational_point.data->>'is_passenger_station')::boolean) AS is_passenger_station
,    (infra_object_operational_point.data->>'secondary_name') AS secondary_name
,    (infra_object_operational_point.data->>'country_code') AS country_code
FROM "infra_object_operational_point"
    ;
