import type { TimesStopsTableRow } from '../../../../utils/times-stops-table-types';

export const speedLimitTagOnData: TimesStopsTableRow[] = [
  {
    index: 1,
    status: 'success-schedule',
    stationName: 'West_station',
    stationCh: 'BV',
    trackName: 'V2',
    requestedArrival: '11:22:40',
    calculatedArrival: '11:22:40',
    stopTime: '',
    requestedDeparture: '',
    calculatedDeparture: '•',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: {
      requestedTheoretical: '0%',
      computedTheoretical: '00m00s',
      real: '00m00s',
      difference: '00m00s',
    },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
  },
  {
    index: 2,
    status: '',
    stationName: 'Mid_West_station',
    stationCh: 'BV',
    trackName: 'V1',
    requestedArrival: '',
    calculatedArrival: '11:29:42',
    stopTime: '',
    requestedDeparture: '',
    calculatedDeparture: '•',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: { requestedTheoretical: '', computedTheoretical: '', real: '', difference: '' },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
  },
  {
    index: 3,
    status: '',
    stationName: 'Mid_East_station',
    stationCh: 'BV',
    trackName: 'V1',
    requestedArrival: '',
    calculatedArrival: '11:35:44',
    stopTime: '00h02m04s',
    requestedDeparture: '',
    calculatedDeparture: '11:37:48',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: { requestedTheoretical: '', computedTheoretical: '', real: '', difference: '' },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
  },
  {
    index: 4,
    status: '',
    stationName: 'South_East_station',
    stationCh: 'BV',
    trackName: 'V1',
    requestedArrival: '',
    calculatedArrival: '11:49:00',
    stopTime: '00h00m00s',
    requestedDeparture: '',
    calculatedDeparture: '11:49:00',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: { requestedTheoretical: '', computedTheoretical: '', real: '', difference: '' },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
  },
];
