plugins {
    alias(libs.plugins.kotlin.jvm)
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.jna
    testImplementation libs.kotlin.test
}

tasks.register('rustBuild', Exec) {
    description = 'Builds the rust binary'

    workingDir '..'
    commandLine 'cargo', 'build', '--release'
    outputs.file '../target/release/libtrain_sim.so'

    // Always run the task and rely on cargo to build when necessary
    outputs.upToDateWhen { false }
}

tasks.register('generateKotlinBindings', Exec) {
    description = 'Re-generate the kotlin bindings'

    workingDir '..'
    commandLine 'cargo', 'run', '--package', 'uniffi-bindgen', '--',
                'generate',
                '--library', 'target/release/libtrain_sim.so',
                '--language', 'kotlin',
                '--out-dir', 'kotlin_bindings/src/main/kotlin'

    inputs.file '../target/release/libtrain_sim.so'

    // Register the train-sim crate sources as inputs of this task so that it
    // runs when the API changes
    inputs.dir '../src'

    outputs.dir 'src/main/kotlin'
}
