ARG PLAYWRIGHT_VERSION=latest
FROM mcr.microsoft.com/playwright:$PLAYWRIGHT_VERSION

COPY front/package.json front/package-lock.json /app/front/
WORKDIR /app/front
RUN --mount=type=cache,target=/root/.npm \
    npm install --frozen-lockfile

COPY front /app/front/
COPY tests /app/tests
RUN chmod a+w /app/front/
