# Generated by Django 3.1.7 on 2021-04-13 08:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(choices=[(0, 'Track Section')])),
            ],
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.entityid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Infra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.entityid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperationalPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.entityid')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.identifier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.entityid')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.identifier')),
                ('infra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.infra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackSectionRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_offset', models.FloatField()),
                ('end_offset', models.FloatField()),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.entityid')),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.tracksection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackSectionLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.FloatField()),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.entityid')),
                ('track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.tracksection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackSectionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_endpoint', models.IntegerField(choices=[(0, 'Begin'), (1, 'End')])),
                ('end_endpoint', models.IntegerField(choices=[(0, 'Begin'), (1, 'End')])),
                ('begin_track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_begin_branches', to='osrd_infra.tracksection')),
                ('end_track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_end_branches', to='osrd_infra.tracksection')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.entityid')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.identifier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_endpoint', models.IntegerField(choices=[(0, 'Begin'), (1, 'End')])),
                ('left_endpoint', models.IntegerField(choices=[(0, 'Begin'), (1, 'End')])),
                ('right_endpoint', models.IntegerField(choices=[(0, 'Begin'), (1, 'End')])),
                ('base_track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_base_branches', to='osrd_infra.tracksection')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.entityid')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.identifier')),
                ('left_track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_left_branches', to='osrd_infra.tracksection')),
                ('right_track_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_right_branches', to='osrd_infra.tracksection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.entityid')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.identifier')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.tracksectionlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.entityid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperationalPointPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.entityid')),
                ('operational_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.operationalpoint')),
                ('track_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.tracksectionrange')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
