# Generated by Django 3.1.7 on 2021-04-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identifiercomponent',
            options={'default_related_name': 'identifier_set'},
        ),
        migrations.AlterModelOptions(
            name='tracksectioncomponent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tracksectionlinkcomponent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tracksectionlocationcomponent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tracksectionrangecomponent',
            options={},
        ),
        migrations.AlterField(
            model_name='identifiercomponent',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifier_set', to='osrd_infra.identifierdatabase'),
        ),
        migrations.AlterField(
            model_name='identifiercomponent',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifier_set', to='osrd_infra.entity'),
        ),
        migrations.AlterField(
            model_name='tracksectioncomponent',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='track_section', to='osrd_infra.entity'),
        ),
        migrations.AlterField(
            model_name='tracksectionlinkcomponent',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_section_link_set', to='osrd_infra.entity'),
        ),
        migrations.AlterField(
            model_name='tracksectionlocationcomponent',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_location_set', to='osrd_infra.entity'),
        ),
        migrations.AlterField(
            model_name='tracksectionrangecomponent',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_location_set', to='osrd_infra.entity'),
        ),
    ]
