# Generated by Django 3.1.7 on 2021-04-22 14:49

from django.db import migrations, models
import django.db.models.deletion


def populate_entity_type(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Entity = apps.get_model("infra", "Entity")

    entity_ids = [
        ("TrackSectionEntity", 0),
        ("TrackSectionLinkEntity", 1),
        ("SignalEntity", 2),
        ("OperationalPointEntity", 3),
        ("SwitchEntity", 4),
    ]

    for model_name, type_id in entity_ids:
        model = apps.get_model("infra", model_name)
        content_type = ContentType.objects.get_for_model(model)
        Entity.objects.filter(type_id=type_id).update(entity_type=content_type)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('infra', '0002_auto_20210421_1505'),
    ]

    operations = [
        # add the new field, but nullable
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        # migrate the data
        migrations.RunPython(populate_entity_type),
        # make the field non nullable
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        # remove the old field
        migrations.RemoveField(
            model_name='entity',
            name='type_id',
        ),
    ]
