# Generated by Django 3.1.7 on 2021-04-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_auto_20210426_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracksectioncomponent',
            name='infra',
        ),
    ]
