# Generated by Django 3.2.5 on 2021-09-15 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0003_alter_speedsectionpartcomponent_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackSectionSignalingTypeComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('signaling_type', models.IntegerField(choices=[(0, 'Bal'), (1, 'Bal Vb'), (2, 'Bapr Dv'), (3, 'Bapr Vb'), (4, 'Bm Vu'), (5, 'Bm Vu Se'), (6, 'Bm Cv'), (7, 'Bm U'), (8, 'Bm Amu'), (9, 'Bm Nb'), (10, 'Bm Lu'), (11, 'Bm Lus'), (12, 'Bm Seus'), (13, 'Capi'), (14, 'Ct Dv'), (15, 'Ct Vu'), (16, 'Tvm300'), (18, 'Tvm430'), (19, 'Etcs 1'), (20, 'Etcs 2'), (21, 'Etcs 3'), (22, 'Trmw'), (23, 'Autre')])),
                ('start_offset', models.FloatField()),
                ('end_offset', models.FloatField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signaling_type_set', to='osrd_infra.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
