# Generated by Django 3.1.7 on 2021-04-30 13:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion



def migrate_track_section_path(apps, schema_editor):
    TrackSectionComponent = apps.get_model("osrd_infra", "TrackSectionComponent")
    GeoLineLocationComponent = apps.get_model("osrd_infra", "GeoLineLocationComponent")

    for track_section_comp in TrackSectionComponent.objects.all():
        GeoLineLocationComponent.objects.create(
            entity=track_section_comp.entity,
            geographic=track_section_comp.path,
            schematic=track_section_comp.path,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0002_auto_20210428_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalPointPartEntity',
            fields=[
            ],
            options={
                'verbose_name_plural': 'operational point entities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osrd_infra.entity',),
        ),
        migrations.CreateModel(
            name='OperationalPointPartComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_point_part_set', to='osrd_infra.entity')),
                ('operational_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.operationalpointentity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeoPointLocationComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('geographic', django.contrib.gis.db.models.fields.PointField(srid=3857)),
                ('schematic', django.contrib.gis.db.models.fields.PointField(srid=3857)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_point_location', to='osrd_infra.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeoLineLocationComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('geographic', django.contrib.gis.db.models.fields.LineStringField(srid=3857)),
                ('schematic', django.contrib.gis.db.models.fields.LineStringField(srid=3857)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_line_location', to='osrd_infra.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeoAreaLocationComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('geographic', django.contrib.gis.db.models.fields.PolygonField(srid=3857)),
                ('schematic', django.contrib.gis.db.models.fields.PolygonField(srid=3857)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_area_location', to='osrd_infra.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_track_section_path),
        migrations.RemoveField(
            model_name='tracksectioncomponent',
            name='path',
        ),
    ]
