# Generated by Django 3.1.7 on 2021-04-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0003_remove_tracksectioncomponent_infra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationalpointentity',
            options={'verbose_name_plural': 'operational point entities'},
        ),
        migrations.AlterModelOptions(
            name='signalentity',
            options={'verbose_name_plural': 'signal entities'},
        ),
        migrations.AlterModelOptions(
            name='switchentity',
            options={'verbose_name_plural': 'switch entities'},
        ),
        migrations.AlterModelOptions(
            name='tracksectionentity',
            options={'verbose_name_plural': 'track section entities'},
        ),
        migrations.AlterModelOptions(
            name='tracksectionlinkentity',
            options={'verbose_name_plural': 'track section link entities'},
        ),
    ]
