# Generated by Django 4.0.4 on 2022-04-27 15:15

from django.db import migrations, models

import osrd_infra.utils


def apply_migration(apps, schema_editor):
    """Update infra to v2.2.3"""
    Infra = apps.get_model("osrd_infra", "Infra")
    updated_infra = []

    for infra in Infra.objects.all():
        if infra.railjson_version != "2.2.3":
            infra.railjson_version = "2.2.3"
            infra.version = str(int(infra.version) + 1)
            updated_infra.append(infra)
    Infra.objects.bulk_update(updated_infra, ["railjson_version", "version"])


def revert_migration(apps, schema_editor):
    """Revert infra to v2.2.2"""
    Infra = apps.get_model("osrd_infra", "Infra")
    updated_infra = []

    for infra in Infra.objects.all():
        if infra.railjson_version == "2.2.3":
            infra.railjson_version = "2.2.2"
            infra.version = str(int(infra.version) + 1)
            updated_infra.append(infra)
    Infra.objects.bulk_update(updated_infra, ["railjson_version", "version"])


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0004_add_loading_gauges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="switchmodel",
            name="data",
            field=models.JSONField(
                validators=[
                    osrd_infra.utils.JSONSchemaValidator(
                        limit_value={
                            "definitions": {
                                "Endpoint": {
                                    "description": "An enumeration.",
                                    "enum": ["BEGIN", "END"],
                                    "title": "Endpoint",
                                    "type": "string",
                                },
                                "ObjectReference": {
                                    "properties": {
                                        "id": {"maxLength": 255, "title": "Id", "type": "string"},
                                        "type": {"title": "Type", "type": "string"},
                                    },
                                    "required": ["id", "type"],
                                    "title": "ObjectReference",
                                    "type": "object",
                                },
                                "TrackEndpoint": {
                                    "properties": {
                                        "endpoint": {"$ref": "#/definitions/Endpoint"},
                                        "track": {"$ref": "#/definitions/ObjectReference"},
                                    },
                                    "required": ["endpoint", "track"],
                                    "title": "TrackEndpoint",
                                    "type": "object",
                                },
                            },
                            "properties": {
                                "group_change_delay": {"title": "Group Change Delay", "type": "number"},
                                "id": {"maxLength": 255, "title": "Id", "type": "string"},
                                "label": {"title": "Label", "type": "string"},
                                "ports": {
                                    "additionalProperties": {"$ref": "#/definitions/TrackEndpoint"},
                                    "title": "Ports",
                                    "type": "object",
                                },
                                "switch_type": {"$ref": "#/definitions/ObjectReference"},
                            },
                            "required": ["id", "switch_type", "group_change_delay", "ports", "label"],
                            "title": "Switch",
                            "type": "object",
                        }
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="infra",
            name="railjson_version",
            field=models.CharField(default="2.2.3", editable=False, max_length=16),
        ),
        migrations.RunSQL(
            sql="""UPDATE osrd_infra_switchmodel as switch  SET data = JSONB_SET(data, '{label}', '""')""",
            reverse_sql="""UPDATE osrd_infra_switchmodel as switch  SET data = switch.data - 'label'""",
        ),
        migrations.RunPython(code=apply_migration, reverse_code=revert_migration),
    ]
