# Generated by Django 3.2 on 2021-04-30 15:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0004_add_geo_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationalpointpartentity',
            options={'verbose_name_plural': 'operational point part entities'},
        ),
        migrations.CreateModel(
            name='TrackAngleComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('geographic', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(379)])),
                ('schematic', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(379)])),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='track_angle', to='osrd_infra.entity')),
            ],
            options={
                'default_related_name': 'track_angle_set',
            },
        ),
        migrations.AddConstraint(
            model_name='trackanglecomponent',
            constraint=models.CheckConstraint(check=models.Q(geographic__lte=379), name='geographic__lte=379'),
        ),
        migrations.AddConstraint(
            model_name='trackanglecomponent',
            constraint=models.CheckConstraint(check=models.Q(schematic__lte=379), name='schematic__lte=379'),
        ),
    ]
