# Generated by Django 3.2.5 on 2021-09-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0006_alter_line_and_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalpointpartcomponent',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operational_point_part', to='osrd_infra.entity'),
        ),
        migrations.CreateModel(
            name='OperationalPointComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ci', models.IntegerField()),
                ('ch', models.CharField(max_length=2)),
                ('ch_short_label', models.CharField(max_length=255, null=True)),
                ('ch_long_label', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operational_point', to='osrd_infra.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
