# Generated by Django 3.2 on 2021-04-30 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0006_add_track_and_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='KilometricPointComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kilometric_point_set', to='osrd_infra.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
