# Generated by Django 3.1.7 on 2021-04-30 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0007_add_kilometric_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicableDirectionComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('applicable_direction', models.IntegerField(choices=[(0, 'Normal'), (1, 'Reverse')])),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicable_direction_set', to='osrd_infra.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
