# Generated by Django 3.2 on 2021-05-05 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0008_signal_applicable_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptFunctionEntity',
            fields=[
            ],
            options={
                'verbose_name_plural': 'script functions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osrd_infra.entity',),
        ),
        migrations.CreateModel(
            name='SightDistanceComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('distance', models.FloatField()),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sight_distance', to='osrd_infra.entity')),
            ],
            options={
                'default_related_name': 'sight_distance_set',
            },
        ),
        migrations.CreateModel(
            name='RailScriptComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('script', models.JSONField()),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rail_script', to='osrd_infra.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='sightdistancecomponent',
            constraint=models.CheckConstraint(check=models.Q(distance__gte=0), name='distance__gte=0'),
        ),
    ]
