# Generated by Django 3.2 on 2021-05-05 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0009_railscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedSectionEntity',
            fields=[
            ],
            options={
                'verbose_name_plural': 'speed section entities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osrd_infra.entity',),
        ),
        migrations.CreateModel(
            name='SpeedSectionPartEntity',
            fields=[
            ],
            options={
                'verbose_name_plural': 'speed section part entities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osrd_infra.entity',),
        ),
        migrations.CreateModel(
            name='SpeedSectionPartComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_section_part_set', to='osrd_infra.entity')),
                ('speed_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.speedsectionentity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeedSectionComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('speed', models.FloatField()),
                ('is_signalized', models.BooleanField()),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speed_section', to='osrd_infra.entity')),
            ],
            options={
                'default_related_name': 'speed_section_set',
            },
        ),
        migrations.AddConstraint(
            model_name='speedsectioncomponent',
            constraint=models.CheckConstraint(check=models.Q(speed__gte=0), name='speed__gte=0'),
        ),
    ]
