# Generated by Django 3.2 on 2021-05-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0010_fix_infra'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='osrd_infra.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sight_distance', models.FloatField()),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='osrd_infra.entity')),
            ],
            options={
                'default_related_name': 'signal_set',
            },
        ),
        migrations.CreateModel(
            name='WaypointComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('waypoint_type', models.IntegerField(choices=[(0, 'Buffer Stop'), (1, 'Detector')])),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waypoint', to='osrd_infra.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sightdistancecomponent',
            name='entity',
        ),
        migrations.DeleteModel(
            name='BufferStopEntity',
        ),
        migrations.DeleteModel(
            name='DetectorEntity',
        ),
        migrations.CreateModel(
            name='WaypointEntity',
            fields=[
            ],
            options={
                'verbose_name_plural': 'waypoint entities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osrd_infra.entity',),
        ),
        migrations.DeleteModel(
            name='SightDistanceComponent',
        ),
        migrations.AddField(
            model_name='signalcomponent',
            name='linked_detector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_detector', to='osrd_infra.waypointentity'),
        ),
        migrations.AddField(
            model_name='routecomponent',
            name='entry_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.waypointentity'),
        ),
        migrations.AddConstraint(
            model_name='signalcomponent',
            constraint=models.CheckConstraint(check=models.Q(sight_distance__gte=0), name='sight_distance__gte=0'),
        ),
    ]
