# Generated by Django 3.2 on 2021-05-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0010_speed_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BufferStopEntity',
            fields=[
            ],
            options={
                'verbose_name_plural': 'buffer stop entities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osrd_infra.entity',),
        ),
        migrations.CreateModel(
            name='DetectorEntity',
            fields=[
            ],
            options={
                'verbose_name_plural': 'detector entities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osrd_infra.entity',),
        ),
        migrations.AlterField(
            model_name='applicabledirectioncomponent',
            name='applicable_direction',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Reverse'), (2, 'Both')]),
        ),
    ]
