# Generated by Django 3.2 on 2021-05-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0011_waypoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracksectionlinkcomponent',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='track_section_link', to='osrd_infra.entity'),
        ),
        migrations.CreateModel(
            name='SwitchComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='switch', to='osrd_infra.entity')),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_switch', to='osrd_infra.tracksectionlinkentity')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_switch', to='osrd_infra.tracksectionlinkentity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
