# Generated by Django 3.2 on 2021-05-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0011_waypoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVDSectionEntity',
            fields=[
            ],
            options={
                'verbose_name_plural': 'TVD section entities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osrd_infra.entity',),
        ),
        migrations.CreateModel(
            name='BerthingComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_berthing', models.BooleanField()),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='berthing', to='osrd_infra.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BelongsToTVDSectionComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belong_to_tvd_section_set', to='osrd_infra.entity')),
                ('tvd_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvd_section_components', to='osrd_infra.tvdsectionentity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
