# Generated by Django 3.1.7 on 2021-05-25 22:39

from django.db import migrations, models


def migrate_identifier_database(apps, schema_editor):
    IdentifierComponent = apps.get_model("osrd_infra", "IdentifierComponent")

    for identifier in IdentifierComponent.objects.select_related("database"):
        identifier.database_name = identifier.database.name
        identifier.save()


class Migration(migrations.Migration):
    dependencies = [
        ('osrd_infra', '0012_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifiercomponent',
            name='database_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.RunPython(migrate_identifier_database),
        migrations.RemoveField(
            model_name='identifiercomponent',
            name='database',
        ),
        migrations.RenameField(
            model_name='identifiercomponent',
            old_name='database_name',
            new_name='database',
        ),
        migrations.AlterField(
            model_name='identifiercomponent',
            name='database',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='IdentifierDatabase',
        ),
    ]
