# Generated by Django 3.2 on 2021-05-06 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0012_tvd_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicabledirectioncomponent',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicable_direction', to='osrd_infra.entity'),
        ),
    ]
