# Generated by Django 3.2.2 on 2021-05-31 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0014_rollingstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracksectionlocationcomponent',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_location', to='osrd_infra.entity'),
        ),
    ]
