# Generated by Django 3.1.7 on 2021-06-02 15:54

import django.contrib.postgres.fields
from django.db import migrations, models
import osrd_infra.models.rolling_stock


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0015_alter_track_location_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingstock',
            name='capabilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='A list of features the train exhibits, such as ERTMS support', size=None),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='comfort_acceleration',
            field=models.FloatField(help_text='The maximum operational acceleration, in m/s^2'),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='max_speed',
            field=models.FloatField(help_text='The maximum operational speed, in m/s'),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='startup_acceleration',
            field=models.FloatField(help_text='The maximum acceleration during startup, in m/s^2'),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='startup_time',
            field=models.FloatField(help_text='The time the train takes before it can start accelerating'),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='timetable_gamma',
            field=models.FloatField(help_text='The maximum braking coefficient, for timetabling purposes, in m/s^2'),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='tractive_effort_curve',
            field=models.JSONField(help_text='A curve mapping speed (in m/s) to maximum traction (in newtons)', validators=[osrd_infra.models.rolling_stock.JSONSchemaValidator(limit_value={'items': {'properties': {'max_effort': {'type': 'number'}, 'speed': {'type': 'number'}}, 'required': ['speed', 'max_effort'], 'type': 'object'}, 'title': 'schema', 'type': 'array'})]),
        ),
    ]
