# Generated by Django 3.2.2 on 2021-06-07 08:05

from django.db import migrations, models
import osrd_infra.models.rolling_stock


def migrate_curve_schema(apps, schema_editor):
    RollingStock = apps.get_model("osrd_infra", "rollingstock")

    for rolling_stock in RollingStock.objects.all():
        rolling_stock.tractive_effort_curves = {
            "default": rolling_stock.tractive_effort_curve,
        }


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0016_rolling_stock_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollingstock',
            name='tractive_effort_curves',
            field=models.JSONField(default={}, help_text='A set of curves mapping speed (in m/s) to maximum traction (in newtons)', validators=[osrd_infra.models.rolling_stock.JSONSchemaValidator(limit_value={'additionalProperties': {'items': {'properties': {'max_effort': {'type': 'number'}, 'speed': {'type': 'number'}}, 'required': ['speed', 'max_effort'], 'type': 'object'}, 'title': 'schema', 'type': 'array'}, 'type': 'object'})]),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_curve_schema),
        migrations.RemoveField(
            model_name='rollingstock',
            name='tractive_effort_curve',
        ),
    ]
