# Generated by Django 3.2.2 on 2021-06-08 21:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import osrd_infra.models.rolling_stock


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0018_multiple_effort_curves'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('infra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='osrd_infra.infra')),
            ],
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=128)),
                ('departure_time', models.FloatField()),
                ('phases', models.JSONField(validators=[osrd_infra.models.rolling_stock.JSONSchemaValidator(limit_value={'items': {'additionalProperties': False, 'properties': {'operational_point': {'type': 'number'}, 'position': {'additionalProperties': False, 'properties': {'offset': {'type': 'number'}, 'track_section': {'type': 'number'}}, 'required': ['offset', 'track_section'], 'type': 'object'}, 'stop_time': {'type': 'number'}}, 'required': ['position', 'stop_time', 'operational_point'], 'type': 'object'}, 'title': 'schema', 'type': 'array'})])),
                ('initial_speed', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='path',
            name='geographic',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=3857),
        ),
        migrations.AlterField(
            model_name='path',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.entitynamespace'),
        ),
        migrations.AlterField(
            model_name='path',
            name='payload',
            field=models.JSONField(validators=[osrd_infra.models.rolling_stock.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'operational_points': {'items': {'additionalProperties': False, 'properties': {'op': {'type': 'number'}, 'position': {'additionalProperties': False, 'properties': {'offset': {'type': 'number'}, 'track_section': {'type': 'number'}}, 'required': ['offset', 'track_section'], 'type': 'object'}}, 'required': ['op', 'position'], 'type': 'object'}, 'title': 'schema', 'type': 'array'}, 'path': {'items': {'additionalProperties': False, 'properties': {'route': {'type': 'number'}, 'track_sections': {'items': {'additionalProperties': False, 'properties': {'begin': {'type': 'number'}, 'end': {'type': 'number'}, 'track_section': {'type': 'number'}}, 'required': ['begin', 'end', 'track_section'], 'type': 'object'}, 'type': 'array'}}, 'required': ['route', 'track_sections'], 'type': 'object'}, 'title': 'schema', 'type': 'array'}}, 'required': ['path', 'operational_points'], 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='path',
            name='schematic',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=3857),
        ),
        migrations.CreateModel(
            name='TrainScheduleResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.JSONField()),
                ('train_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='osrd_infra.trainschedule', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.path'),
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='rolling_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='osrd_infra.rollingstock'),
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_schedules', to='osrd_infra.timetable'),
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('started_by', models.UUIDField()),
                ('infra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='osrd_infra.infra')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='osrd_infra.timetable')),
            ],
        ),
    ]
