# Generated by Django 3.2.2 on 2021-06-17 08:22

from django.db import migrations, models
import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0019_timetable_train_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainschedule',
            old_name='train_id',
            new_name='train_name',
        ),
        migrations.RemoveField(
            model_name='trainschedule',
            name='phases',
        ),
        migrations.AlterField(
            model_name='path',
            name='payload',
            field=models.JSONField(validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'path': {'items': {'additionalProperties': False, 'properties': {'route': {'type': 'number'}, 'track_sections': {'items': {'additionalProperties': False, 'properties': {'begin': {'type': 'number'}, 'end': {'type': 'number'}, 'track_section': {'type': 'number'}}, 'required': ['begin', 'end', 'track_section'], 'type': 'object'}, 'type': 'array'}}, 'required': ['route', 'track_sections'], 'type': 'object'}, 'title': 'schema', 'type': 'array'}, 'via': {'items': {'additionalProperties': False, 'properties': {'geographic': {'type': 'string'}, 'name': {'type': 'string'}, 'position': {'additionalProperties': False, 'properties': {'offset': {'type': 'number'}, 'track_section': {'type': 'number'}}, 'required': ['offset', 'track_section'], 'type': 'object'}, 'schematic': {'type': 'string'}, 'stop_time': {'type': 'number'}, 'suggestion': {'type': 'bool'}}, 'required': ['name', 'position', 'suggestion', 'stop_time'], 'type': 'object'}, 'title': 'schema', 'type': 'array'}}, 'required': ['path', 'operational_points'], 'type': 'object'})]),
        ),
    ]
