# Generated by Django 3.2.2 on 2021-06-17 15:31

from django.db import migrations, models
import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0020_remove_phases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='payload',
            field=models.JSONField(validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'path': {'items': {'additionalProperties': False, 'properties': {'route': {'type': 'number'}, 'track_sections': {'items': {'additionalProperties': False, 'properties': {'begin': {'type': 'number'}, 'end': {'type': 'number'}, 'track_section': {'type': 'number'}}, 'required': ['begin', 'end', 'track_section'], 'type': 'object'}, 'type': 'array'}}, 'required': ['route', 'track_sections'], 'type': 'object'}, 'title': 'schema', 'type': 'array'}, 'steps': {'items': {'additionalProperties': False, 'properties': {'geographic': {'items': {'type': 'number'}, 'maxItems': 2, 'minItems': 2, 'type': 'array'}, 'name': {'type': 'string'}, 'position': {'additionalProperties': False, 'properties': {'offset': {'type': 'number'}, 'track_section': {'type': 'number'}}, 'required': ['offset', 'track_section'], 'type': 'object'}, 'schematic': {'type': 'string'}, 'stop_time': {'type': 'number'}, 'suggestion': {'type': 'bool'}}, 'required': ['name', 'position', 'suggestion', 'stop_time'], 'type': 'object'}, 'title': 'schema', 'type': 'array'}}, 'required': ['path', 'steps'], 'type': 'object'})]),
        ),
    ]
