# Generated by Django 3.1.6 on 2021-06-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0021_alter_path_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollingstock',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
