# Generated by Django 3.1.6 on 2021-06-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0022_rollingstock_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingstock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
