# Generated by Django 3.2.2 on 2021-06-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0023_auto_20210617_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainScheduleLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='labels',
            field=models.ManyToManyField(blank=True, to='osrd_infra.TrainScheduleLabel'),
        ),
    ]
