# Generated by Django 3.2.5 on 2021-08-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0025_change_timetable_json_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='infra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.infra'),
        ),
        migrations.AlterField(
            model_name='trainschedule',
            name='rolling_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.rollingstock'),
        ),
    ]
