# Generated by Django 3.1.6 on 2021-08-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0026_alter_timetable_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollingstock',
            name='power_class',
            field=models.PositiveIntegerField(default=1, help_text=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollingstock',
            name='traction_mode',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
