# Generated by Django 3.1.6 on 2021-08-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0027_auto_20210809_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingstock',
            name='power_class',
            field=models.PositiveIntegerField(help_text=''),
        ),
    ]
