# Generated by Django 3.2.5 on 2021-08-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0028_add_slopes_curves'),
    ]

    operations = [
        migrations.AddField(
            model_name='routecomponent',
            name='entry_direction',
            field=models.IntegerField(choices=[(0, 'Start To Stop'), (1, 'Stop To Start')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routecomponent',
            name='exit_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_routes', to='osrd_infra.waypointentity'),
        ),
        migrations.AlterField(
            model_name='routecomponent',
            name='entry_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_routes', to='osrd_infra.waypointentity'),
        ),
    ]
