coverage:
  round: down
  precision: 2
  status:
    project:
      default: off
      core:
        target: 75%
        threshold: 0.5%
        flags:
          - core
      editoast:
        target: 70%
        threshold: 0.5%
        flags:
          - editoast
      gateway:
        target: auto
        threshold: 0.5%
        flags:
          - gateway
      front:
        target: auto
        threshold: 0.5%
        flags:
          - front
    patch:
      default: off

flags:
  core:
    paths:
      - core/
  editoast:
    paths:
      - editoast/
  gateway:
    paths:
      - gateway/
  front:
    paths:
      - front/
