version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/editoast/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      opentelemetry:
        patterns:
          - "*opentelemetry*"
    commit-message:
      prefix: "editoast:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "area:editoast"
  - package-ecosystem: "cargo"
    directory: "/gateway/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5
    groups:
      opentelemetry:
        patterns:
          - "*opentelemetry*"
    commit-message:
      prefix: "gateway:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "area:gateway"
  - package-ecosystem: "cargo"
    directory: "/osrdyne/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5
    groups:
      opentelemetry:
        patterns:
          - "*opentelemetry*"
    commit-message:
      prefix: "osrdyne:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "area:osrdyne"
  - package-ecosystem: "npm"
    directory: "/front/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      nivo:
        patterns:
          - "@nivo/*"
      osrd-ui:
        patterns:
          - "@osrd-project/ui-*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      rjsf:
        patterns:
          - "@rjsf/*"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
          - "eslint-plugin-storybook"
      turf:
        patterns:
          - "@turf/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      patch:
        update-types:
          - "patch"
    commit-message:
      prefix: "front:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "area:front"
    ignore:
      # Updates for NGE don't follow SemVer and are handled manually
      - dependency-name: "@osrd-project/netzgrafik-frontend"
  - package-ecosystem: "uv"
    directories:
      - "python/osrd_schemas"
      - "python/railjson_generator"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5
    commit-message:
      prefix: "python:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "area:railjson"
  - package-ecosystem: "uv"
    directory: "/core/scripts/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    commit-message:
      prefix: "core: scripts:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "area:core"
    groups:
      patch:
        update-types:
          - "patch"
      minor:
        update-types:
          - "minor"
  - package-ecosystem: "uv"
    directory: "/tests/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    commit-message:
      prefix: "tests:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "area:integration-tests"
    groups:
      patch:
        update-types:
          - "patch"
      minor:
        update-types:
          - "minor"
  - package-ecosystem: "gradle"
    directory: "/core/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    commit-message:
      prefix: "core:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "area:core"
    groups:
      kotlin:
        patterns:
          - "kotlin"
          - "ksp"
      patch:
        update-types:
          - "patch"
      minor:
        update-types:
          - "minor"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5
    commit-message:
      prefix: "actions:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "area:ci"
  - package-ecosystem: "docker"
    directories:
      - "core"
      - "docker"
      - "editoast"
      - "front/docker"
      - "gateway"
      - "osrdyne"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    commit-message:
      prefix: "docker:"
    labels:
      - "dependencies"
  - package-ecosystem: "docker-compose"
    directories:
      - "/"
      - "docker"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    commit-message:
      prefix: "docker:"
    labels:
      - "dependencies"
  - package-ecosystem: "uv"
    directory: "/osrd_schemas_auto/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5
    commit-message:
      prefix: "osrd_schemas_auto:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
