[project]
name = "osrd-railway-manager-interface"
version = "0.2.7"
description = "Railway manager interface"
authors = [{ name = "OSRD Contributors", email = "contact@osrd.fr" }]
requires-python = ">=3.11"

dependencies = [
  "datamodel-code-generator==0.35.0",
  "openapi-pydantic==0.5.1",
  "pyyaml==6.0.3",
]

[dependency-groups]
dev = ["pyright~=1.1.409", "ruff~=0.15.10"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["osrd_railway_manager_interface"]
exclude = ["**/__pycache__"]
