version: '3'
volumes:
  psql_data:
  redis_data:
services:
  postgres:
    image: postgis/postgis:15-3.4-alpine
    container_name: osrd-postgres
    network_mode: host
    user: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - "psql_data:/var/lib/postgresql/data"
      - "./init_db.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres://osrd:password@localhost/osrd"]
      start_period: 4s
      interval: 5s

  redis:
    image: redis
    container_name: osrd-redis
    network_mode: host
    restart: unless-stopped
    volumes:
      - "redis_data:/data"
    command: "redis-server --save 30 1 --loglevel warning"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 4s
      interval: 5s

  core:
    image: osrd/core
    container_name: osrd-core
    network_mode: host
    build:
      context: core
      dockerfile: Dockerfile
      args:
        OSRD_GIT_DESCRIBE: ${OSRD_GIT_DESCRIBE}
    restart: unless-stopped
    command: "java -ea -jar /app/osrd_core.jar api -p 8080"
    environment:
      MIDDLEWARE_BASE_URL: "http://localhost:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      start_period: 4s
      interval: 5s

  front:
    image: osrd/front
    container_name: osrd-front
    build:
      context: front
      dockerfile: Dockerfile
      args:
        NGINX_CONFIG: "nginx-dev.conf"
        OSRD_GIT_DESCRIBE: ${OSRD_GIT_DESCRIBE}
    environment:
    - OSRD_LOCAL_BACKEND=true
    - OSRD_EDITOAST_URL=http://localhost:8090
    restart: unless-stopped
    ports: ["3000:80"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      start_period: 4s
      interval: 5s

  editoast:
    image: osrd/editoast
    container_name: osrd-editoast
    network_mode: host
    depends_on:
      postgres: {condition: service_healthy}
      redis: {condition: service_healthy}
    build:
      context: editoast
      dockerfile: Dockerfile
      args:
        OSRD_GIT_DESCRIBE: ${OSRD_GIT_DESCRIBE}
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://osrd:password@localhost:5432/osrd"
    command:
      - /bin/sh
      - -c
      - |
        diesel migration run
        editoast runserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      start_period: 4s
      interval: 5s

  wait-healthy:
    depends_on:
      editoast: {condition: service_healthy}
    restart: "no"
    image: alpine:latest
    command: "true"
