version = 1

[[annotations]]
path = ["*", "**/"]
SPDX-FileCopyrightText = "Copyright © 2022 The OSRD Contributors"
SPDX-License-Identifier = "LGPL-3.0-only"

[[annotations]]
path = ["README.md"]
SPDX-FileCopyrightText = "Copyright © 2022 The OSRD Contributors"
SPDX-License-Identifier = "LGPL-3.0-only OR GPL-3.0-only"
