CREATE TABLE paced_train (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    train_name varchar(128) NOT NULL,
    labels text [] NOT NULL,
    rolling_stock_name varchar(128) NOT NULL,
    timetable_id int8 NOT NULL REFERENCES timetable(id) ON DELETE CASCADE,
    start_time timestamptz NOT NULL,
    schedule jsonb NOT NULL,
    margins jsonb NOT NULL,
    initial_speed float8 NOT NULL,
    comfort smallint NOT NULL,
    path jsonb NOT NULL,
    constraint_distribution smallint NOT NULL,
    speed_limit_tag varchar(128),
    power_restrictions jsonb NOT NULL,
    options jsonb NOT NULL,
    duration interval NOT NULL,
    step interval NOT NULL
);

CREATE INDEX pga_idx_fk_paced_train_timetable_id ON public.paced_train (timetable_id);
