[package]
name = "osrd_gateway"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "actix_auth", "actix_proxy"]
# used for cargo test, build, fix, package, bench, doc, tree
default-members = [".", "actix_auth", "actix_proxy"]

[workspace.dependencies]
# common utils
dyn-clone = "1.0.20"
either = { version = "1", default-features = false }
env_logger = { version = "0.11", default-features = false }
futures = "0.3"
futures-util = { version = "0.3.31", default-features = false }
log = "0.4.28"
smallvec = "1.15.1"
thiserror = { version = "2.0.16", default-features = false }

# main crate
actix-cors = "0.7.1"
actix-files = "0.6"
actix-session = "0.10"
actix-web = { version = "4.11", features = [
  "macros",
], default-features = false }
actix-web-opentelemetry = { version = "0.22.0", features = ["awc"] }
base64ct = "1.8"
figment = "0.10.19"
humantime = "2"
humantime-serde = "1"
opentelemetry = { version = "0.30.0", default-features = false }
opentelemetry-otlp = { version = "0.30.0", features = [
  "grpc-tonic",
  "trace",
], default-features = false }
opentelemetry_sdk = { version = "0.30.0", default-features = false }
serde = { version = "1.0.225", default-features = false }
serde_json = "1"

# reverse proxy dependencies
actix = { version = "0.13", default-features = false }
actix-web-actors = "4.3"
awc = { version = "3", default-features = false } # the http / ws client
bytestring = "1"
ipnet = { version = "2.11", default-features = false }
percent-encoding = { version = "2.3", default-features = false }
phf = { version = "0.12", default-features = false }
regex = "1.11.2"

# actix_auth
actix-web-httpauth = "0.8"
openidconnect = { version = "4.0.1", default-features = false }
reqwest = { version = "0.12", default-features = false }
url = { version = "2.5", default-features = false }


[dependencies]
either.workspace = true
env_logger.workspace = true
log.workspace = true

# configuration parsing
base64ct.workspace = true # to parse the session secret key
figment = { workspace = true, features = ["env", "toml"] }
humantime.workspace = true
humantime-serde.workspace = true
serde.workspace = true

# web server
actix-cors.workspace = true
actix-files.workspace = true
actix-session = { workspace = true, features = ["cookie-session"] }
actix-web.workspace = true
actix_auth = { path = "./actix_auth" }
actix_proxy = { path = "./actix_proxy" }

# tracing / metrics
actix-web-opentelemetry.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
