[package]
name = "database"
license.workspace = true
version.workspace = true
edition.workspace = true

[features]
testing = []

[dependencies]
aws-lc-rs = { version = "1.17.1", default-features = false }
rustls-native-certs.workspace = true
sea-orm.workspace = true
sha1.workspace = true
sqlx.workspace = true
tokio.workspace = true
tokio-rustls = "0.26"
tracing.workspace = true
url.workspace = true
uuid.workspace = true
