import type { LayerProps } from 'react-map-gl/maplibre';

import type { MapStyle } from 'reducers/globalMap/types';

export default function getOSMMinimalStyle(_mapStyle: MapStyle): LayerProps[] {
  return [
    {
      id: 'background',
      type: 'background',
      paint: {
        'background-color': 'rgba(255, 255, 255, 1)',
      },
    },
    {
      id: 'park',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'park',
      layout: {
        visibility: 'none',
      },
      paint: {
        'fill-color': '#d8e8c8',
        'fill-opacity': 0.7,
        'fill-outline-color': 'rgba(95, 208, 100, 1)',
      },
    },
    {
      id: 'park_outline',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'park',
      layout: {
        visibility: 'none',
      },
      paint: {
        'line-dasharray': [1, 1.5],
        'line-color': 'rgba(228, 241, 215, 1)',
      },
    },
    {
      id: 'landuse_residential',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      maxzoom: 14,
      filter: ['==', 'class', 'residential'],
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-color': [
          'step',
          ['zoom'],
          'rgba(218, 216, 216, 0)',
          9,
          'rgba(218, 216, 216, 0.24)',
          12,
          'rgba(224, 215, 206, 0.32)',
        ],
      },
    },
    {
      id: 'landcover_wood',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['all', ['==', 'class', 'wood']],
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-antialias': false,
        'fill-color': 'rgba(201, 239, 187, 0.43)',
        'fill-opacity': 0.4,
      },
    },
    {
      id: 'landcover_grass',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['all', ['==', 'class', 'grass']],
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-antialias': false,
        'fill-color': 'rgba(176, 213, 154, 0.5)',
        'fill-opacity': 0.3,
      },
    },
    {
      id: 'landcover_ice',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['all', ['==', 'class', 'ice']],
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-antialias': false,
        'fill-color': 'rgba(214, 241, 237, 0.44)',
        'fill-opacity': 0.8,
      },
    },
    {
      id: 'landcover_wetland',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      minzoom: 12,
      filter: ['all', ['==', 'class', 'wetland']],
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-antialias': true,
        'fill-opacity': 0.8,
        'fill-translate-anchor': 'map',
        'fill-color': 'rgba(212, 188, 128, 0.12)',
      },
    },
    {
      id: 'landuse_pitch',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: ['==', 'class', 'pitch'],
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-color': 'rgba(176, 213, 154, 0.25)',
      },
    },
    {
      id: 'landuse_track',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: ['==', 'class', 'track'],
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-color': 'rgba(176, 213, 154, 0.25)',
      },
    },
    {
      id: 'landuse_cemetery',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: ['==', 'class', 'cemetery'],
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-color': 'rgba(222, 221, 203, 0.26)',
      },
    },
    {
      id: 'landuse_hospital',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: ['==', 'class', 'hospital'],
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-color': 'rgba(255, 229, 221, 0.59)',
      },
    },
    {
      id: 'landuse_school',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: ['==', 'class', 'school'],
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-color': 'rgba(250, 251, 100, 0.22)',
      },
    },
    {
      id: 'waterway_tunnel',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'waterway',
      filter: ['all', ['==', 'brunnel', 'tunnel']],
      paint: {
        'line-color': '#D4EEFD',
        'line-dasharray': [3, 3],
        'line-gap-width': ['interpolate', ['exponential', 1], ['zoom'], 12, 0, 20, 6],
        'line-opacity': 1,
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 8, 1, 20, 2],
      },
    },
    {
      id: 'waterway_river',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'waterway',
      filter: ['all', ['==', 'class', 'river'], ['!=', 'brunnel', 'tunnel']],
      layout: {
        'line-cap': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(223, 241, 251, 1)',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 11, 0.5, 20, 6],
      },
    },
    {
      id: 'waterway_other',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'waterway',
      filter: ['all', ['!=', 'class', 'river'], ['!=', 'brunnel', 'tunnel']],
      layout: {
        'line-cap': 'round',
      },
      paint: {
        'line-color': 'rgba(212, 238, 253, 1)',
        'line-width': ['interpolate', ['exponential', 1.3], ['zoom'], 13, 0.5, 20, 6],
      },
    },
    {
      id: 'water',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'water',
      filter: ['all', ['!=', 'brunnel', 'tunnel']],
      paint: {
        'fill-color': 'rgba(228, 242, 253, 1)',
      },
    },
    {
      id: 'landcover_sand',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['all', ['==', 'class', 'sand']],
      paint: {
        'fill-color': 'rgba(253, 250, 230, 1)',
      },
    },
    {
      id: 'aeroway_fill',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'aeroway',
      minzoom: 11,
      filter: ['==', '$type', 'Polygon'],
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-color': 'rgba(195, 255, 255, 0.35)',
        'fill-opacity': 0.7,
      },
    },
    {
      id: 'aeroway_runway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'aeroway',
      minzoom: 11,
      filter: ['all', ['==', '$type', 'LineString'], ['==', 'class', 'runway']],
      layout: {
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(188, 241, 235, 0.52)',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 11, 3, 20, 16],
      },
    },
    {
      id: 'aeroway_taxiway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'aeroway',
      minzoom: 11,
      filter: ['all', ['==', '$type', 'LineString'], ['==', 'class', 'taxiway']],
      layout: {
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(188, 241, 235, 0.52)',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 11, 0.5, 20, 6],
      },
    },
    {
      id: 'tunnel_path_pedestrian',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'tunnel'],
        ['in', 'class', 'path', 'pedestrian'],
      ],
      layout: {
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(247, 246, 246, 1)',
        'line-dasharray': [1, 0.75],
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 14, 0.5, 20, 10],
      },
    },
    {
      id: 'tunnel_motorway_link',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'class', 'motorway'], ['==', 'ramp', 1], ['==', 'brunnel', 'tunnel']],
      layout: {
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F7F6F6',
        'line-width': [
          'interpolate',
          ['exponential', 1.2],
          ['zoom'],
          12.5,
          0,
          13,
          1.5,
          14,
          2.5,
          20,
          11.5,
        ],
      },
    },
    {
      id: 'tunnel_link',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'ramp', 1], ['==', 'brunnel', 'tunnel']],
      layout: {
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(247, 246, 246, 1)',
        'line-width': [
          'interpolate',
          ['exponential', 1.2],
          ['zoom'],
          12.5,
          0,
          13,
          1.5,
          14,
          2.5,
          20,
          11.5,
        ],
      },
    },
    {
      id: 'tunnel_minor',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'brunnel', 'tunnel'], ['in', 'class', 'minor']],
      layout: {
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(247, 246, 246, 1)',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 13.5, 0, 14, 2.5, 20, 11.5],
      },
    },
    {
      id: 'tunnel_secondary_tertiary',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'brunnel', 'tunnel'], ['in', 'class', 'secondary', 'tertiary']],
      layout: {
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(247, 246, 246, 1)',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 6.5, 0, 7, 0.5, 20, 10],
      },
    },
    {
      id: 'tunnel_trunk_primary',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'brunnel', 'tunnel'], ['in', 'class', 'primary', 'trunk']],
      layout: {
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(247, 246, 246, 1)',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 5, 0, 7, 1, 20, 18],
      },
    },
    {
      id: 'tunnel_motorway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'class', 'motorway'], ['!=', 'ramp', 1], ['==', 'brunnel', 'tunnel']],
      layout: {
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F7F6F6',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 5, 0, 7, 1, 20, 18],
      },
    },
    {
      id: 'tunnel_major_rail',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'brunnel', 'tunnel'], ['in', 'class', 'rail']],
      layout: {
        visibility: 'none',
      },
      paint: {
        'line-color': 'rgba(0, 0, 0, 1)',
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14, 0.4, 15, 0.75, 20, 2],
      },
    },
    {
      id: 'tunnel_transit_rail',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'brunnel', 'tunnel'], ['in', 'class', 'transit']],
      layout: {
        visibility: 'none',
      },
      paint: {
        'line-color': 'rgba(187, 187, 187, 1)',
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14, 0.4, 15, 0.75, 20, 2],
      },
    },
    {
      id: 'road_path_pedestrian',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 14,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'path', 'pedestrian'],
      ],
      layout: {
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(245, 237, 237, 1)',
        'line-dasharray': [1.5, 1.5],
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 14, 1, 20, 5],
      },
    },
    {
      id: 'road_motorway_link',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 12,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['==', 'class', 'motorway'],
        ['==', 'ramp', 1],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F7F6F6',
        'line-width': [
          'interpolate',
          ['exponential', 1.2],
          ['zoom'],
          12.5,
          0,
          13,
          1.5,
          14,
          2.5,
          20,
          11.5,
        ],
      },
    },
    {
      id: 'road_service_track',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['!in', 'brunnel', 'bridge', 'tunnel'], ['in', 'class', 'service', 'track']],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'none',
      },
      paint: {
        'line-color': '#F7F6F6',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 15.5, 0, 16, 2, 20, 7.5],
      },
    },
    {
      id: 'road_link',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['==', 'ramp', 1],
        ['!in', 'class', 'pedestrian', 'path', 'track', 'service', 'motorway'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F7F6F6',
        'line-width': [
          'interpolate',
          ['exponential', 1.2],
          ['zoom'],
          12.5,
          0,
          13,
          1.5,
          14,
          2.5,
          20,
          11.5,
        ],
      },
    },
    {
      id: 'road_minor',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'minor'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F7F6F6',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 13.5, 0, 14, 2.5, 20, 18],
      },
    },
    {
      id: 'road_secondary_tertiary',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'secondary', 'tertiary'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F7F6F6',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 6.5, 0, 8, 0.5, 20, 13],
      },
    },
    {
      id: 'road_trunk_primary',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 10,
      filter: ['all', ['!in', 'brunnel', 'bridge', 'tunnel'], ['in', 'class', 'primary', 'trunk']],
      layout: {
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F7F6F6',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 5, 0, 7, 1, 20, 18],
      },
    },
    {
      id: 'road_motorway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['==', 'class', 'motorway'],
        ['!=', 'ramp', 1],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': [
          'step',
          ['zoom'],
          'rgba(0, 0, 0, 0)',
          5,
          'rgba(242, 147, 74, 0.55)',
          9,
          '#F7F6F6',
        ],
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 5, 0, 7, 1, 20, 18],
      },
    },
    {
      id: 'road_major_rail_hatching',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['!in', 'brunnel', 'bridge', 'tunnel'], ['==', 'class', 'rail']],
      layout: {
        visibility: 'none',
      },
      paint: {
        'line-color': '#000',
        'line-dasharray': [0.2, 8],
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14.5, 0, 15, 3, 20, 8],
      },
    },
    {
      id: 'road_transit_rail',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['!in', 'brunnel', 'bridge', 'tunnel'], ['==', 'class', 'transit']],
      layout: {
        visibility: 'none',
      },
      paint: {
        'line-color': '#bbb',
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14, 0.4, 15, 0.75, 20, 2],
      },
    },
    {
      id: 'road_major_rail',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['!in', 'brunnel', 'bridge', 'tunnel'], ['==', 'class', 'rail']],
      layout: {
        visibility: 'none',
      },
      paint: {
        'line-color': 'rgba(0, 0, 0, 1)',
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14, 0.4, 15, 0.75, 20, 2],
      },
    },
    {
      id: 'bridge_path_pedestrian',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'bridge'],
        ['in', 'class', 'path', 'pedestrian'],
      ],
      layout: {
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(228, 221, 221, 0.74)',
        'line-dasharray': [1, 1.5],
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 14, 0.5, 20, 5],
      },
    },
    {
      id: 'bridge_motorway_link',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'class', 'motorway'], ['==', 'ramp', 1], ['==', 'brunnel', 'bridge']],
      layout: {
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(247, 246, 246, 0.75)',
        'line-width': [
          'interpolate',
          ['exponential', 1.2],
          ['zoom'],
          12.5,
          0,
          13,
          1.5,
          14,
          2.5,
          20,
          11.5,
        ],
      },
    },
    {
      id: 'bridge_service_track',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'brunnel', 'bridge'], ['in', 'class', 'service', 'track']],
      layout: {
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(247, 246, 246, 0.75)',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 15.5, 0, 16, 2, 20, 7.5],
      },
    },
    {
      id: 'bridge_link',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'class', 'link'], ['==', 'brunnel', 'bridge']],
      layout: {
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(247, 246, 246, 0.75)',
        'line-width': [
          'interpolate',
          ['exponential', 1.2],
          ['zoom'],
          12.5,
          0,
          13,
          1.5,
          14,
          2.5,
          20,
          11.5,
        ],
      },
    },
    {
      id: 'bridge_street',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'brunnel', 'bridge'], ['in', 'class', 'minor']],
      layout: {
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(247, 246, 246, 0.75)',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 13.5, 0, 14, 2.5, 20, 18],
      },
    },
    {
      id: 'bridge_secondary_tertiary',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'brunnel', 'bridge'], ['in', 'class', 'secondary', 'tertiary']],
      layout: {
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(247, 246, 246, 0.75)',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 6.5, 0, 7, 0.5, 20, 10],
      },
    },
    {
      id: 'bridge_trunk_primary',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'brunnel', 'bridge'], ['in', 'class', 'primary', 'trunk']],
      layout: {
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(247, 246, 246, 0.75)',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 5, 0, 7, 1, 20, 18],
      },
    },
    {
      id: 'bridge_motorway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'class', 'motorway'], ['!=', 'ramp', 1], ['==', 'brunnel', 'bridge']],
      layout: {
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(247, 246, 246, 0.75)',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 5, 0, 7, 1, 20, 18],
      },
    },
    {
      id: 'bridge_major_rail',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'class', 'rail'], ['==', 'brunnel', 'bridge']],
      layout: {
        visibility: 'none',
      },
      paint: {
        'line-color': '#000',
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14, 0.4, 15, 0.75, 20, 2],
      },
    },
    {
      id: 'bridge_major_rail_hatching',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'class', 'rail'], ['==', 'brunnel', 'bridge']],
      layout: {
        visibility: 'none',
      },
      paint: {
        'line-color': '#000',
        'line-dasharray': [0.2, 8],
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14.5, 0, 15, 3, 20, 8],
      },
    },
    {
      id: 'bridge_transit_rail',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'class', 'transit'], ['==', 'brunnel', 'bridge']],
      layout: {
        visibility: 'none',
      },
      paint: {
        'line-color': '#bbb',
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 14, 0.5, 15, 0.75, 20, 2],
      },
    },
    {
      id: 'building',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'building',
      minzoom: 14,
      maxzoom: 17,
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-color': 'rgba(236, 236, 236, 0.75)',
        'fill-outline-color': 'hsla(35, 6%, 79%, 0.32)',
      },
    },
    {
      id: 'building-3d',
      type: 'fill-extrusion',
      source: 'openmaptiles',
      'source-layer': 'building',
      minzoom: 17,
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-extrusion-color': 'rgba(239, 236, 236, 1)',
        'fill-extrusion-height': {
          type: 'identity',
          property: 'render_height',
        },
        'fill-extrusion-base': {
          property: 'render_min_height',
          type: 'identity',
        },
        'fill-extrusion-opacity': 0.8,
      },
    },
    {
      id: 'water_name_line',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'waterway',
      filter: ['all', ['==', '$type', 'LineString']],
      layout: {
        'text-field': '{name}',
        'text-font': ['IBMPlexSerif-Italic'],
        'text-max-width': 5,
        'text-size': 11,
        'symbol-placement': 'line',
        visibility: 'visible',
        'text-letter-spacing': 0.04,
      },
      paint: {
        'text-color': 'rgba(106, 173, 218, 1)',
        'text-halo-color': 'rgba(255,255,255,0.7)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'water_name_point',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'water_name',
      filter: ['==', '$type', 'Point'],
      layout: {
        'text-field': '{name}',
        'text-font': ['IBMPlexSerif-Italic'],
        'text-max-width': 5,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(67, 166, 232, 1)',
        'text-halo-color': 'rgba(255,255,255,0.7)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'road_label',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'transportation_name',
      minzoom: 15,
      filter: ['all'],
      layout: {
        'symbol-placement': 'line',
        'text-anchor': 'center',
        'text-field': '{name}',
        'text-font': ['IBMPlexSerif-Regular'],
        'text-offset': [0, 0.15],
        'text-size': ['interpolate', ['exponential', 1], ['zoom'], 13, 10, 14, 11],
        visibility: 'visible',
        'text-letter-spacing': 0.05,
      },
      paint: {
        'text-color': 'rgba(181, 178, 178, 1)',
        'text-halo-blur': 0.5,
        'text-halo-width': 1,
      },
    },
    {
      id: 'road_shield',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'transportation_name',
      minzoom: 7,
      filter: ['all', ['<=', 'ref_length', 6]],
      layout: {
        'icon-image': 'default_{ref_length}',
        'icon-rotation-alignment': 'viewport',
        'symbol-placement': ['step', ['zoom'], 'point', 10, 'point', 11, 'line'],
        'symbol-spacing': 500,
        'text-field': '{ref}',
        'text-font': ['IBMPlexSerif-Regular'],
        'text-offset': [0, 0.1],
        'text-rotation-alignment': 'viewport',
        'text-size': 10,
        'icon-size': 0.8,
        visibility: 'none',
      },
    },
    {
      id: 'place_label_country',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      maxzoom: 9,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'country'], ['has', 'iso_a2']],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['IBMPlexSerif-Regular'],
        'text-letter-spacing': 0.138,
        'text-line-height': 22,
        'text-max-width': 20,
        'text-rotate': 0,
        'text-size': 18,
        'text-transform': 'uppercase',
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(148, 145, 142, 1)',
        'text-halo-blur': 0,
        'text-halo-color': 'rgba(255, 255, 255, 1)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_label_state',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      minzoom: 5,
      maxzoom: 16,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'state']],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['IBMPlexSerif-Italic'],
        'text-letter-spacing': 0.1,
        'text-line-height': 17,
        'text-rotate': 0,
        'text-size': 14,
        'text-transform': 'uppercase',
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(148, 145, 142, 1)',
        'text-halo-blur': 0,
        'text-halo-color': 'rgba(255, 255, 255, 1)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_label_city',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      minzoom: 5,
      maxzoom: 16,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'city']],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['IBMPlexSerif-Medium'],
        'text-line-height': 17,
        'text-rotate': 0,
        'text-size': 14,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(92,89,85, 1)',
        'text-halo-blur': 0,
        'text-halo-color': 'rgba(255, 255, 255, 1)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_label_town',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      minzoom: 5,
      maxzoom: 16,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'town']],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['IBMPlexSerif-Regular'],
        'text-line-height': 14,
        'text-rotate': 0,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(121,118,113, 1)',
        'text-halo-blur': 0,
        'text-halo-color': 'rgba(255, 255, 255, 1)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_label_village',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      minzoom: 5,
      maxzoom: 16,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'village']],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['IBMPlexSerif-Italic'],
        'text-line-height': 13,
        'text-rotate': 0,
        'text-size': 11,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(121, 118, 113, 1)',
        'text-halo-blur': 0,
        'text-halo-color': 'rgba(255, 255, 255, 1)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_label_hamlet',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      minzoom: 5,
      maxzoom: 16,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'hamlet']],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['IBMPlexSerif-Italic'],
        'text-letter-spacing': 0.05,
        'text-line-height': 11,
        'text-rotate': 0,
        'text-size': 9,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(121,118,113, 1)',
        'text-halo-blur': 0,
        'text-halo-color': 'rgba(255, 255, 255, 1)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_label_suburb',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      minzoom: 5,
      maxzoom: 16,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'suburb']],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['IBMPlexSerif-Regular'],
        'text-line-height': 11,
        'text-rotate': 0,
        'text-size': 9,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(121,118,113, 1)',
        'text-halo-blur': 0,
        'text-halo-color': 'rgba(255, 255, 255, 1)',
        'text-halo-width': 1,
      },
    },
  ];
}
