import type { LayerProps } from 'react-map-gl/maplibre';

import type { MapStyle } from 'reducers/globalMap/types';

export default function getOSMNormalStyle(_mapStyle: MapStyle): LayerProps[] {
  return [
    {
      id: 'background',
      type: 'background',
      paint: { 'background-color': 'rgba(246, 245, 241, 1)' },
    },
    {
      id: 'landuse-residential',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      minzoom: 8,
      filter: [
        'all',
        ['==', '$type', 'Polygon'],
        ['in', 'class', 'residential', 'suburb', 'neighbourhood'],
      ],
      layout: { visibility: 'visible' },
      paint: { 'fill-color': 'rgba(228, 226, 220, 1)', 'fill-opacity': 0.7 },
    },
    {
      id: 'landcover_grass',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      minzoom: 12,
      filter: ['==', 'class', 'grass'],
      paint: { 'fill-color': 'hsl(82, 46%, 72%)', 'fill-opacity': 0.25 },
    },
    {
      id: 'landcover_wood',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      minzoom: 7,
      filter: ['==', 'class', 'wood'],
      paint: {
        'fill-color': 'rgba(192, 216, 151, 0.3)',
        'fill-opacity': ['interpolate', ['exponential', 1], ['zoom'], 8, 0.6, 22, 1],
      },
    },
    {
      id: 'water',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'water',
      filter: [
        'all',
        ['==', '$type', 'Polygon'],
        ['!=', 'intermittent', 1],
        ['!=', 'brunnel', 'tunnel'],
      ],
      layout: { visibility: 'visible' },
      paint: {
        'fill-color': '#D9ECF2',
        'fill-antialias': true,
      },
    },
    {
      id: 'water-border-2',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'water',
      filter: [
        'all',
        ['==', '$type', 'Polygon'],
        ['!=', 'intermittent', 1],
        ['!=', 'brunnel', 'tunnel'],
        ['==', 'class', 'ocean'],
      ],
      layout: { visibility: 'visible' },
      minzoom: 8,
      paint: {
        'line-color': '#CDE6EE',
        'line-width': 4,
        'line-offset': 3.5,
      },
    },
    {
      id: 'water-border-1',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'water',
      filter: [
        'all',
        ['==', '$type', 'Polygon'],
        ['!=', 'intermittent', 1],
        ['!=', 'brunnel', 'tunnel'],
        ['==', 'class', 'ocean'],
      ],
      layout: { visibility: 'visible' },
      paint: {
        'line-color': '#B0D1DB',
        'line-width': 1.5,
        'line-offset': 0.75,
      },
    },
    {
      id: 'water-border',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'water',
      filter: [
        'all',
        ['==', '$type', 'Polygon'],
        ['!=', 'intermittent', 1],
        ['!=', 'brunnel', 'tunnel'],
        ['==', 'class', 'ocean'],
      ],
      layout: { visibility: 'visible' },
      paint: {
        'line-color': '#80A1AB',
        'line-width': 0.5,
        'line-offset': -0.25,
      },
    },
    {
      id: 'water-border-coast',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'water',
      filter: [
        'all',
        ['==', '$type', 'Polygon'],
        ['!=', 'intermittent', 1],
        ['!=', 'brunnel', 'tunnel'],
        ['==', 'class', 'ocean'],
      ],
      layout: { visibility: 'visible' },
      paint: {
        'line-color': '#FFFFFF',
        'line-width': 1,
        'line-offset': -1.25,
      },
    },
    {
      id: 'water_intermittent',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'water',
      filter: ['all', ['==', '$type', 'Polygon'], ['==', 'intermittent', 1]],
      layout: { visibility: 'visible' },
      paint: { 'fill-color': 'rgba(217, 236, 242, 1)', 'fill-opacity': 0.7 },
    },
    {
      id: 'landcover-ice-shelf',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['==', 'subclass', 'ice_shelf'],
      layout: { visibility: 'visible' },
      paint: { 'fill-color': 'hsl(47, 26%, 88%)', 'fill-opacity': 0.8 },
    },
    {
      id: 'landcover-glacier',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['==', 'subclass', 'glacier'],
      layout: { visibility: 'visible' },
      paint: {
        'fill-color': 'hsl(47, 22%, 94%)',
        'fill-opacity': ['interpolate', ['exponential', 1], ['zoom'], 0, 1, 8, 0.5],
      },
    },
    {
      id: 'landcover_sand',
      type: 'fill',
      metadata: {},
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['all', ['in', 'class', 'sand']],
      paint: {
        'fill-antialias': false,
        'fill-color': 'rgba(232, 214, 38, 1)',
        'fill-opacity': 0.3,
      },
    },
    {
      id: 'landuse',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: ['==', 'class', 'agriculture'],
      layout: { visibility: 'visible' },
      paint: { 'fill-color': '#eae0d0' },
    },
    {
      id: 'landuse_overlay_national_park',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['==', 'class', 'national_park'],
      paint: {
        'fill-color': '#E1EBB0',
        'fill-opacity': ['interpolate', ['exponential', 1], ['zoom'], 5, 0, 9, 0.75],
      },
    },
    {
      id: 'waterway-tunnel',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'waterway',
      filter: ['all', ['==', '$type', 'LineString'], ['==', 'brunnel', 'tunnel']],
      layout: { visibility: 'visible' },
      paint: {
        'line-color': 'hsl(205, 56%, 73%)',
        'line-dasharray': [3, 3],
        'line-gap-width': ['interpolate', ['exponential', 1], ['zoom'], 12, 0, 20, 6],
        'line-opacity': 1,
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 8, 1, 20, 2],
      },
    },
    {
      id: 'waterway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'waterway',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!in', 'brunnel', 'tunnel', 'bridge'],
        ['!=', 'intermittent', 1],
      ],
      layout: { visibility: 'visible' },
      paint: {
        'line-color': 'rgba(203, 232, 241, 1)',
        'line-opacity': 1,
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 8, 1, 20, 8],
      },
    },
    {
      id: 'waterway_intermittent',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'waterway',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!in', 'brunnel', 'tunnel', 'bridge'],
        ['==', 'intermittent', 1],
      ],
      layout: { visibility: 'visible' },
      paint: {
        'line-color': 'hsl(205, 56%, 73%)',
        'line-dasharray': [2, 1],
        'line-opacity': 1,
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 8, 1, 20, 8],
      },
    },
    {
      id: 'tunnel_railway_transit',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 0,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'tunnel'],
        ['==', 'class', 'transit'],
      ],
      layout: { 'line-cap': 'butt', 'line-join': 'miter' },
      paint: {
        'line-color': 'hsl(34, 12%, 66%)',
        'line-dasharray': [3, 3],
        'line-opacity': ['interpolate', ['exponential', 1], ['zoom'], 11, 0, 16, 1],
      },
    },
    {
      id: 'building',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'building',
      minzoom: 16,
      paint: {
        'fill-antialias': true,
        'fill-color': 'rgba(210, 210, 202, 1)',
        'fill-opacity': ['interpolate', ['exponential', 1], ['zoom'], 13, 0, 15, 1],
        'fill-outline-color': 'rgba(212, 177, 146, 0.5)',
      },
    },
    {
      id: 'housenumber',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'housenumber',
      minzoom: 17,
      filter: ['==', '$type', 'Point'],
      layout: {
        'text-field': '{housenumber}',
        'text-font': ['IBMPlexSerif-Regular'],
        'text-size': 10,
      },
      paint: { 'text-color': 'rgba(212, 177, 146, 1)' },
    },
    {
      id: 'road_area_pier',
      type: 'fill',
      metadata: {},
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: ['all', ['==', '$type', 'Polygon'], ['==', 'class', 'pier']],
      layout: { visibility: 'visible' },
      paint: { 'fill-antialias': true, 'fill-color': 'hsl(47, 26%, 88%)' },
    },
    {
      id: 'road_pier',
      type: 'line',
      metadata: {},
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: ['all', ['==', '$type', 'LineString'], ['in', 'class', 'pier']],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': 'hsl(47, 26%, 88%)',
        'line-width': ['interpolate', ['exponential', 1.2], ['zoom'], 15, 1, 17, 4],
      },
    },
    {
      id: 'road_bridge_area',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: ['all', ['==', '$type', 'Polygon'], ['in', 'brunnel', 'bridge']],
      layout: {},
      paint: { 'fill-color': 'hsl(47, 26%, 88%)', 'fill-opacity': 0.5 },
    },
    {
      id: 'road_path',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: ['all', ['==', '$type', 'LineString'], ['in', 'class', 'path', 'track']],
      layout: { 'line-cap': 'square', 'line-join': 'bevel' },
      paint: {
        'line-color': 'hsl(0, 0%, 97%)',
        'line-dasharray': [1, 1],
        'line-width': ['interpolate', ['exponential', 1.55], ['zoom'], 4, 0.25, 20, 10],
      },
    },
    {
      id: 'road_minor',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: ['all', ['==', '$type', 'LineString'], ['in', 'class', 'minor', 'service']],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': 'hsl(0, 0%, 97%)',
        'line-width': ['interpolate', ['exponential', 1.55], ['zoom'], 4, 0.25, 20, 30],
      },
    },
    {
      id: 'tunnel_minor',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'tunnel'],
        ['==', 'class', 'minor_road'],
      ],
      layout: { 'line-cap': 'butt', 'line-join': 'miter' },
      paint: {
        'line-color': '#efefef',
        'line-dasharray': [0.36, 0.18],
        'line-width': ['interpolate', ['exponential', 1.55], ['zoom'], 4, 0.25, 20, 30],
      },
    },
    {
      id: 'tunnel_major',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'tunnel'],
        ['in', 'class', 'primary', 'secondary', 'tertiary', 'trunk'],
      ],
      layout: { 'line-cap': 'butt', 'line-join': 'miter' },
      paint: {
        'line-color': '#fff',
        'line-dasharray': [0.28, 0.14],
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 6, 0.5, 20, 30],
      },
    },
    {
      id: 'aeroway-area',
      type: 'fill',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'aeroway',
      minzoom: 4,
      filter: ['all', ['==', '$type', 'Polygon'], ['in', 'class', 'runway', 'taxiway']],
      layout: { visibility: 'visible' },
      paint: {
        'fill-color': 'rgba(255, 255, 255, 1)',
        'fill-opacity': ['interpolate', ['exponential', 1], ['zoom'], 13, 0, 14, 1],
      },
    },
    {
      id: 'aeroway-taxiway',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'aeroway',
      minzoom: 12,
      filter: ['all', ['in', 'class', 'taxiway'], ['==', '$type', 'LineString']],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(255, 255, 255, 1)',
        'line-opacity': 1,
        'line-width': ['interpolate', ['exponential', 1.5], ['zoom'], 12, 1, 17, 10],
      },
    },
    {
      id: 'aeroway-runway',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'aeroway',
      minzoom: 7,
      filter: ['all', ['in', 'class', 'runway'], ['==', '$type', 'LineString']],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(231, 217, 243, 1)',
        'line-opacity': 1,
        'line-width': ['interpolate', ['exponential', 1.5], ['zoom'], 11, 4, 17, 50],
      },
    },
    {
      id: 'road_trunk_primary',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: ['all', ['==', '$type', 'LineString'], ['in', 'class', 'trunk', 'primary']],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#fff',
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 6, 0.5, 20, 30],
        'line-opacity': 0.7,
      },
    },
    {
      id: 'road_secondary_tertiary',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: ['all', ['==', '$type', 'LineString'], ['in', 'class', 'secondary', 'tertiary']],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#fff',
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 6, 0.5, 20, 20],
        'line-opacity': 0.7,
      },
    },
    {
      id: 'road_major_motorway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: ['all', ['==', '$type', 'LineString'], ['==', 'class', 'motorway']],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': 'rgba(242, 227, 175, 1)',
        'line-offset': 0,
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 8, 1, 16, 10],
        'line-opacity': ['interpolate', ['exponential', 1], ['zoom'], 4, 0.2, 14, 1],
      },
    },
    {
      id: 'railway-transit',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'class', 'transit'], ['!=', 'brunnel', 'tunnel']],
      layout: { visibility: 'visible' },
      paint: {
        'line-color': 'hsl(34, 12%, 66%)',
        'line-opacity': ['interpolate', ['exponential', 1], ['zoom'], 11, 1, 16, 1],
      },
    },
    {
      id: 'waterway-bridge-case',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'waterway',
      minzoom: 8,
      filter: ['all', ['==', '$type', 'LineString'], ['==', 'brunnel', 'bridge']],
      layout: { 'line-cap': 'butt', 'line-join': 'miter' },
      paint: {
        'line-color': '#bbbbbb',
        'line-gap-width': ['interpolate', ['exponential', 1.55], ['zoom'], 4, 0.25, 20, 30],
        'line-width': ['interpolate', ['exponential', 1.6], ['zoom'], 12, 0.5, 20, 10],
      },
    },
    {
      id: 'waterway-bridge',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'waterway',
      filter: ['all', ['==', '$type', 'LineString'], ['==', 'brunnel', 'bridge']],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': 'hsl(205, 56%, 73%)',
        'line-width': ['interpolate', ['exponential', 1.55], ['zoom'], 4, 0.25, 20, 30],
      },
    },
    {
      id: 'bridge_minor case',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 7,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'bridge'],
        ['==', 'class', 'minor_road'],
      ],
      layout: { 'line-cap': 'butt', 'line-join': 'miter' },
      paint: {
        'line-color': '#dedede',
        'line-gap-width': ['interpolate', ['exponential', 1.55], ['zoom'], 4, 0.25, 20, 30],
        'line-width': ['interpolate', ['exponential', 1.6], ['zoom'], 12, 0.5, 20, 10],
      },
    },
    {
      id: 'bridge_major case',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'bridge'],
        ['in', 'class', 'primary', 'secondary', 'tertiary', 'trunk'],
      ],
      layout: { 'line-cap': 'butt', 'line-join': 'miter' },
      paint: {
        'line-color': '#dedede',
        'line-gap-width': ['interpolate', ['exponential', 1.55], ['zoom'], 4, 0.25, 20, 30],
        'line-width': ['interpolate', ['exponential', 1.6], ['zoom'], 12, 0.5, 20, 10],
      },
    },
    {
      id: 'bridge_minor',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'bridge'],
        ['==', 'class', 'minor_road'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#efefef',
        'line-width': ['interpolate', ['exponential', 1.55], ['zoom'], 4, 0.25, 20, 30],
      },
    },
    {
      id: 'bridge_major',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 8,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'bridge'],
        ['in', 'class', 'primary', 'secondary', 'tertiary', 'trunk'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#fff',
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 6, 0.5, 20, 30],
      },
    },
    {
      id: 'admin_sub',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'boundary',
      minzoom: 8,
      filter: ['in', 'admin_level', 4, 6, 8],
      layout: { visibility: 'visible' },
      paint: {
        'line-color': 'rgba(153, 153, 153, 0.3)',
        'line-dasharray': [2, 1],
      },
    },
    {
      id: 'admin_country_z0-4',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'boundary',
      minzoom: 0,
      maxzoom: 1,
      filter: [
        'all',
        ['<=', 'admin_level', 2],
        ['==', '$type', 'LineString'],
        ['!has', 'claimed_by'],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': 'rgba(72, 157, 185, 1)',
        'line-width': ['interpolate', ['exponential', 1.3], ['zoom'], 3, 0.5, 22, 15],
        'line-opacity': 0.3,
      },
    },
    {
      id: 'admin_country_z5-',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'boundary',
      filter: ['all', ['<=', 'admin_level', 2], ['==', '$type', 'LineString']],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': 'rgba(187, 70, 37, 1)',
        'line-dasharray': [0, 2],
        'line-opacity': 0.3,
        'line-width': ['interpolate', ['exponential', 1.3], ['zoom'], 5, 1, 22, 15],
      },
    },
    {
      id: 'poi',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'poi',
      minzoom: 14,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'rank', 1]],
      layout: {
        'icon-size': 1,
        'text-anchor': 'top',
        'text-field': '{name:latin}\n{name:nonlatin}',
        'text-font': ['IBMPlexSerif-Regular'],
        'text-max-width': 8,
        'text-offset': [0, 0.5],
        'text-size': 11,
        visibility: 'visible',
      },
      paint: {
        'text-color': '#666',
        'text-halo-blur': 1,
        'text-halo-color': 'rgba(255,255,255,0.75)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'airport-label',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'aerodrome_label',
      minzoom: 10,
      filter: ['all', ['has', 'iata']],
      layout: {
        'icon-size': 1,
        'text-anchor': 'top',
        'text-field': '{name:latin}\n{name:nonlatin}',
        'text-font': ['IBMPlexSerif-Regular'],
        'text-max-width': 8,
        'text-offset': [0, 0.5],
        'text-size': 11,
        visibility: 'visible',
      },
      paint: {
        'text-color': '#666',
        'text-halo-blur': 1,
        'text-halo-color': 'rgba(255,255,255,0.75)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'road_major_label',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'transportation_name',
      minzoom: 13,
      filter: ['==', '$type', 'LineString'],
      layout: {
        'symbol-placement': 'line',
        'text-field': '{name:latin} {name:nonlatin}',
        'text-font': ['IBMPlexSerif-Regular'],
        'text-letter-spacing': 0.1,
        'text-rotation-alignment': 'map',
        'text-size': ['interpolate', ['exponential', 1.4], ['zoom'], 10, 8, 20, 14],
        'text-transform': 'uppercase',
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(121, 118, 113, 1)',
        'text-halo-color': 'hsl(0, 0%, 100%)',
        'text-halo-width': 2,
        'icon-halo-color': 'rgba(121, 118, 113, 1)',
      },
    },
    {
      id: 'place_label_country',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      maxzoom: 9,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'country'], ['has', 'iso_a2']],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['IBMPlexSerif-Regular'],
        'text-letter-spacing': 0.138,
        'text-line-height': 22,
        'text-max-width': 20,
        'text-rotate': 0,
        'text-size': 18,
        'text-transform': 'uppercase',
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(148, 145, 142, 1)',
        'text-halo-blur': 0,
        'text-halo-color': 'rgba(255, 255, 255, 1)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_label_state',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      minzoom: 5,
      maxzoom: 16,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'state']],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['IBMPlexSerif-Italic'],
        'text-letter-spacing': 0.1,
        'text-line-height': 17,
        'text-rotate': 0,
        'text-size': 14,
        'text-transform': 'uppercase',
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(148, 145, 142, 1)',
        'text-halo-blur': 0,
        'text-halo-color': 'rgba(255, 255, 255, 1)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_label_city',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      minzoom: 5,
      maxzoom: 16,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'city']],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['IBMPlexSerif-Medium'],
        'text-line-height': 17,
        'text-rotate': 0,
        'text-size': 14,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(92,89,85, 1)',
        'text-halo-blur': 0,
        'text-halo-color': 'rgba(255, 255, 255, 1)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_label_town',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      minzoom: 5,
      maxzoom: 16,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'town']],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['IBMPlexSerif-Regular'],
        'text-line-height': 14,
        'text-rotate': 0,
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(121,118,113, 1)',
        'text-halo-blur': 0,
        'text-halo-color': 'rgba(255, 255, 255, 1)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_label_village',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      minzoom: 5,
      maxzoom: 16,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'village']],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['IBMPlexSerif-Italic'],
        'text-line-height': 13,
        'text-rotate': 0,
        'text-size': 11,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(121, 118, 113, 1)',
        'text-halo-blur': 0,
        'text-halo-color': 'rgba(255, 255, 255, 1)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_label_hamlet',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      minzoom: 5,
      maxzoom: 16,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'hamlet']],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['IBMPlexSerif-Italic'],
        'text-letter-spacing': 0.05,
        'text-line-height': 11,
        'text-rotate': 0,
        'text-size': 9,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(121,118,113, 1)',
        'text-halo-blur': 0,
        'text-halo-color': 'rgba(255, 255, 255, 1)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place_label_suburb',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      minzoom: 5,
      maxzoom: 16,
      filter: ['all', ['==', '$type', 'Point'], ['==', 'class', 'suburb']],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['IBMPlexSerif-Regular'],
        'text-line-height': 11,
        'text-rotate': 0,
        'text-size': 9,
        visibility: 'visible',
      },
      paint: {
        'text-color': 'rgba(121,118,113, 1)',
        'text-halo-blur': 0,
        'text-halo-color': 'rgba(255, 255, 255, 1)',
        'text-halo-width': 1,
      },
    },
  ];
}
