plugins {
    alias(libs.plugins.kotlin.jvm)
}

tasks.register('rustBuildRelease', Exec) {
    group = 'build'
    description = 'Builds the rust binary with optimizations enabled'

    workingDir 'libtsim'
    commandLine 'cargo', 'build', '--package', 'tsim-ffi', '--release'

    // Register all crates as input to avoid having to maintain the list, should
    // the number of crates increase. In any case, cargo build incrementally
    // and false positives won't incur great timelosses.
    inputs.dir 'libtsim/crates'
    inputs.file 'libtsim/Cargo.toml'
    inputs.file 'libtsim/Cargo.lock'

    // Hard-code `build/` instead of using layout.buildDirectory, because we
    // don't really care about where libtsim_ffi.so gets built as long as cargo
    // and gradle agree on a location. Otherwise we could set the env var
    // CARGO_TARGET_DIR to match gradle's layout.buildDirectory here, but then
    // running cargo outside of gradle would recompile everything in `build/`,
    // as configured in `.cargo/config.toml`.
    outputs.file 'build/rust/release/libtsim_ffi.so'
}

tasks.register('rustTest', Exec) {
    group = 'verification'
    description = 'Runs the rust tests'

    workingDir 'libtsim'
    commandLine 'cargo', 'test'
    inputs.dir 'libtsim/crates'
    inputs.file 'libtsim/Cargo.toml'
    inputs.file 'libtsim/Cargo.lock'
}
tasks.test.dependsOn tasks.named('rustTest')

tasks.register('generateKotlinBindings', Exec) {
    group = 'build'
    description = 'Re-generates and overwrites the kotlin bindings. Use this during development'

    workingDir 'libtsim'
    commandLine 'cargo', 'run', '--package', 'uniffi-bindgen', '--',
            'generate',
            '--no-format', // let spotless format it
            '--library', tasks.rustBuildRelease.outputs.files[0],
            '--language', 'kotlin',
            '--out-dir', '../src/main/kotlin'

    inputs.file tasks.named('rustBuildRelease').map { it.outputs.files[0] }

    // Register tsim-ffi crate sources as inputs of this task so that it runs
    // when the FFI changes
    inputs.dir 'libtsim/crates/tsim-ffi'
    inputs.file 'libtsim/Cargo.toml'
    inputs.file 'libtsim/Cargo.lock'

    outputs.dir 'src/main/kotlin'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.jna
}

// Ensure rustBuildRelease is ran whenever the rust files change.
// We hook onto the java plugin's processResources task so that we run cargo
// both for shadowJar and for tests.
tasks.processResources.dependsOn tasks.named('rustBuildRelease')
