plugins {
    alias(libs.plugins.kotlin.jvm)
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.jna
}

tasks.register('rustBuildRelease', Exec) {
    group = 'build'
    description = 'Builds the rust binary with optimizations enabled'

    workingDir 'libtsim'
    commandLine 'cargo', 'build', '--package', 'tsim-ffi', '--release'

    // Hard-code `build/` instead of using layout.buildDirectory, because we
    // don't really care about where libtsim_ffi.so gets built as long as cargo
    // and gradle agree on a location. Otherwise we could set the env var
    // CARGO_TARGET_DIR to match gradle's layout.buildDirectory here, but then
    // running cargo outside of gradle would recompile everything in `build/`,
    // as configured in `.cargo/config.toml`.
    outputs.file 'build/rust/release/libtsim_ffi.so'

    // Always run the task and rely on cargo to build when necessary
    outputs.upToDateWhen { false }
}

tasks.register('generateKotlinBindings', Exec) {
    group = 'build'
    description = 'Re-generates and overwrites the kotlin bindings. Use this during development'

    workingDir 'libtsim'
    commandLine 'cargo', 'run', '--package', 'uniffi-bindgen', '--',
                'generate',
                '--no-format', // let spotless format it
                '--library', '../build/rust/release/libtsim_ffi.so',
                '--language', 'kotlin',
                '--out-dir', '../src/main/kotlin'

    inputs.file tasks.named('rustBuildRelease').map { it.outputs.getFiles()[0] }

    // Register tsim-ffi crate sources as inputs of this task so that it runs
    // when the FFI changes
    inputs.dir 'libtsim/crates/tsim-ffi/src'

    outputs.dir 'src/main/kotlin'
}
