[package]
name = "core_client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
common = { workspace = true }
dashmap.workspace = true
deadpool.workspace = true
editoast_derive.workspace = true
educe.workspace = true
futures.workspace = true
futures-util.workspace = true
geos.workspace = true
hostname.workspace = true
http = { workspace = true }
itertools.workspace = true
lapin.workspace = true
opentelemetry.workspace = true
ordered-float.workspace = true
schemas = { workspace = true, features = ["testing"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream = "0.1.18"
tracing.workspace = true
tracing-opentelemetry.workspace = true
url.workspace = true
utoipa.workspace = true
uuid.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
schemas = { workspace = true, features = ["testing"] }

[lints]
workspace = true
