-- Recreate legacy tables so older migrations can roll back

-- train_schedule
CREATE TABLE train_schedule (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    train_name varchar(128) NOT NULL,
    labels text[] NOT NULL,
    rolling_stock_name varchar(128) NOT NULL,
    timetable_id int8 NOT NULL REFERENCES timetable(id) ON DELETE CASCADE,
    start_time timestamptz NOT NULL,
    schedule jsonb NOT NULL,
    margins jsonb NOT NULL,
    initial_speed float8 NOT NULL,
    comfort smallint NOT NULL,
    path jsonb NOT NULL,
    constraint_distribution smallint NOT NULL,
    speed_limit_tag varchar(128),
    power_restrictions jsonb NOT NULL,
    options jsonb NOT NULL,
    main_category train_main_category,
    sub_category varchar(255),
    CONSTRAINT only_one_category CHECK (sub_category IS NULL OR main_category IS NULL)
);

-- Indexes to match common access patterns
CREATE INDEX pga_idx_fk_train_schedule_timetable_id ON public.train_schedule (timetable_id);

-- Foreign key to sub_categories table
ALTER TABLE train_schedule
ADD CONSTRAINT fk_train_schedule_sub_category FOREIGN KEY (sub_category) REFERENCES sub_categories(code) ON DELETE SET NULL;

-- train_schedule_round_trips
CREATE TABLE train_schedule_round_trips (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    left_id int8 NOT NULL UNIQUE REFERENCES train_schedule(id) ON DELETE CASCADE,
    right_id int8 UNIQUE REFERENCES train_schedule(id) ON DELETE CASCADE,
    CONSTRAINT id_order CHECK (right_id IS NULL OR left_id < right_id)
);
