apiVersion: gateway.dgexsol.fr/v1
kind: ApiDefinition
metadata:
  name: osrd-core-tmp-def-{{ .Values.realm }}
  labels:
    gateway/target: {{ .Values.realm }}
spec:
  app_name: /osrd_core
  forward_path: ""
  host: osrd-core-{{ .Values.realm }}-osrd-core:8000
  mode:
    endpoints:
    - method: POST
      path: /simulation/
    - method: POST
      path: /pathfinding/routes/
    - method: POST
      path: /pathfinding/tracks/
    kind: forward_strict
