{{- if .Values.services.editoast.cronjob.schedule -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osrd.fullname" . }}-editoast-cronjob
data:
  cronjob.sh: |
    #!/bin/sh
    set -euo pipefail
    {{- with .Values.services.editoast.cronjob.extend }}
    {{ . | nindent 4 }}
    {{- end }}
    editoast gc
---
{{ $mergedLabels := merge (dict "name" (printf "%s-editoast-cronjob" (include "osrd.fullname" .))) (default (dict) $.Values.services.editoast.cronjob.labels) -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "osrd.fullname" . }}-editoast-cronjob
  labels:
    {{- toYaml ($mergedLabels | default dict) | nindent 4 }}
spec:
  schedule: "{{ .Values.services.editoast.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          containers:
          - name: {{ include "osrd.name" . }}-editoast-cronjob
            image: "{{ .Values.images.editoast }}"
            imagePullPolicy: {{ .Values.pullPolicy }}
            command: ["/bin/sh"]
            args: ["/crons/cronjob.sh"]
            env:
              - name: EDITOAST_PORT
                value: "{{ .Values.services.editoast.service.targetPort }}"
              - name: OSRDYNE_API_URL
                value: http://{{ include "osrd.fullname" . }}-osrdyne
              - name: ROOT_URL
                value: "{{ .Values.endpoints.public }}/api"
              - name: OSRD_MQ_URL
                {{- $amqp := .Values.endpoints.amqp.url }}
                {{- if eq (kindOf $amqp) "map" }}
                valueFrom:
                  {{- toYaml $amqp.valueFrom | nindent 18 }}
                {{- else }}
                value: "{{ $amqp }}"
                {{- end }}
              - name: DATABASE_URL
                {{- $postgresql := .Values.endpoints.postgresql }}
                {{- if eq (kindOf $postgresql) "map" }}
                valueFrom:
                  {{- toYaml $postgresql.valueFrom | nindent 18 }}
                {{- else }}
                value: "{{ $postgresql }}"
                {{- end }}
              - name: VALKEY_URL
                {{- $redis := .Values.endpoints.redis }}
                {{- if eq (kindOf $redis) "map" }}
                valueFrom:
                  {{- toYaml $redis.valueFrom | nindent 18 }}
                {{- else }}
                value: "{{ $redis }}"
                {{- end }}
              - name: FGA_API_URL
                value: "http://{{ include "osrd.fullname" . }}-openfga:{{ .Values.services.openfga.service.port }}"
              {{- with .Values.services.editoast.cronjob.env | default dict }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            resources:
              {{- toYaml .Values.services.editoast.resources | nindent 14 }}
            volumeMounts:
              - name: config
                mountPath: /crons/cronjob.sh
                subPath: cronjob.sh
          volumes:
            - name: config
              configMap:
                name: {{ include "osrd.fullname" . }}-editoast-cronjob
          restartPolicy: Never
{{- end }}
