{{- if .Values.services.editoast.permanent_storage_size -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: editoast_volume
  namespace: {{ .Release.Namespace }}
spec:
  accessMode: ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.services.editoast.permanent_storage_size }}
{{- end -}}
