[package]
name = "editoast"
license.workspace = true
version.workspace = true
edition.workspace = true

[workspace]
members = [
  ".",
  "authz",
  "cache",
  "common",
  "core_client",
  "core_task",
  "database",
  "editoast_derive",
  "editoast_models",
  "fga",
  "fga_derive",
  "fga_migrations",
  "osm_to_railjson",
  "schemas",
  "search",
]

[workspace.lints.rust]
async_fn_in_trait = "allow" # all of our public traits are only used inside the project
dependency_on_unit_never_type_fallback = "allow" # this is caused by tracing, we can't do anything about it

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "LGPL-3.0"

[workspace.dependencies]
approx = "0.5.1"
arcstr = { version = "1.2.0", features = ["serde"] }
authz = { path = "./authz" }
cache = { path = "./cache" }
chrono = { version = "0.4.44", default-features = false, features = ["serde"] }
clap = { version = "4.6", features = ["derive", "env"] }
common = { path = "./common" }
core_client = { path = "./core_client" }
core_task = { path = "./core_task" }
darling = "0.23"
dashmap = "6.1.0"
database = { path = "./database" }
deadpool = { version = "0.13.0", default-features = false, features = [
  "managed",
  "rt_tokio_1",
  "unmanaged",
] }
deadpool-redis = { version = "0.23", default-features = false, features = [
  "tokio-comp",
  "tokio-native-tls-comp",
] }
derive_more = { version = "2.1.1", features = [
  "debug",
  "deref",
  "display",
  "from",
  "from_str",
] }
diesel = { version = "2.3", default-features = false, features = [
  "32-column-tables",
  "chrono",
  "postgres",
  "serde_json",
  "uuid",
] }
diesel-async = { version = "0.9", default-features = false, features = [
  "deadpool",
  "migrations",
  "postgres",
] }
diesel_json = "0.3.0"
editoast_derive = { path = "./editoast_derive" }
editoast_models = { path = "./editoast_models" }
educe = "0.6.0"
enum-map = "2.7.3"
fga = { path = "./fga", features = ["test_utilities"] }
fga_migrations = { path = "./fga_migrations" }
flate2 = "1.1.9"
futures = "0.3.32"
futures-util = "0.3.30"
geos = { version = "11.1.1", features = ["json"] }
hostname = "0.4.2"
http = "1.4"
indexmap = "2.13"
itertools = "0.14.0"
lapin = { version = "4.7.4", default-features = false, features = ["tokio"] }
linkme = "0.3.36"
mvt = "0.13.0"
object_store = { version = "0.13.2", features = ["aws"] }
openssl = "0.10.80"
opentelemetry = { version = "0.32.0", default-features = false, features = [
  "trace",
] }
opentelemetry-otlp = { version = "0.32.0", default-features = false, features = [
  "grpc-tonic",
  "trace",
] }
opentelemetry-semantic-conventions = { version = "0.32", features = [
  "semconv_experimental",
] }
opentelemetry_sdk = { version = "0.32.0", default-features = false, features = [
  "internal-logs",
  "rt-tokio",
  "trace",
] }
ordered-float = { version = "5.3.0", features = ["serde"] }
postgis_diesel = { version = "3.1.0", features = ["serde"] }
postgres-openssl = "0.5.3"
pretty_assertions = "1.4.1"
proc-macro2 = "1.0"
quote = "1.0"
rand = "0.10.1"
rangemap = "1.7.1"
regex = "1.12"
reqwest = { version = "0.13.3", default-features = false, features = ["json"] }
rstest = { version = "0.26.1", default-features = false }
schemas = { path = "./schemas" }
search = { path = "./search" }
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = "1.0.149"
serde_norway = "0.9.42"
serde_with = { version = "3.20.0", default-features = false, features = [
  "macros",
] }
sha1 = "0.11"
stdext = "0.3.3"
strum = { version = "0.28.0", features = ["derive"] }
syn = "2.0"
tempfile = "3.20.0" # redis-test (crate cache) isn't up to date
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["fs", "macros", "rt-multi-thread"] }
tokio-postgres = "0.7.17"
tracing = { version = "0.1.44", default-features = false, features = [
  "attributes",
  "log",
] }
tracing-opentelemetry = { version = "0.33.0", default-features = false, features = [
  "tracing-log",
] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uom = { version = "0.38.0", default-features = false, features = ["f64", "si"] }
url = { version = "2.5.8", features = ["serde"] }
urlencoding = "2.1.3"
utoipa = { git = "https://github.com/osrd-project/utoipa.git", rev = "5103a24a6d6", features = [
  "chrono",
  "uuid",
] }
uuid = { version = "1.23.1", features = ["serde", "v4"] }
zstd = "0.13.3"

[dependencies]
anyhow = "1.0"
approx.workspace = true
arcstr.workspace = true
authz.workspace = true
axum = { version = "0.8.7", default-features = false, features = [
  "http1",
  "json",
  "multipart",
  "query",
  "tracing",
] }
axum-extra = { version = "0.12.2", default-features = false, features = [
  "typed-header",
] }
axum-streams = { version = "0.25.0", features = ["json"] }
axum-tracing-opentelemetry = { version = "0.38.0", default-features = false, features = [
  "tracing_level_info",
] }
buildid = "1.0.4"
cache.workspace = true
chrono.workspace = true
clap.workspace = true
colored = "3.0.0"
common = { workspace = true }
core_client = { workspace = true }
core_task = { path = "./core_task" }
dashmap.workspace = true
database.workspace = true
deadpool-redis.workspace = true
derive_more.workspace = true
diesel.workspace = true
diesel-async = { workspace = true }
diesel_json.workspace = true
editoast_derive.workspace = true
editoast_models.workspace = true
educe.workspace = true
enum-map.workspace = true
fga.workspace = true
fga_migrations.workspace = true
flate2.workspace = true
futures.workspace = true
futures-util.workspace = true
geos.workspace = true
headers = "0.4.1"
image = { version = "0.25.9", default-features = false, features = [
  "bmp",
  "gif",
  "jpeg",
  "png",
  "tiff",
  "webp",
] }
inventory = "0.3"
itertools.workspace = true
json-patch = { version = "4.1.0", default-features = false, features = [
  "utoipa",
] }
linkme.workspace = true
object_store.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
ordered-float.workspace = true
pathfinding = "4.14.0"
petgraph = "0.8.2"
postgis_diesel.workspace = true
rand.workspace = true
rangemap.workspace = true
reqwest.workspace = true
schemas.workspace = true
search = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_norway.workspace = true
serde_with.workspace = true
sha1.workspace = true
strum.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream = "0.1.18"
tower = "0.5.2"
tower-http = { version = "0.6.6", features = [
  "compression-full",
  "cors",
  "decompression-full",
  "fs",
  "limit",
  "normalize-path",
  "trace",
] }
tracing.workspace = true
tracing-subscriber.workspace = true
uom.workspace = true
url.workspace = true
utoipa.workspace = true
uuid.workspace = true

[dev-dependencies]
authz = { workspace = true }
axum = { version = "0.8.4", default-features = false, features = [
  "macros",
  "multipart",
  "tracing",
] }
axum-test = { version = "20.0", default-features = false }
core_client = { workspace = true }
database = { workspace = true, features = ["testing"] }
editoast_models = { workspace = true, features = ["testing"] }
fga = { path = "./fga", features = ["test_utilities"] }
pretty_assertions.workspace = true
rstest.workspace = true
schemas = { workspace = true, features = ["testing"] }
stdext.workspace = true
tempfile.workspace = true

[patch.crates-io]
utoipa = { git = "https://github.com/osrd-project/utoipa.git", rev = "5103a24a6d6" }

[lints]
workspace = true

[profile.dev]
debug = "limited"

[profile.dev-for-debug]
inherits = "dev"
debug = "full"

# Makes snapshot diffs faster to compute.
# insta is used in editast_derive to track changes made to proc-macros.
# Cf. https://insta.rs/docs/quickstart/#optional-faster-runs
[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
