#!/usr/bin/env just --justfile

# Display available recipes
help:
    @just --list --unsorted

run:
    @echo "This component is only about test (see `just test`)"

# Install required dependencies
install:
    uv sync --all-extras

# Run the tests
test:
    uv run pytest

# Format the source code
format:
    uv run ruff format

# Verify code lints without applying any fix
lint:
    uv run ruff check
    uv run pyright

# Fix all the lints that can be automatically applied
fix-lint:
    uv run ruff check --fix
