export const LAYER_GROUPS = Object.freeze({
  MAP_BACKGROUND: Symbol('MAP_BACKGROUND'),
  TOPOGRAPHY: Symbol('TOPOGRAPHY'),
  TRACKS: Symbol('TRACKS'),
  INFRA: Symbol('INFRA'),
  SIGNALS: Symbol('SIGNALS'),
  DYN_SIGNALS: Symbol('DYN_SIGNALS'),
  TRAIN: Symbol('TRAIN'),
});

export const LAYER_GROUPS_ORDER = Object.freeze({
  [LAYER_GROUPS.MAP_BACKGROUND]: 0,
  [LAYER_GROUPS.TOPOGRAPHY]: 1,
  [LAYER_GROUPS.TRACKS]: 2,
  [LAYER_GROUPS.INFRA]: 3,
  [LAYER_GROUPS.SIGNALS]: 4,
  [LAYER_GROUPS.DYN_SIGNALS]: 5,
  [LAYER_GROUPS.TRAIN]: 6,
});

/**
 * Virtual layers are the topmost layer of each group.
 * for example, virtual-layer-0 will be on top of all layers of group 0.
 * Layers of group MAP_BACKGROUND (0) will have boeforeId: 'virtual-layer-0'
 * Layers of group TOPOGRAPHY (1) will have boeforeId: 'virtual-layer-1'
 * etc
 */
export const LAYERS = Object.freeze({
  // 0
  BACKGROUND: { GROUP: LAYER_GROUPS.MAP_BACKGROUND },
  // 1
  PLATFORMS: { GROUP: LAYER_GROUPS.TOPOGRAPHY },
  // 2
  TRACKS_GEOGRAPHIC: { GROUP: LAYER_GROUPS.TRACKS },
  TRACKS_OSM: { GROUP: LAYER_GROUPS.TRACKS },
  TRACKS_SCHEMATIC: { GROUP: LAYER_GROUPS.TRACKS },
  ITINERARY: { GROUP: LAYER_GROUPS.TRACKS },
  // 3
  ROUTES: { GROUP: LAYER_GROUPS.INFRA },
  OPERATIONAL_POINTS: { GROUP: LAYER_GROUPS.INFRA },
  CATENARIES: { GROUP: LAYER_GROUPS.INFRA },
  BUFFER_STOPS: { GROUP: LAYER_GROUPS.INFRA },
  DETECTORS: { GROUP: LAYER_GROUPS.INFRA },
  SWITCHES: { GROUP: LAYER_GROUPS.INFRA },
  LINE_SEARCH: { GROUP: LAYER_GROUPS.INFRA },
  // 4
  SPEED_LIMITS: { GROUP: LAYER_GROUPS.SIGNALS },
  // 5
  SIGNALS: { GROUP: LAYER_GROUPS.DYN_SIGNALS },
  // 6
  TRAIN: { GROUP: LAYER_GROUPS.TRAIN },
});
