CREATE TABLE IF NOT EXISTS macro_note (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    scenario_id int8 NOT NULL, 
    x int8 NOT NULL,
    y int8 NOT NULL,
    title text NOT NULL,
    text text NOT NULL,
    labels text[] NOT NULL,
	CONSTRAINT fk_scenario
      FOREIGN KEY(scenario_id) 
        REFERENCES scenario(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_macro_note_scenario_id ON macro_note(scenario_id);
