mod margins;
pub use margins::MarginValue;
pub use margins::Margins;

// 'pub' to remove when schemas/train_schedule.rs is deleted
pub mod schedule_item;
pub use schedule_item::ReceptionSignal;
pub use schedule_item::ScheduleItem;

// 'pub' to remove when schemas/train_schedule.rs is deleted
pub mod path_item;
pub use path_item::OperationalPointPartReference;
pub use path_item::OperationalPointReference;
pub use path_item::PathItem;
pub use path_item::PathItemLocation;

mod train_schedule_options;
pub use train_schedule_options::TrainScheduleOptions;

mod power_restriction_item;
pub use power_restriction_item::PowerRestrictionItem;

mod distribution;
pub use distribution::Distribution;

mod comfort;
pub use comfort::Comfort;

mod allowance;
pub use allowance::Allowance;
pub use allowance::AllowanceDistribution;
pub use allowance::AllowanceValue;
pub use allowance::EngineeringAllowance;
pub use allowance::RangeAllowance;
pub use allowance::StandardAllowance;

mod rjs_power_restriction_range;
pub use rjs_power_restriction_range::RjsPowerRestrictionRange;

use std::collections::HashSet;

use chrono::DateTime;
use chrono::Utc;
use serde::Deserialize;
use serde::Deserializer;
use serde::Serialize;
use serde_with::DefaultOnNull;
use serde_with::serde_as;
use serde_with::skip_serializing_none;
use utoipa::ToSchema;
use utoipa::openapi::ObjectBuilder;
use utoipa::openapi::RefOr;
use utoipa::openapi::schema::Schema;

use crate::primitives::NonBlankString;
use crate::primitives::PositiveDuration;
use crate::rolling_stock::TrainCategory;
use crate::train_schedule::TrainSchedule;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ToSchema)]
pub struct Paced {
    /// Duration of the paced train, an ISO 8601 format is expected
    pub time_window: PositiveDuration,
    /// Time between two occurrences, an ISO 8601 format is expected
    pub interval: PositiveDuration,
    #[serde(default)]
    #[schema(required)]
    pub exceptions: Vec<PacedTrainException>,
}

#[derive(Debug, Clone, Serialize, PartialEq, ToSchema)]
pub struct PacedTrain {
    #[serde(flatten)]
    pub train_schedule_base: TrainSchedule,
    #[schema(inline)]
    pub paced: Option<Paced>,
}

impl<'de> Deserialize<'de> for PacedTrain {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct PacedTrainJson {
            #[serde(flatten)]
            pub train_schedule_base: TrainSchedule,
            pub paced: Option<Paced>,
        }
        let raw = PacedTrainJson::deserialize(deserializer)?;

        if let Some(ref paced) = raw.paced {
            let mut seen_keys = HashSet::with_capacity(paced.exceptions.len());
            for e in &paced.exceptions {
                if !seen_keys.insert(&e.key) {
                    return Err(serde::de::Error::custom(format!(
                        "Duplicate exception key: '{}'",
                        e.key
                    )));
                }
            }

            let time_window_secs = paced.time_window.num_seconds();
            let interval_secs = paced.interval.num_seconds();
            let num_occurrences = (time_window_secs / interval_secs) as usize;

            for ex in &paced.exceptions {
                if let ExceptionType::Modified { occurrence_index } = ex.exception_type
                    && occurrence_index > num_occurrences
                {
                    return Err(serde::de::Error::custom(format!(
                        "Modified exception '{}' references invalid occurrence index {}",
                        ex.key, occurrence_index,
                    )));
                }
            }
        }
        Ok(PacedTrain {
            train_schedule_base: raw.train_schedule_base,
            paced: raw.paced,
        })
    }
}

/// Represents an exception for a paced train occurrence.
/// Occurrences are normally generated from a base paced train.
/// An exception occurs when an occurrence is added or modified
/// compared to the base model. Each field corresponds to a "ChangeGroup" of attributes
/// that may deviate from the paced train.
/// - Created: A new occurrence manually added by the user, not originally present in the automatically generated occurrences based on the paced train.
/// - Modified: An existing occurrence that has been changed
#[skip_serializing_none]
#[serde_as]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, ToSchema)]
#[cfg_attr(feature = "testing", derive(Default))]
pub struct PacedTrainException {
    /// Unique key for the exception within the paced train, required and generated by the frontend.
    pub key: String,
    #[serde(flatten)]
    #[schema(inline)]
    pub exception_type: ExceptionType,
    #[serde[default]]
    #[serde_as(as = "DefaultOnNull")]
    pub disabled: bool,
    #[schema(nullable = false)]
    pub train_name: Option<TrainNameChangeGroup>,
    #[schema(nullable = false)]
    pub rolling_stock: Option<RollingStockChangeGroup>,
    #[schema(nullable = false)]
    pub rolling_stock_category: Option<RollingStockCategoryChangeGroup>,
    #[schema(nullable = false)]
    pub labels: Option<LabelsChangeGroup>,
    #[schema(nullable = false)]
    pub speed_limit_tag: Option<SpeedLimitTagChangeGroup>,
    #[schema(nullable = false)]
    pub start_time: Option<StartTimeChangeGroup>,
    #[schema(nullable = false)]
    pub constraint_distribution: Option<ConstraintDistributionChangeGroup>,
    #[schema(nullable = false)]
    pub initial_speed: Option<InitialSpeedChangeGroup>,
    #[schema(nullable = false)]
    pub options: Option<OptionsChangeGroup>,
    #[schema(nullable = false)]
    pub path_and_schedule: Option<PathAndScheduleChangeGroup>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum ExceptionType {
    Modified { occurrence_index: usize },
    // Created is a struct variant (not unit) to allow proper deserialization with #[serde(untagged)].
    // This avoids ambiguity with an empty object `{}`.
    // Must be declared after more specific variants, as order matters for untagged enums.
    Created {},
}

#[cfg(feature = "testing")]
impl Default for ExceptionType {
    fn default() -> Self {
        ExceptionType::Created {}
    }
}

impl utoipa::PartialSchema for ExceptionType {
    fn schema() -> RefOr<Schema> {
        let modified_schema = ObjectBuilder::new()
            .property(
                "occurrence_index",
                ObjectBuilder::new().schema_type(utoipa::openapi::schema::SchemaType::Type(
                    utoipa::openapi::schema::Type::Integer,
                )),
            )
            .build();
        modified_schema.into()
    }
}

impl ToSchema for ExceptionType {}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, ToSchema)]
pub struct TrainNameChangeGroup {
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, ToSchema)]
pub struct RollingStockChangeGroup {
    pub rolling_stock_name: String,
    pub comfort: Comfort,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, ToSchema)]
pub struct RollingStockCategoryChangeGroup {
    pub value: Option<TrainCategory>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, ToSchema)]
pub struct LabelsChangeGroup {
    pub value: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, ToSchema)]
pub struct SpeedLimitTagChangeGroup {
    #[schema(inline)]
    pub value: Option<NonBlankString>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, ToSchema)]
pub struct StartTimeChangeGroup {
    pub value: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, ToSchema)]
pub struct ConstraintDistributionChangeGroup {
    pub value: Distribution,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, ToSchema)]
pub struct InitialSpeedChangeGroup {
    pub value: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, ToSchema)]
pub struct OptionsChangeGroup {
    pub value: TrainScheduleOptions,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, ToSchema)]
pub struct PathAndScheduleChangeGroup {
    pub path: Vec<PathItem>,
    pub schedule: Vec<ScheduleItem>,
    pub margins: Margins,
    pub power_restrictions: Vec<PowerRestrictionItem>,
}
