-- Your SQL goes here
CREATE TABLE
    sub_categories (
        id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(255) NOT NULL,
        code VARCHAR(255) NOT NULL UNIQUE,
        main_category train_main_category NOT NULL,
        color VARCHAR(7) NOT NULL,
        background_color VARCHAR(7) NOT NULL,
        hovered_color VARCHAR(7) NOT NULL
    );

CREATE INDEX idx_sub_categories_code ON sub_categories (code);

ALTER TABLE paced_train
ADD COLUMN sub_category VARCHAR(255);

ALTER TABLE paced_train
ADD CONSTRAINT fk_paced_train_sub_category
FOREIGN KEY (sub_category)
REFERENCES sub_categories (code)
ON DELETE SET NULL;

ALTER TABLE paced_train ADD CONSTRAINT only_one_category CHECK (
    (sub_category IS NULL)
    OR (main_category IS NULL)
);

ALTER TABLE train_schedule
ADD COLUMN sub_category VARCHAR(255);

ALTER TABLE train_schedule
ADD CONSTRAINT fk_train_schedule_sub_category
FOREIGN KEY (sub_category)
REFERENCES sub_categories (code) ON DELETE SET NULL;

ALTER TABLE train_schedule ADD CONSTRAINT only_one_category CHECK (
    (sub_category IS NULL)
    OR (main_category IS NULL)
);
