import { requestedPoint } from '../../../utils/manchette';
import type { StationData } from '../../../utils/types';

export const invalidUniqueTrainTimetableOutput: StationData[] = [
  {
    stationName: 'North_East_station',
    stationCh: 'BV',
    trackName: '',
    requestedArrival: '11:45:43',
    requestedDeparture: '',
    stopTime: '',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    margin: { theoretical: '5 %', theoreticalS: '', actual: '', difference: '' },
    calculatedArrival: '',
    calculatedDeparture: '',
  },
  {
    stationName: requestedPoint('1'),
    stationCh: '',
    trackName: 'V1',
    requestedArrival: '',
    requestedDeparture: '',
    stopTime: '',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    margin: { theoretical: '', theoreticalS: '', actual: '', difference: '' },
    calculatedArrival: '',
    calculatedDeparture: '',
  },
  {
    stationName: 'Mid_East_station',
    stationCh: 'BV',
    trackName: '',
    requestedArrival: '',
    requestedDeparture: '',
    stopTime: '124',
    signalReceptionClosed: true,
    shortSlipDistance: true,
    margin: { theoretical: '', theoreticalS: '', actual: '', difference: '' },
    calculatedArrival: '',
    calculatedDeparture: '',
  },
  {
    stationName: requestedPoint('3'),
    stationCh: '',
    trackName: 'V1',
    requestedArrival: '',
    requestedDeparture: '',
    stopTime: '',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    margin: { theoretical: '', theoreticalS: '', actual: '', difference: '' },
    calculatedArrival: '',
    calculatedDeparture: '',
  },
  {
    stationName: 'Mid_West_station',
    stationCh: 'BV',
    trackName: '',
    requestedArrival: '14:41:37',
    requestedDeparture: '14:51:37',
    stopTime: '600',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    margin: { theoretical: '5 %', theoreticalS: '', actual: '', difference: '' },
    calculatedArrival: '',
    calculatedDeparture: '',
  },
  {
    stationName: requestedPoint('5'),
    stationCh: '',
    trackName: 'V1',
    requestedArrival: '',
    requestedDeparture: '',
    stopTime: '',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    margin: { theoretical: '', theoreticalS: '', actual: '', difference: '' },
    calculatedArrival: '',
    calculatedDeparture: '',
  },
  {
    stationName: 'North_West_station',
    stationCh: 'BC',
    trackName: '',
    requestedArrival: '',
    requestedDeparture: '',
    stopTime: '0',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    margin: { theoretical: '', theoreticalS: '', actual: '', difference: '' },
    calculatedArrival: '',
    calculatedDeparture: '',
  },
];
