import { requestedPoint } from '../../../utils/manchette';
import type { TimesStopsTableRow } from '../../../utils/times-stops-table-types';

export const invalidUniqueTrainWithReferenceBaseArrivalOutput: TimesStopsTableRow[] = [
  {
    index: 1,
    status: '',
    stationName: 'North_East_station',
    stationCh: 'BV',
    trackName: '',
    requestedArrival: '11:45:43',
    calculatedArrival: '',
    stopTime: '',
    requestedDeparture: '',
    calculatedDeparture: '•',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: {
      requestedTheoretical: '5%',
      computedTheoretical: '00m03s',
      real: '01m00s',
      difference: '-01m03s',
    },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
    referenceBaseArrival: '11:45:43',
  },
  {
    index: 2,
    status: '',
    stationName: requestedPoint('1'),
    stationCh: '',
    trackName: 'V1',
    requestedArrival: '11:46:00',
    calculatedArrival: '',
    stopTime: '',
    requestedDeparture: '',
    calculatedDeparture: '•',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: { requestedTheoretical: '5%', computedTheoretical: '', real: '', difference: '' },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
    referenceBaseArrival: '11:47:00',
  },
  {
    index: 3,
    status: '',
    stationName: 'Mid_East_station',
    stationCh: 'BV',
    trackName: '',
    requestedArrival: '',
    calculatedArrival: '',
    stopTime: '00h02m04s',
    requestedDeparture: '',
    calculatedDeparture: '•',
    signalReceptionClosed: true,
    shortSlipDistance: true,
    powerRestriction: '',
    margin: { requestedTheoretical: '', computedTheoretical: '', real: '', difference: '' },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
    referenceBaseArrival: '',
  },
  {
    index: 4,
    status: '',
    stationName: requestedPoint('3'),
    stationCh: '',
    trackName: 'V1',
    requestedArrival: '',
    calculatedArrival: '',
    stopTime: '',
    requestedDeparture: '',
    calculatedDeparture: '•',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: { requestedTheoretical: '', computedTheoretical: '', real: '', difference: '' },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
    referenceBaseArrival: '',
  },
  {
    index: 5,
    status: '',
    stationName: 'Mid_West_station',
    stationCh: 'BV',
    trackName: '',
    requestedArrival: '14:41:37',
    calculatedArrival: '',
    stopTime: '00h10m00s',
    requestedDeparture: '14:51:37',
    calculatedDeparture: '•',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: { requestedTheoretical: '5%', computedTheoretical: '', real: '', difference: '' },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
    referenceBaseArrival: '',
  },
  {
    index: 6,
    status: '',
    stationName: requestedPoint('5'),
    stationCh: '',
    trackName: 'V1',
    requestedArrival: '',
    calculatedArrival: '',
    stopTime: '',
    requestedDeparture: '',
    calculatedDeparture: '•',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: { requestedTheoretical: '', computedTheoretical: '', real: '', difference: '' },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
    referenceBaseArrival: '',
  },
  {
    index: 7,
    status: '',
    stationName: 'North_West_station',
    stationCh: 'BC',
    trackName: '',
    requestedArrival: '',
    calculatedArrival: '',
    stopTime: '00h00m00s',
    requestedDeparture: '',
    calculatedDeparture: '•',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: { requestedTheoretical: '', computedTheoretical: '', real: '', difference: '' },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
    referenceBaseArrival: '',
  },
];
