import { requestedDestination } from '../../../pages/operational-studies/std-manchette';
import { requestedPoint } from '../../../utils/manchette';
import type { TimesStopsTableRow } from '../../../utils/times-stops-table-types';

export const invalidPacedTrainTimetableOutput: TimesStopsTableRow[] = [
  {
    index: 1,
    status: '',
    stationName: 'North_East_station',
    stationCh: 'BV',
    trackName: '',
    requestedArrival: '11:45:43',
    calculatedArrival: '',
    stopTime: '',
    requestedDeparture: '',
    calculatedDeparture: '•',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: { requestedTheoretical: '0%', computedTheoretical: '', real: '', difference: '' },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
  },
  {
    index: 2,
    status: '',
    stationName: requestedPoint('1'),
    stationCh: '',
    trackName: 'V1',
    requestedArrival: '',
    calculatedArrival: '',
    stopTime: '00h05m00s',
    requestedDeparture: '',
    calculatedDeparture: '•',
    signalReceptionClosed: true,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: { requestedTheoretical: '', computedTheoretical: '', real: '', difference: '' },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
  },
  {
    index: 3,
    status: '',
    stationName: requestedDestination,
    stationCh: '',
    trackName: 'A',
    requestedArrival: '',
    calculatedArrival: '',
    stopTime: '00h00m00s',
    requestedDeparture: '',
    calculatedDeparture: '•',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: { requestedTheoretical: '', computedTheoretical: '', real: '', difference: '' },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
  },
];
