CREATE TABLE IF NOT EXISTS macro_node (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    scenario_id int8 NOT NULL, 
    position_x float8 NOT NULL,
    position_y float8 NOT NULL,
    full_name varchar(255),
    connection_time  int8 NOT NULL DEFAULT 0,
    labels text[] NOT NULL,
    trigram varchar(25),
    path_item_key varchar(255) NOT NULL,
  UNIQUE (scenario_id, path_item_key),
	CONSTRAINT fk_scenario
      FOREIGN KEY(scenario_id) 
        REFERENCES scenario(id)
);
