import type { AspectLabel } from './types';

export const TAG_COLORS = {
  MISSING: '#94918E',
  GIVEN_TRAIN: '#494641',
  FALLBACK: '#216482',
  INCOMPATIBLE: '#EAA72B',
};

export const OCCUPANCY_BLOCKS_COLORS = {
  FREE: '#CAEDDB',
  SEMAPHORE: '#FFD4D8',
  WARNING: '#FFEABF',
  GREY: '#D3D1CF',
};

export const ASPECT_LABELS_COLORS: Record<AspectLabel, string> = {
  VL: OCCUPANCY_BLOCKS_COLORS.FREE,
  '300VL': OCCUPANCY_BLOCKS_COLORS.FREE,
  S: OCCUPANCY_BLOCKS_COLORS.SEMAPHORE,
  OCCUPIED: OCCUPANCY_BLOCKS_COLORS.SEMAPHORE,
  C: OCCUPANCY_BLOCKS_COLORS.SEMAPHORE,
  RRR: OCCUPANCY_BLOCKS_COLORS.SEMAPHORE,
  '(A)': OCCUPANCY_BLOCKS_COLORS.WARNING,
  A: OCCUPANCY_BLOCKS_COLORS.WARNING,
  '300(VL)': OCCUPANCY_BLOCKS_COLORS.GREY,
  '270A': OCCUPANCY_BLOCKS_COLORS.GREY,
  '220A': OCCUPANCY_BLOCKS_COLORS.GREY,
  '160A': OCCUPANCY_BLOCKS_COLORS.GREY,
  '080A': OCCUPANCY_BLOCKS_COLORS.GREY,
  '000': OCCUPANCY_BLOCKS_COLORS.GREY,
};
