name: "🐛 Bug Report"
description: Report a bug encountered while operating OSRD
labels: kind:bug
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: |
        Please provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How can we reproduce it (as minimally and precisely as possible)?
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: What operating system and browser are you using? (if applicable)
      value: |
        - Windows 10
        - Google Chrome 22
    validations:
      required: false

  - type: input
    id: osrdVersion
    attributes:
      label: OSRD version
      value: "1.0"
    validations:
      required: true
