CREATE TABLE catalog_entry (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) CONSTRAINT catalog_entry_name_unique UNIQUE
);
CREATE TABLE train_schedule_set (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    catalog_entry_id int8 REFERENCES catalog_entry(id),
    name VARCHAR(255),
    description TEXT NOT NULL DEFAULT '',
    published BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT train_schedule_set_catalog_entry_or_not_published CHECK (
        NOT published
        OR catalog_entry_id IS NOT NULL
    ),
    CONSTRAINT train_schedule_set_name_or_not_catalog_entry CHECK (
        catalog_entry_id IS NULL
        OR name IS NOT NULL
    )
);
CREATE UNIQUE INDEX train_schedule_set_catalog_entry_name_published_unique ON train_schedule_set (catalog_entry_id, name)
WHERE published = TRUE;
