export const SAMPLE_COLUMNS = [
  { key: 'index', label: '', className: 'col-index' },
  { key: 'name', label: 'operational point', className: 'col-name' },
  { key: 'track', label: 'track', className: 'col-track' },
  { key: 'requestedArrival', label: 'requested arrival', className: 'col-requested-arrival' },
  {
    key: 'computedArrival',
    label: 'computed arrival',
    className: 'col-computed-arrival',
  },
  { key: 'stoppingTime', label: 'stopping time', className: 'col-stopping-time' },
  { key: 'requestedDeparture', label: 'requested departure', className: 'col-requested-departure' },
  {
    key: 'computedDeparture',
    label: 'computed departure',
    className: 'col-computed-departure',
  },
];

export const SAMPLE_DATA = [
  {
    index: 1,
    name: 'Paris-Gare-de-Lyon',
    track: '2MS',
    requestedArrival: '09:00:00',
    computedArrival: '09:00:00',
    stoppingTime: '',
    requestedDeparture: '',
    computedDeparture: '09:16',
  },
  {
    index: 2,
    name: 'Laroche-Migennes',
    track: 'V1BIS',
    requestedArrival: '',
    computedArrival: '10:10:15',
    stoppingTime: '00:02:00',
    requestedDeparture: '',
    computedDeparture: '10:12:15',
  },
  {
    index: 3,
    name: 'Dijon-Ville',
    track: 'V1',
    requestedArrival: '',
    computedArrival: '11:35:50',
    stoppingTime: '',
    requestedDeparture: '',
    computedDeparture: '',
  },
  {
    index: 4,
    name: 'Tournus',
    track: 'V1',
    requestedArrival: '12:30:30',
    computedArrival: '12:30:30',
    stoppingTime: '',
    requestedDeparture: '12:40:00',
    computedDeparture: '12:40:00',
  },
  {
    index: 5,
    name: 'Lyon-Part-Dieu',
    track: 'G',
    requestedArrival: '13:00:00',
    computedArrival: '13:05:20',
    stoppingTime: '',
    requestedDeparture: '',
    computedDeparture: '',
  },
];
