plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.ksp)
    id 'java-test-fixtures'
    id 'jacoco'
}


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    // PLEASE ADD AND UPDATE DEPENDENCIES USING libs.versions.toml
    api project(":kt-osrd-utils")
    api project(':kt-osrd-sim-infra')
    api project(':kt-railjson-builder')
    api project(":osrd-railjson")
    api project(":osrd-reporting")
    implementation project(':osrd-geom')
    implementation project(':osrd-mp')
    testFixturesApi project(":osrd-mp")

    implementation libs.guava
    implementation libs.kotlin.logging
    testImplementation libs.kotlin.test
    implementation libs.hppc
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        freeCompilerArgs += [
                "-opt-in=kotlin.RequiresOptIn",
                "-opt-in=kotlin.ExperimentalUnsignedTypes",
                "-opt-in=kotlin.time.ExperimentalTime",
                "-opt-in=kotlin.contracts.ExperimentalContracts",
        ]
    }
}
