services:
  editoast:
    environment:
      - EDITOAST_CORE_SINGLE_WORKER=true

  rabbitmq:
    environment:
      - RABBITMQ_HEARTBEAT=43200 # 12h heartbeat

  osrdyne:
    volumes: !reset []
    environment:
      - OSRDYNE__QUEUE_UNBIND_DELAY=30y
      - OSRDYNE__QUEUE_DELETE_DELAY=30y

  core:
    # Launch a single worker handling all infra
    environment:
      - ALL_INFRA=true
      - WORKER_AMQP_HEARTBEAT=43200 # 12h heartbeat
    container_name: osrd-core-all-infra
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - "exec java $JAVA_OPTS -ea -jar /app/osrd_core.jar worker"
