services:
  editoast:
    environment:
      - EDITOAST_CORE_SINGLE_WORKER=true

  rabbitmq:
    volumes:
      - "./docker/rabbitmq-single-worker.conf:/etc/rabbitmq/conf.d/99-osrd.conf"

  osrdyne:
    volumes: !reset []
    environment:
      - OSRDYNE__QUEUE_UNBIND_DELAY=30y
      - OSRDYNE__QUEUE_DELETE_DELAY=30y

  core:
    # Launch a single worker handling all infra
    environment:
      - ALL_INFRA=true
    container_name: osrd-core-all-infra
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - "exec java $JAVA_OPTS -ea -jar /app/osrd_core.jar worker"
