version: '3'

services:
  core-test:
    image: ghcr.io/openrailassociation/osrd-edge/osrd-core:${TAG-dev}
    container_name: osrd-core-test
    restart: unless-stopped
    ports: ["8080:8080"]
    command: "java -ea -jar /app/osrd_core.jar api -p 8080"
    environment:
      CORE_EDITOAST_URL: "http://osrd-editoast"
      JAVA_TOOL_OPTIONS: "-javaagent:/app/opentelemetry-javaagent.jar"
      CORE_MONITOR_TYPE: "opentelemetry"
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: "grpc"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://jaeger:4317"
      OTEL_METRICS_EXPORTER: "none"
      OTEL_LOGS_EXPORTER: "none"
