# This config file is copied into the host networking dev container

# generate a production key with this command:
# python3 -c "import secrets, base64; print(base64.standard_b64encode(secrets.token_bytes(64)).decode())"
secret_key = "NOT+A+SECRET++NOT+A+SECRET++NOT+A+SECRET++NOT+A+SECRET++NOT+A+SECRET++NOT+A+SECRET++NOT+A+SECRET"

listen_addr = "0.0.0.0"

[telemetry.tracing]
enable = true
endpoint = "http://localhost:4317"

[[targets]]
tracing_name = "editoast"
prefix = "/api"
upstream = "http://localhost:8090"
require_auth = true

[[targets]]
tracing_name = "front"
upstream = "http://localhost:3000"
require_auth = false

[[targets]]
tracing_name = "images"
prefix = "/images"
upstream = "http://localhost:8080"
require_auth = false

[auth]
default_provider = "mock"
secure_cookies = false

[[auth.providers]]
type = "Mocked"
provider_id = "mock"
username = "Example User"
require_login = false
