[worker_driver]
type = "DockerDriver"
# TODO: How do we pre-build the image for developers if it's not in the docker compose anymore ?
# Tentative answer: we keep it in the docker compose, but the container just run /bin/true...
core_image_name = "ghcr.io/openrailassociation/osrd-edge/osrd-core"
core_image_tag = "dev"
container_prefix = "osrd"
container_command = [
    "sh",
    "-c",
    "exec java $JAVA_OPTS -ea -jar /app/osrd_core.jar worker",
]
default_env = [
    "CORE_EDITOAST_URL=http://osrd-editoast",
    "JAVA_TOOL_OPTIONS=-javaagent:/app/opentelemetry-javaagent.jar",
    "CORE_MONITOR_TYPE=opentelemetry",
    "OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc",
    "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jaeger:4317",
    "OTEL_METRICS_EXPORTER=none",
    "OTEL_LOGS_EXPORTER=none",
]
