# Generated by Django 4.1.5 on 2023-01-25 11:32

import django.db.models.deletion
from django.db import migrations, models
import django.db.models.deletion
import osrd_schemas.train_schedule
from django.db import migrations, models

import osrd_infra.utils
from osrd_infra.migrations import run_sql_add_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ElectricalProfilesSet",
            new_name="ElectricalProfileSet",
        ),
        migrations.AlterModelOptions(
            name="electricalprofileset",
            options={"verbose_name_plural": "Electrical profile sets"},
        ),
        run_sql_add_foreign_key("timetable", "electrical_profile_set", "electricalprofileset", nullable=True),
        migrations.AddField(
            model_name="trainschedulemodel",
            name="modes_and_profiles",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="trainschedulemodel",
            name="allowances",
            field=models.JSONField(
                default=list,
                validators=[osrd_infra.utils.PydanticValidator(osrd_schemas.train_schedule.Allowances)],
            ),
        ),
        migrations.AlterField(
            model_name="trainschedulemodel",
            name="labels",
            field=models.JSONField(
                default=list,
                validators=[osrd_infra.utils.PydanticValidator(osrd_schemas.train_schedule.TrainScheduleLabels)],
            ),
        ),
    ]
