# Generated by Django 3.2.9 on 2022-01-19 18:22

from django.db import migrations, models
import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainschedule',
            old_name='base_simulation_log',
            new_name='eco_simulation',
        ),
        migrations.RemoveField(
            model_name='trainschedule',
            name='eco_simulation_log',
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='base_simulation',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pathmodel',
            name='payload',
            field=models.JSONField(validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'definitions': {'Direction': {'description': 'An enumeration.', 'enum': ['START_TO_STOP', 'STOP_TO_START'], 'title': 'Direction', 'type': 'string'}, 'DirectionalTrackRange': {'properties': {'begin': {'title': 'Begin', 'type': 'number'}, 'direction': {'$ref': '#/definitions/Direction'}, 'end': {'title': 'End', 'type': 'number'}, 'track': {'$ref': '#/definitions/ObjectReference'}}, 'required': ['track', 'begin', 'end', 'direction'], 'title': 'DirectionalTrackRange', 'type': 'object'}, 'ObjectReference': {'properties': {'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'type': {'title': 'Type', 'type': 'string'}}, 'required': ['id', 'type'], 'title': 'ObjectReference', 'type': 'object'}, 'PathWaypoint': {'properties': {'duration': {'title': 'Duration', 'type': 'number'}, 'geo': {'$ref': '#/definitions/Point'}, 'name': {'title': 'Name', 'type': 'string'}, 'position': {'title': 'Position', 'type': 'number'}, 'sch': {'$ref': '#/definitions/Point'}, 'suggestion': {'title': 'Suggestion', 'type': 'boolean'}, 'track': {'$ref': '#/definitions/ObjectReference'}}, 'required': ['track', 'position', 'geo', 'sch', 'suggestion', 'duration'], 'title': 'PathWaypoint', 'type': 'object'}, 'Point': {'description': 'Point Model', 'properties': {'coordinates': {'anyOf': [{'items': [{'anyOf': [{'type': 'number'}, {'type': 'integer'}]}, {'anyOf': [{'type': 'number'}, {'type': 'integer'}]}], 'maxItems': 2, 'minItems': 2, 'type': 'array'}, {'items': [{'anyOf': [{'type': 'number'}, {'type': 'integer'}]}, {'anyOf': [{'type': 'number'}, {'type': 'integer'}]}, {'anyOf': [{'type': 'number'}, {'type': 'integer'}]}], 'maxItems': 3, 'minItems': 3, 'type': 'array'}], 'title': 'Coordinates'}, 'type': {'const': 'Point', 'title': 'Type', 'type': 'string'}}, 'required': ['coordinates'], 'title': 'Point', 'type': 'object'}, 'RoutePath': {'properties': {'route': {'$ref': '#/definitions/ObjectReference'}, 'track_sections': {'items': {'$ref': '#/definitions/DirectionalTrackRange'}, 'title': 'Track Sections', 'type': 'array'}}, 'required': ['route', 'track_sections'], 'title': 'RoutePath', 'type': 'object'}}, 'properties': {'path_waypoints': {'items': {'$ref': '#/definitions/PathWaypoint'}, 'title': 'Path Waypoints', 'type': 'array'}, 'route_paths': {'items': {'$ref': '#/definitions/RoutePath'}, 'title': 'Route Paths', 'type': 'array'}}, 'required': ['route_paths', 'path_waypoints'], 'title': 'PathPayload', 'type': 'object'})]),
        ),
        migrations.RemoveField(
            model_name='trainschedule',
            name='labels',
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='labels',
            field=models.JSONField(default=[], validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'items': {'maxLength': 128, 'type': 'string'}, 'title': 'TrainScheduleLabels', 'type': 'array'})]),
        ),
        migrations.AlterField(
            model_name='trainschedule',
            name='margins',
            field=models.JSONField(default=[], validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'items': {'additionalProperties': False, 'properties': {'begin_position': {'type': 'number'}, 'end_position': {'type': 'number'}, 'type': {'enum': ['construction', 'ratio_time', 'ratio_distance']}, 'value': {'type': 'number'}}, 'required': ['type', 'value'], 'type': 'object'}, 'type': 'array'})]),
        ),
        migrations.DeleteModel(
            name='TrainScheduleLabel',
        ),
    ]
