# Generated by Django 3.2.9 on 2022-04-19 09:56

from django.db import migrations, models

import osrd_infra.utils


def apply_migration(apps, schema_editor):
    """Update infra from v2.2.0 to v2.2.1"""
    Infra = apps.get_model("osrd_infra", "Infra")
    updated_infra = []

    for infra in Infra.objects.all():
        if infra.railjson_version == "2.2.0":
            infra.railjson_version = "2.2.1"
            infra.version = str(int(infra.version) + 1)
            updated_infra.append(infra)
    Infra.objects.bulk_update(updated_infra, ["railjson_version", "version"])


def revert_migration(apps, schema_editor):
    """Revert infra from v2.2.1 to v2.2.0"""
    Infra = apps.get_model("osrd_infra", "Infra")
    updated_infra = []

    for infra in Infra.objects.all():
        if infra.railjson_version == "2.2.1":
            infra.railjson_version = "2.2.0"
            infra.version = str(int(infra.version) + 1)
            updated_infra.append(infra)
    Infra.objects.bulk_update(updated_infra, ["railjson_version", "version"])


class Migration(migrations.Migration):
    dependencies = [
        ("osrd_infra", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infra",
            name="railjson_version",
            field=models.CharField(default="2.2.1", editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name="signalmodel",
            name="data",
            field=models.JSONField(
                validators=[
                    osrd_infra.utils.JSONSchemaValidator(
                        limit_value={
                            "definitions": {
                                "Direction": {
                                    "description": "An enumeration.",
                                    "enum": ["START_TO_STOP", "STOP_TO_START"],
                                    "title": "Direction",
                                    "type": "string",
                                },
                                "ObjectReference": {
                                    "properties": {
                                        "id": {"maxLength": 255, "title": "Id", "type": "string"},
                                        "type": {"title": "Type", "type": "string"},
                                    },
                                    "required": ["id", "type"],
                                    "title": "ObjectReference",
                                    "type": "object",
                                },
                                "Side": {
                                    "description": "An enumeration.",
                                    "enum": ["LEFT", "RIGHT", "CENTER"],
                                    "title": "Side",
                                    "type": "string",
                                },
                            },
                            "properties": {
                                "angle_geo": {
                                    "default": 0,
                                    "description": "Geographic angle in degrees",
                                    "title": "Angle Geo",
                                    "type": "number",
                                },
                                "angle_sch": {
                                    "default": 0,
                                    "description": "Schematic angle in degrees",
                                    "title": "Angle Sch",
                                    "type": "number",
                                },
                                "aspects": {"items": {"type": "string"}, "title": "Aspects", "type": "array"},
                                "comment": {"title": "Comment", "type": "string"},
                                "direction": {"$ref": "#/definitions/Direction"},
                                "id": {"maxLength": 255, "title": "Id", "type": "string"},
                                "installation_type": {"title": "Installation Type", "type": "string"},
                                "is_in_service": {"title": "Is In Service", "type": "boolean"},
                                "is_lightable": {"title": "Is Lightable", "type": "boolean"},
                                "is_operational": {"title": "Is Operational", "type": "boolean"},
                                "label": {"title": "Label", "type": "string"},
                                "linked_detector": {"$ref": "#/definitions/ObjectReference"},
                                "physical_organization_group": {
                                    "title": "Physical Organization Group",
                                    "type": "string",
                                },
                                "position": {"title": "Position", "type": "number"},
                                "responsible_group": {"title": "Responsible Group", "type": "string"},
                                "side": {
                                    "allOf": [{"$ref": "#/definitions/Side"}],
                                    "default": "CENTER",
                                    "description": "Side of the signal on the track",
                                },
                                "sight_distance": {"title": "Sight Distance", "type": "number"},
                                "support_type": {"title": "Support Type", "type": "string"},
                                "track": {"$ref": "#/definitions/ObjectReference"},
                                "type_code": {"title": "Type Code", "type": "string"},
                                "value": {"title": "Value", "type": "string"},
                            },
                            "required": ["track", "position", "id", "direction", "sight_distance"],
                            "title": "Signal",
                            "type": "object",
                        }
                    )
                ]
            ),
        ),
        migrations.RunSQL(
            sql="""UPDATE osrd_infra_signalmodel as signal  SET data = JSONB_SET(data, '{side}', '\"CENTER\"') FROM
                osrd_infra_infra as infra WHERE infra.id = signal.infra_id AND infra.railjson_version = '2.2.0'""",
            reverse_sql="""UPDATE osrd_infra_signalmodel as signal  SET data = data - 'side' FROM osrd_infra_infra as
                infra WHERE infra.id = signal.infra_id AND infra.railjson_version = '2.2.1'""",
        ),
        migrations.RunSQL(
            sql="""UPDATE osrd_infra_signalmodel as signal  SET data = JSONB_SET(data, '{angle_sch}', '0') FROM
                osrd_infra_infra as infra WHERE infra.id = signal.infra_id AND infra.railjson_version = '2.2.0'
                AND signal.data->>'angle_sch' IS NULL""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""UPDATE osrd_infra_signalmodel as signal  SET data = JSONB_SET(data, '{angle_geo}', '0') FROM
                osrd_infra_infra as infra WHERE infra.id = signal.infra_id AND infra.railjson_version = '2.2.0'
                AND signal.data->>'angle_geo' IS NULL""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(code=apply_migration, reverse_code=revert_migration),
    ]
