# Generated by Django 4.1 on 2022-08-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainschedulemodel",
            name="speed_limit_category",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
