# Generated by Django 3.2.9 on 2022-01-20 16:02

from django.db import migrations, models
import django.db.models.deletion
import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=128)),
                ('departure_time', models.FloatField()),
                ('initial_speed', models.FloatField()),
                ('labels', models.JSONField(default=[], validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'items': {'maxLength': 128, 'type': 'string'}, 'title': 'TrainScheduleLabels', 'type': 'array'})])),
                ('allowances', models.JSONField(default=[], validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'definitions': {'Allowance': {'anyOf': [{'$ref': '#/definitions/ConstructionAllowance'}, {'$ref': '#/definitions/MarecoAllowance'}], 'discriminator': {'mapping': {'construction': '#/definitions/ConstructionAllowance', 'mareco': '#/definitions/MarecoAllowance'}, 'propertyName': 'allowance_type'}, 'title': 'Allowance'}, 'AllowancePercentValue': {'properties': {'percentage': {'title': 'Percentage', 'type': 'number'}, 'value_type': {'default': 'percentage', 'enum': ['percentage'], 'title': 'Value Type', 'type': 'string'}}, 'required': ['percentage'], 'title': 'AllowancePercentValue', 'type': 'object'}, 'AllowanceTimePerDistanceValue': {'properties': {'minutes': {'description': 'min/100km', 'title': 'Minutes', 'type': 'number'}, 'value_type': {'default': 'time_per_distance', 'enum': ['time_per_distance'], 'title': 'Value Type', 'type': 'string'}}, 'required': ['minutes'], 'title': 'AllowanceTimePerDistanceValue', 'type': 'object'}, 'AllowanceTimeValue': {'properties': {'seconds': {'title': 'Seconds', 'type': 'number'}, 'value_type': {'default': 'time', 'enum': ['time'], 'title': 'Value Type', 'type': 'string'}}, 'required': ['seconds'], 'title': 'AllowanceTimeValue', 'type': 'object'}, 'AllowanceValue': {'anyOf': [{'$ref': '#/definitions/AllowanceTimeValue'}, {'$ref': '#/definitions/AllowancePercentValue'}, {'$ref': '#/definitions/AllowanceTimePerDistanceValue'}], 'discriminator': {'mapping': {'percentage': '#/definitions/AllowancePercentValue', 'time': '#/definitions/AllowanceTimeValue', 'time_per_distance': '#/definitions/AllowanceTimePerDistanceValue'}, 'propertyName': 'value_type'}, 'title': 'AllowanceValue'}, 'ConstructionAllowance': {'properties': {'allowance_type': {'default': 'construction', 'enum': ['construction'], 'title': 'Allowance Type', 'type': 'string'}, 'begin_position': {'title': 'Begin Position', 'type': 'number'}, 'end_position': {'title': 'End Position', 'type': 'number'}, 'value': {'$ref': '#/definitions/AllowanceValue'}}, 'required': ['begin_position', 'end_position', 'value'], 'title': 'ConstructionAllowance', 'type': 'object'}, 'MarecoAllowance': {'properties': {'allowance_type': {'default': 'mareco', 'enum': ['mareco'], 'title': 'Allowance Type', 'type': 'string'}, 'default_value': {'$ref': '#/definitions/AllowanceValue'}, 'ranges': {'items': {'$ref': '#/definitions/RangeAllowance'}, 'title': 'Ranges', 'type': 'array'}}, 'required': ['default_value', 'ranges'], 'title': 'MarecoAllowance', 'type': 'object'}, 'RangeAllowance': {'properties': {'begin_position': {'title': 'Begin Position', 'type': 'number'}, 'end_position': {'title': 'End Position', 'type': 'number'}, 'value': {'$ref': '#/definitions/AllowanceValue'}}, 'required': ['begin_position', 'end_position', 'value'], 'title': 'RangeAllowance', 'type': 'object'}}, 'items': {'$ref': '#/definitions/Allowance'}, 'title': 'Allowances', 'type': 'array'})])),
                ('base_simulation', models.JSONField()),
                ('eco_simulation', models.JSONField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainschedule',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='trainschedule',
            name='path',
        ),
        migrations.RemoveField(
            model_name='trainschedule',
            name='rolling_stock',
        ),
        migrations.RemoveField(
            model_name='trainschedule',
            name='timetable',
        ),
        migrations.AlterField(
            model_name='pathmodel',
            name='payload',
            field=models.JSONField(validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'definitions': {'Direction': {'description': 'An enumeration.', 'enum': ['START_TO_STOP', 'STOP_TO_START'], 'title': 'Direction', 'type': 'string'}, 'DirectionalTrackRange': {'properties': {'begin': {'title': 'Begin', 'type': 'number'}, 'direction': {'$ref': '#/definitions/Direction'}, 'end': {'title': 'End', 'type': 'number'}, 'track': {'$ref': '#/definitions/ObjectReference'}}, 'required': ['track', 'begin', 'end', 'direction'], 'title': 'DirectionalTrackRange', 'type': 'object'}, 'ObjectReference': {'properties': {'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'type': {'title': 'Type', 'type': 'string'}}, 'required': ['id', 'type'], 'title': 'ObjectReference', 'type': 'object'}, 'PathWaypoint': {'properties': {'duration': {'title': 'Duration', 'type': 'number'}, 'geo': {'$ref': '#/definitions/Point'}, 'name': {'title': 'Name', 'type': 'string'}, 'position': {'title': 'Position', 'type': 'number'}, 'sch': {'$ref': '#/definitions/Point'}, 'suggestion': {'title': 'Suggestion', 'type': 'boolean'}, 'track': {'$ref': '#/definitions/ObjectReference'}}, 'required': ['track', 'position', 'geo', 'sch', 'suggestion', 'duration'], 'title': 'PathWaypoint', 'type': 'object'}, 'Point': {'description': 'Point Model', 'properties': {'coordinates': {'anyOf': [{'items': [{'anyOf': [{'type': 'number'}, {'type': 'integer'}]}, {'anyOf': [{'type': 'number'}, {'type': 'integer'}]}], 'maxItems': 2, 'minItems': 2, 'type': 'array'}, {'items': [{'anyOf': [{'type': 'number'}, {'type': 'integer'}]}, {'anyOf': [{'type': 'number'}, {'type': 'integer'}]}, {'anyOf': [{'type': 'number'}, {'type': 'integer'}]}], 'maxItems': 3, 'minItems': 3, 'type': 'array'}], 'title': 'Coordinates'}, 'type': {'const': 'Point', 'title': 'Type', 'type': 'string'}}, 'required': ['coordinates'], 'title': 'Point', 'type': 'object'}, 'RoutePath': {'properties': {'route': {'$ref': '#/definitions/ObjectReference'}, 'track_sections': {'items': {'$ref': '#/definitions/DirectionalTrackRange'}, 'title': 'Track Sections', 'type': 'array'}}, 'required': ['route', 'track_sections'], 'title': 'RoutePath', 'type': 'object'}}, 'properties': {'path_waypoints': {'items': {'$ref': '#/definitions/PathWaypoint'}, 'title': 'Path Waypoints', 'type': 'array'}, 'route_paths': {'items': {'$ref': '#/definitions/RoutePath'}, 'title': 'Route Paths', 'type': 'array'}}, 'required': ['route_paths', 'path_waypoints'], 'title': 'PathPayload', 'type': 'object'})]),
        ),
        migrations.DeleteModel(
            name='Simulation',
        ),
        migrations.DeleteModel(
            name='TrainSchedule',
        ),
        migrations.DeleteModel(
            name='TrainScheduleLabel',
        ),
        migrations.AddField(
            model_name='trainschedulemodel',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.pathmodel'),
        ),
        migrations.AddField(
            model_name='trainschedulemodel',
            name='rolling_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.rollingstock'),
        ),
        migrations.AddField(
            model_name='trainschedulemodel',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_schedules', to='osrd_infra.timetable'),
        ),
    ]
