# Generated by Django 3.2.9 on 2022-03-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infra',
            name='generated_version',
            field=models.CharField(default='0', editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='infra',
            name='version',
            field=models.CharField(default='1', editable=False, max_length=40),
        ),
        migrations.DeleteModel(
            name='GeneratedInfra',
        ),
    ]
