# Generated by Django 3.2.9 on 2022-04-22 15:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0002_railjson_v2_2_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackSectionLinkLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.CharField(max_length=255)),
                ('geographic', django.contrib.gis.db.models.fields.PointField(srid=3857)),
                ('schematic', django.contrib.gis.db.models.fields.PointField(srid=3857)),
            ],
            options={
                'verbose_name_plural': 'generated track section links layer',
            },
        ),
        migrations.RunSQL(
            """ALTER TABLE osrd_infra_tracksectionlinklayer
                ADD infra_id INTEGER,
                ADD CONSTRAINT osrd_infra_tracksectionlinklayer_fkey FOREIGN KEY (infra_id) REFERENCES osrd_infra_infra(id) ON DELETE CASCADE
            """,
            state_operations=[
                migrations.AddField(
                    model_name="tracksectionlinklayer",
                    name="infra",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="osrd_infra.infra",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
                name="tracksectionlinklayer",
                unique_together={('infra', 'obj_id')},
            )
    ]
