# Generated by Django 4.1.5 on 2023-01-25 15:59

import django.db.models.deletion
from django.db import migrations, models

from osrd_infra.migrations import run_sql_complex_add_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0002_add_electrical_profiles_to_schedules"),
    ]

    operations = [
        migrations.CreateModel(
            name="RollingStockCompoundImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.BinaryField()),
            ],
            options={
                "verbose_name_plural": "rolling stock compound images",
                "db_table": "osrd_infra_rollingstockimage",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RollingStockLivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="default", help_text="Name of the livery", max_length=255)),
            ],
            options={
                "verbose_name_plural": "rolling stocks liveries",
            },
        ),
        migrations.CreateModel(
            name="RollingStockSeparatedImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.BinaryField()),
                ("order", models.IntegerField(default=0, help_text="Position of this image in its livery")),
            ],
            options={
                "verbose_name_plural": "rolling stock separated images",
                "db_table": "osrd_infra_rollingstockimage",
            },
        ),
    ]

    # rolling_stock_images: set order default to 0
    operations.append(
        migrations.RunSQL(
            sql=[
                (
                    f"""ALTER TABLE osrd_infra_rollingstockimage
                    ALTER COLUMN "order" SET DEFAULT 0;
                """
                )
            ],
            reverse_sql=[
                (
                    f"""ALTER TABLE osrd_infra_rollingstockimage
                    ALTER COLUMN "order" DROP DEFAULT;
                """
                )
            ],
        ),
    )

    # compound_image: OneToOne in RollingStockLivery with RollingStockImage
    operations.append(
        migrations.RunSQL(
            sql=[
                (
                    f"""ALTER TABLE osrd_infra_rollingstocklivery
                ADD compound_image_id INTEGER,
                ADD CONSTRAINT osrd_rollingstockcompoundimage_rollingstocklivery_fkey FOREIGN KEY (compound_image_id)
                   REFERENCES osrd_infra_rollingstockimage(id) ON DELETE CASCADE
            """
                )
            ],
            reverse_sql=[
                (
                    f"""ALTER TABLE osrd_infra_rollingstocklivery
                DROP CONSTRAINT osrd_rollingstockcompoundimage_rollingstocklivery_fkey,
                DROP COLUMN compound_image_id
            """
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="RollingStockLivery",
                    name="compound_image",
                    field=models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=f"osrd_infra.RollingStockCompoundImage",
                    ),
                ),
            ],
        )
    )

    # OneToMany in RollingStockLivery with RollingStock
    operations.append(
        migrations.RunSQL(
            sql=[
                (
                    f"""ALTER TABLE osrd_infra_rollingstocklivery
                ADD rolling_stock_id INTEGER,
                ADD CONSTRAINT osrd_rollingstock_rollingstocklivery_fkey FOREIGN KEY (rolling_stock_id)
                   REFERENCES osrd_infra_rollingstock(id) ON DELETE CASCADE
            """
                )
            ],
            reverse_sql=[
                (
                    f"""ALTER TABLE osrd_infra_rollingstocklivery
                DROP CONSTRAINT osrd_rollingstock_rollingstocklivery_fkey,
                DROP COLUMN rolling_stock_id
            """
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="rollingstocklivery",
                    name="rolling_stock",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=f"osrd_infra.rollingstock",
                        related_name="liveries",
                    ),
                ),
            ],
        )
    )

    # OneToMany in RollingStockImage with RollingStockLivery
    operations.append(
        run_sql_complex_add_foreign_key(
            table_name="rollingstockimage",
            field_name="livery",
            model_name="rollingstockseparatedimage",
            link_table="rollingstocklivery",
            link_model="rollingstocklivery",
        )
    )

    # add unique together constraint in RollingStockLivery (rollingStock and name)
    operations.append(
        migrations.AlterUniqueTogether(
            name="rollingstocklivery",
            unique_together={("rolling_stock", "name")},
        )
    )

    # add unique together constraint in RollingStockImage (livery and order)
    operations.append(
        migrations.AlterUniqueTogether(
            name="rollingstockseparatedimage",
            unique_together={("livery", "order")},
        )
    )
