# Generated by Django 3.2.5 on 2021-09-14 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0002_trainschedule_simulation_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedsectionpartcomponent',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speed_section_part', to='osrd_infra.entity'),
        ),
    ]
