# Generated by Django 4.1 on 2022-09-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0002_add_train_speed_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="infra",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
