# Generated by Django 4.1 on 2022-09-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0003_infra_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainschedulemodel",
            name="speed_limit_category",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
