# Generated by Django 4.1.5 on 2023-01-31 13:00

import osrd_schemas.train_schedule
from django.db import migrations, models

import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0003_rollingstockimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainschedulemodel",
            name="options",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[osrd_infra.utils.PydanticValidator(osrd_schemas.train_schedule.TrainScheduleOptions)],
            ),
        ),
    ]
