# Generated by Django 4.1 on 2022-09-20 14:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0004_make_speed_category_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollingstock",
            name="compatible_voltages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=[],
                help_text="A list of compatible voltage (in V)",
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rollingstock",
            name="electric_only",
            field=models.BooleanField(
                default=False, help_text="If true, the train can only use tracks with compatible catenaries"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rollingstock",
            name="version",
            field=models.CharField(default="2.2", editable=False, max_length=16),
        ),
    ]
