# Generated by Django 3.2.5 on 2021-09-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0004_tracksectionsignalingtypecomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackSectionElectrificationTypeComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('electrification_type', models.IntegerField()),
                ('start_offset', models.FloatField()),
                ('end_offset', models.FloatField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrification_type_set', to='osrd_infra.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
