# Generated by Django 4.0.7 on 2022-10-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0005_rollingstock_add_electrification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlayer',
            name='obj_id',
        ),
        migrations.RemoveField(
            model_name='errorlayer',
            name='obj_type',
        ),
        migrations.AlterField(
            model_name='infra',
            name='railjson_version',
            field=models.CharField(default='3.0.0', editable=False, max_length=16),
        ),
    ]
