# Generated by Django 3.2.9 on 2022-03-04 08:55

from django.db import migrations, models
import django.db.models.deletion
import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0005_rm_tvd_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatenaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.CharField(max_length=255)),
                ('data', models.JSONField(validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'definitions': {'ApplicableDirections': {'description': 'An enumeration.', 'enum': ['START_TO_STOP', 'STOP_TO_START', 'BOTH'], 'title': 'ApplicableDirections', 'type': 'string'}, 'ApplicableDirectionsTrackRange': {'properties': {'applicable_directions': {'$ref': '#/definitions/ApplicableDirections'}, 'begin': {'title': 'Begin', 'type': 'number'}, 'end': {'title': 'End', 'type': 'number'}, 'track': {'$ref': '#/definitions/ObjectReference'}}, 'required': ['track', 'begin', 'end', 'applicable_directions'], 'title': 'ApplicableDirectionsTrackRange', 'type': 'object'}, 'ObjectReference': {'properties': {'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'type': {'title': 'Type', 'type': 'string'}}, 'required': ['id', 'type'], 'title': 'ObjectReference', 'type': 'object'}}, 'properties': {'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'track_ranges': {'items': {'$ref': '#/definitions/ApplicableDirectionsTrackRange'}, 'title': 'Track Ranges', 'type': 'array'}, 'voltage': {'title': 'Voltage', 'type': 'number'}}, 'required': ['id', 'voltage', 'track_ranges'], 'title': 'Catenary', 'type': 'object'})])),
            ],
            options={
                'verbose_name_plural': 'catenaries',
            },
        ),
        migrations.CreateModel(
            name='SpeedSectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.CharField(max_length=255)),
                ('data', models.JSONField(validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'definitions': {'ApplicableDirections': {'description': 'An enumeration.', 'enum': ['START_TO_STOP', 'STOP_TO_START', 'BOTH'], 'title': 'ApplicableDirections', 'type': 'string'}, 'ApplicableDirectionsTrackRange': {'properties': {'applicable_directions': {'$ref': '#/definitions/ApplicableDirections'}, 'begin': {'title': 'Begin', 'type': 'number'}, 'end': {'title': 'End', 'type': 'number'}, 'track': {'$ref': '#/definitions/ObjectReference'}}, 'required': ['track', 'begin', 'end', 'applicable_directions'], 'title': 'ApplicableDirectionsTrackRange', 'type': 'object'}, 'ObjectReference': {'properties': {'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'type': {'title': 'Type', 'type': 'string'}}, 'required': ['id', 'type'], 'title': 'ObjectReference', 'type': 'object'}}, 'properties': {'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'speed': {'title': 'Speed', 'type': 'number'}, 'track_ranges': {'items': {'$ref': '#/definitions/ApplicableDirectionsTrackRange'}, 'title': 'Track Ranges', 'type': 'array'}}, 'required': ['id', 'speed', 'track_ranges'], 'title': 'SpeedSection', 'type': 'object'})])),
            ],
            options={
                'verbose_name_plural': 'speed sections',
            },
        ),
        migrations.RemoveField(
            model_name='railscriptfunctionmodel',
            name='infra',
        ),
        migrations.AddField(
            model_name='infra',
            name='railjson_version',
            field=models.CharField(default='2.1.0', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infra',
            name='railjson_version',
            field=models.CharField(default='2.2.0', max_length=16),
        ),
        migrations.AlterField(
            model_name='bufferstopmodel',
            name='data',
            field=models.JSONField(validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'definitions': {'ApplicableDirections': {'description': 'An enumeration.', 'enum': ['START_TO_STOP', 'STOP_TO_START', 'BOTH'], 'title': 'ApplicableDirections', 'type': 'string'}, 'ObjectReference': {'properties': {'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'type': {'title': 'Type', 'type': 'string'}}, 'required': ['id', 'type'], 'title': 'ObjectReference', 'type': 'object'}}, 'properties': {'applicable_directions': {'$ref': '#/definitions/ApplicableDirections'}, 'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'position': {'title': 'Position', 'type': 'number'}, 'track': {'$ref': '#/definitions/ObjectReference'}}, 'required': ['track', 'position', 'id', 'applicable_directions'], 'title': 'BufferStop', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='detectormodel',
            name='data',
            field=models.JSONField(validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'definitions': {'ApplicableDirections': {'description': 'An enumeration.', 'enum': ['START_TO_STOP', 'STOP_TO_START', 'BOTH'], 'title': 'ApplicableDirections', 'type': 'string'}, 'ObjectReference': {'properties': {'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'type': {'title': 'Type', 'type': 'string'}}, 'required': ['id', 'type'], 'title': 'ObjectReference', 'type': 'object'}}, 'properties': {'applicable_directions': {'$ref': '#/definitions/ApplicableDirections'}, 'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'position': {'title': 'Position', 'type': 'number'}, 'track': {'$ref': '#/definitions/ObjectReference'}}, 'required': ['track', 'position', 'id', 'applicable_directions'], 'title': 'Detector', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='operationalpointmodel',
            name='data',
            field=models.JSONField(validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'definitions': {'ObjectReference': {'properties': {'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'type': {'title': 'Type', 'type': 'string'}}, 'required': ['id', 'type'], 'title': 'ObjectReference', 'type': 'object'}, 'OperationalPointPart': {'properties': {'position': {'title': 'Position', 'type': 'number'}, 'track': {'$ref': '#/definitions/ObjectReference'}}, 'required': ['track', 'position'], 'title': 'OperationalPointPart', 'type': 'object'}}, 'properties': {'ch': {'maxLength': 2, 'title': 'Ch', 'type': 'string'}, 'ch_long_label': {'maxLength': 255, 'title': 'Ch Long Label', 'type': 'string'}, 'ch_short_label': {'maxLength': 255, 'title': 'Ch Short Label', 'type': 'string'}, 'ci': {'title': 'Ci', 'type': 'integer'}, 'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'name': {'maxLength': 255, 'title': 'Name', 'type': 'string'}, 'parts': {'items': {'$ref': '#/definitions/OperationalPointPart'}, 'title': 'Parts', 'type': 'array'}}, 'required': ['id', 'parts', 'ci', 'ch', 'name'], 'title': 'OperationalPoint', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='data',
            field=models.JSONField(validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'definitions': {'Direction': {'description': 'An enumeration.', 'enum': ['START_TO_STOP', 'STOP_TO_START'], 'title': 'Direction', 'type': 'string'}, 'DirectionalTrackRange': {'properties': {'begin': {'title': 'Begin', 'type': 'number'}, 'direction': {'$ref': '#/definitions/Direction'}, 'end': {'title': 'End', 'type': 'number'}, 'track': {'$ref': '#/definitions/ObjectReference'}}, 'required': ['track', 'begin', 'end', 'direction'], 'title': 'DirectionalTrackRange', 'type': 'object'}, 'ObjectReference': {'properties': {'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'type': {'title': 'Type', 'type': 'string'}}, 'required': ['id', 'type'], 'title': 'ObjectReference', 'type': 'object'}}, 'properties': {'entry_point': {'$ref': '#/definitions/ObjectReference'}, 'exit_point': {'$ref': '#/definitions/ObjectReference'}, 'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'path': {'items': {'$ref': '#/definitions/DirectionalTrackRange'}, 'title': 'Path', 'type': 'array'}, 'release_detectors': {'items': {'$ref': '#/definitions/ObjectReference'}, 'title': 'Release Detectors', 'type': 'array'}}, 'required': ['id', 'entry_point', 'exit_point', 'release_detectors', 'path'], 'title': 'Route', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='signalmodel',
            name='data',
            field=models.JSONField(validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'definitions': {'Direction': {'description': 'An enumeration.', 'enum': ['START_TO_STOP', 'STOP_TO_START'], 'title': 'Direction', 'type': 'string'}, 'ObjectReference': {'properties': {'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'type': {'title': 'Type', 'type': 'string'}}, 'required': ['id', 'type'], 'title': 'ObjectReference', 'type': 'object'}}, 'properties': {'angle_geo': {'title': 'Angle Geo', 'type': 'number'}, 'angle_sch': {'title': 'Angle Sch', 'type': 'number'}, 'aspects': {'items': {'type': 'string'}, 'title': 'Aspects', 'type': 'array'}, 'comment': {'title': 'Comment', 'type': 'string'}, 'direction': {'$ref': '#/definitions/Direction'}, 'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'is_in_service': {'title': 'Is In Service', 'type': 'boolean'}, 'is_lightable': {'title': 'Is Lightable', 'type': 'boolean'}, 'is_operational': {'title': 'Is Operational', 'type': 'boolean'}, 'linked_detector': {'$ref': '#/definitions/ObjectReference'}, 'physical_organization_group': {'title': 'Physical Organization Group', 'type': 'string'}, 'position': {'title': 'Position', 'type': 'number'}, 'responsible_group': {'title': 'Responsible Group', 'type': 'string'}, 'sight_distance': {'title': 'Sight Distance', 'type': 'number'}, 'support_type': {'title': 'Support Type', 'type': 'string'}, 'track': {'$ref': '#/definitions/ObjectReference'}, 'type_code': {'title': 'Type Code', 'type': 'string'}}, 'required': ['track', 'position', 'id', 'direction', 'sight_distance'], 'title': 'Signal', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='switchmodel',
            name='data',
            field=models.JSONField(validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'definitions': {'Endpoint': {'description': 'An enumeration.', 'enum': ['BEGIN', 'END'], 'title': 'Endpoint', 'type': 'string'}, 'ObjectReference': {'properties': {'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'type': {'title': 'Type', 'type': 'string'}}, 'required': ['id', 'type'], 'title': 'ObjectReference', 'type': 'object'}, 'TrackEndpoint': {'properties': {'endpoint': {'$ref': '#/definitions/Endpoint'}, 'track': {'$ref': '#/definitions/ObjectReference'}}, 'required': ['endpoint', 'track'], 'title': 'TrackEndpoint', 'type': 'object'}}, 'properties': {'group_change_delay': {'title': 'Group Change Delay', 'type': 'number'}, 'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'ports': {'additionalProperties': {'$ref': '#/definitions/TrackEndpoint'}, 'title': 'Ports', 'type': 'object'}, 'switch_type': {'$ref': '#/definitions/ObjectReference'}}, 'required': ['id', 'switch_type', 'group_change_delay', 'ports'], 'title': 'Switch', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='tracksectionmodel',
            name='data',
            field=models.JSONField(validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'definitions': {'ApplicableDirections': {'description': 'An enumeration.', 'enum': ['START_TO_STOP', 'STOP_TO_START', 'BOTH'], 'title': 'ApplicableDirections', 'type': 'string'}, 'Curve': {'properties': {'begin': {'title': 'Begin', 'type': 'number'}, 'end': {'title': 'End', 'type': 'number'}, 'radius': {'title': 'Radius', 'type': 'number'}}, 'required': ['radius', 'begin', 'end'], 'title': 'Curve', 'type': 'object'}, 'LineString': {'description': 'LineString Model', 'properties': {'coordinates': {'items': {'anyOf': [{'items': [{'anyOf': [{'type': 'number'}, {'type': 'integer'}]}, {'anyOf': [{'type': 'number'}, {'type': 'integer'}]}], 'maxItems': 2, 'minItems': 2, 'type': 'array'}, {'items': [{'anyOf': [{'type': 'number'}, {'type': 'integer'}]}, {'anyOf': [{'type': 'number'}, {'type': 'integer'}]}, {'anyOf': [{'type': 'number'}, {'type': 'integer'}]}], 'maxItems': 3, 'minItems': 3, 'type': 'array'}]}, 'minItems': 2, 'title': 'Coordinates', 'type': 'array'}, 'type': {'const': 'LineString', 'title': 'Type', 'type': 'string'}}, 'required': ['coordinates'], 'title': 'LineString', 'type': 'object'}, 'Slope': {'properties': {'begin': {'title': 'Begin', 'type': 'number'}, 'end': {'title': 'End', 'type': 'number'}, 'gradient': {'title': 'Gradient', 'type': 'number'}}, 'required': ['gradient', 'begin', 'end'], 'title': 'Slope', 'type': 'object'}}, 'properties': {'curves': {'items': {'$ref': '#/definitions/Curve'}, 'title': 'Curves', 'type': 'array'}, 'geo': {'$ref': '#/definitions/LineString'}, 'id': {'maxLength': 255, 'title': 'Id', 'type': 'string'}, 'length': {'title': 'Length', 'type': 'number'}, 'line_code': {'title': 'Line Code', 'type': 'integer'}, 'line_name': {'maxLength': 255, 'title': 'Line Name', 'type': 'string'}, 'navigability': {'$ref': '#/definitions/ApplicableDirections'}, 'sch': {'$ref': '#/definitions/LineString'}, 'slopes': {'items': {'$ref': '#/definitions/Slope'}, 'title': 'Slopes', 'type': 'array'}, 'track_name': {'maxLength': 255, 'title': 'Track Name', 'type': 'string'}, 'track_number': {'title': 'Track Number', 'type': 'integer'}}, 'required': ['geo', 'sch', 'id', 'length', 'line_code', 'line_name', 'track_number', 'track_name', 'navigability', 'slopes', 'curves'], 'title': 'TrackSection', 'type': 'object'})]),
        ),
        migrations.DeleteModel(
            name='AspectModel',
        ),
        migrations.DeleteModel(
            name='RailScriptFunctionModel',
        ),
        migrations.AddField(
            model_name='speedsectionmodel',
            name='infra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.infra'),
        ),
        migrations.AddField(
            model_name='catenarymodel',
            name='infra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.infra'),
        ),
        migrations.AlterUniqueTogether(
            name='speedsectionmodel',
            unique_together={('infra', 'obj_id')},
        ),
        migrations.AlterUniqueTogether(
            name='catenarymodel',
            unique_together={('infra', 'obj_id')},
        ),
    ]
