# Generated by Django 3.2.9 on 2022-03-04 10:52

from django.db import migrations, models
import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0006_rm_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathmodel',
            name='vmax',
        ),
        migrations.AddField(
            model_name='trainschedulemodel',
            name='mrsp',
            field=models.JSONField(default=[], validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'definitions': {'MRSPPoint': {'properties': {'position': {'title': 'Position', 'type': 'number'}, 'speed': {'title': 'Speed', 'type': 'number'}}, 'required': ['position', 'speed'], 'title': 'MRSPPoint', 'type': 'object'}}, 'items': {'$ref': '#/definitions/MRSPPoint'}, 'title': 'MRPS', 'type': 'array'})]),
            preserve_default=False,
        ),
    ]
