# Generated by Django 4.0.8 on 2022-10-26 09:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models

import osrd_infra.schemas.infra
import osrd_infra.utils
from osrd_infra.migrations import run_sql_add_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0006_railjson_v3"),
    ]

    operations = [
        migrations.CreateModel(
            name="LPVPanelLayer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("geographic", django.contrib.gis.db.models.fields.PointField(srid=3857)),
                ("schematic", django.contrib.gis.db.models.fields.PointField(srid=3857)),
                (
                    "data",
                    models.JSONField(validators=[osrd_infra.utils.PydanticValidator(osrd_infra.schemas.infra.Panel)]),
                ),
            ],
        ),
        run_sql_add_foreign_key("lpvpanellayer", "infra", "infra"),
        run_sql_add_foreign_key("lpvpanellayer", "obj", "speedsectionmodel"),
    ]
