# Generated by Django 4.1.5 on 2023-02-10 14:33

from django.db import migrations, models
import django.db.models.deletion

from osrd_infra.migrations import run_sql_add_foreign_key


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0006_operationalstudy_project_remove_timetable_infra_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="electricalprofileset",
            options={"base_manager_name": "objects", "verbose_name_plural": "Electrical profile sets"},
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="electrical_profile_set",
        ),
        run_sql_add_foreign_key("scenario", "electrical_profile_set", "electricalprofileset", nullable=True),
    ]
