# Generated by Django 4.1.2 on 2022-10-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0007_lpvpanellayer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainschedulemodel",
            name="speed_limit_category",
        ),
        migrations.AddField(
            model_name="trainschedulemodel",
            name="speed_limit_composition",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
