# Generated by Django 4.1.5 on 2023-02-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0008_move_electrical_profile_set"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION TileBBox (z int, x int, y int, srid int = 3857)
                RETURNS geometry
                LANGUAGE plpgsql 
                IMMUTABLE AS
            $FUNC$
            DECLARE
                max numeric := 20037508.34;
                res numeric := (max*2)/(2^z);
                bbox geometry;
            BEGIN
                bbox := ST_MakeEnvelope(
                    -max + (x * res),
                    max - (y * res),
                    -max + (x * res) + res,
                    max - (y * res) - res,
                    3857
                );
                IF srid = 3857 then
                    return bbox;
                ELSE
                    return ST_Transform(bbox, srid);
                END IF;
            END;
            $FUNC$
            """,
            reverse_sql="""
            DROP FUNCTION IF EXISTS TileBBox;
            """,
        )
    ]
