# Generated by Django 4.1.5 on 2023-02-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0009_tile_bbox"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainschedulemodel",
            old_name="speed_limit_composition",
            new_name="speed_limit_tags",
        ),
    ]
