# Generated by Django 3.2.7 on 2021-10-04 12:10

from django.db import migrations, models
import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0009_add_complex_switches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainschedule',
            old_name='simulation_log',
            new_name='base_simulation_log',
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='eco_simulation_log',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='margins',
            field=models.JSONField(null=True, validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'items': {'additionalProperties': False, 'properties': {'begin_position': {'type': 'number'}, 'end_position': {'type': 'number'}, 'type': {'enum': ['construction', 'ratio_time', 'ratio_distance']}, 'value': {'type': 'number'}}, 'required': ['type', 'value', 'begin_position', 'end_position'], 'type': 'object'}, 'type': 'array'})]),
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='margins_simulation_log',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='payload',
            field=models.JSONField(validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'path': {'items': {'additionalProperties': False, 'properties': {'route': {'type': 'number'}, 'track_sections': {'items': {'additionalProperties': False, 'properties': {'begin': {'type': 'number'}, 'end': {'type': 'number'}, 'track_section': {'type': 'number'}}, 'required': ['begin', 'end', 'track_section'], 'type': 'object'}, 'type': 'array'}}, 'required': ['route', 'track_sections'], 'type': 'object'}, 'type': 'array'}, 'steps': {'items': {'additionalProperties': False, 'properties': {'geographic': {'items': {'type': 'number'}, 'maxItems': 2, 'minItems': 2, 'type': 'array'}, 'name': {'type': 'string'}, 'position': {'additionalProperties': False, 'properties': {'offset': {'type': 'number'}, 'track_section': {'type': 'number'}}, 'required': ['offset', 'track_section'], 'type': 'object'}, 'schematic': {'items': {'type': 'number'}, 'maxItems': 2, 'minItems': 2, 'type': 'array'}, 'stop_time': {'type': 'number'}, 'suggestion': {'type': 'boolean'}}, 'required': ['name', 'position', 'suggestion', 'stop_time'], 'type': 'object'}, 'type': 'array'}}, 'required': ['path', 'steps'], 'type': 'object'})]),
        ),
    ]
