# Generated by Django 4.0.8 on 2022-11-24 09:32

from django.db import migrations, models
import osrd_infra.schemas.rolling_stock


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0009_rolling_stocks_v3_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainschedulemodel',
            name='comfort',
            field=models.CharField(choices=[('STANDARD', 'STANDARD'), ('AC', 'AC'), ('HEATING', 'HEATING')], default=osrd_infra.schemas.rolling_stock.ComfortType['STANDARD'], max_length=8),
        ),
    ]
