# Generated by Django 4.1.2 on 2022-12-21 18:09

from django.db import migrations, models
import osrd_infra.schemas.external_generated_inputs
import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0010_trainschedulemodel_comfort"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricalProfilesSet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                (
                    "data",
                    models.JSONField(
                        validators=[
                            osrd_infra.utils.PydanticValidator(
                                osrd_infra.schemas.external_generated_inputs.ElectricalProfilesList
                            )
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Electrical profiles sets",
            },
        ),
    ]
