# Generated by Django 4.1.7 on 2023-03-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0010_rename_speed_limit_composition_trainschedulemodel_speed_limit_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content_type", models.CharField(max_length=255)),
                ("data", models.BinaryField(editable=True)),
            ],
        ),
    ]
