# Generated by Django 4.1.2 on 2022-12-20 14:53

from django.db import migrations, models
import osrd_infra.schemas.physical_approximations
import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0010_trainschedulemodel_comfort"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricProfilesList",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "data",
                    models.JSONField(
                        validators=[
                            osrd_infra.utils.PydanticValidator(
                                osrd_infra.schemas.physical_approximations.ElectricProfilesList
                            )
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "electric profiles lists",
            },
        ),
    ]
