# Generated by Django 3.1.6 on 2021-11-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0010_margins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainschedule',
            name='margins_simulation_log',
        ),
    ]
