# Generated by Django 4.1.3 on 2022-12-22 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0011_electricalprofilesset"),
    ]

    operations = [
        migrations.AddField(
            model_name="infra",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infra",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
