# Generated by Django 3.2.9 on 2021-11-18 14:47

from django.db import migrations, models
import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0011_remove_trainschedule_margins_simulation_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainschedule',
            name='margins',
            field=models.JSONField(null=True, validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'items': {'additionalProperties': False, 'properties': {'begin_position': {'type': 'number'}, 'end_position': {'type': 'number'}, 'type': {'enum': ['construction', 'ratio_time', 'ratio_distance']}, 'value': {'type': 'number'}}, 'required': ['type', 'value'], 'type': 'object'}, 'type': 'array'})]),
        ),
    ]
