# Generated by Django 3.2.9 on 2021-11-23 15:14

from django.db import migrations, models
import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0012_alter_trainschedule_margins'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='vmax',
            field=models.JSONField(default=[], validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'items': {'additionalProperties': False, 'properties': {'position': {'type': 'number'}, 'speed': {'type': 'number'}}, 'required': ['position', 'speed'], 'type': 'object'}, 'minItems': 2, 'type': 'array'})]),
            preserve_default=False,
        ),
    ]
