# Generated by Django 4.1.3 on 2023-01-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0013_infra_created_infra_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollingstock",
            name="metadata",
            field=models.JSONField(
                default=dict,
                help_text="Dictionary of optional properties used in the frontend to display            the rolling stock: detail, number, reference, family, type, grouping,            series, subseries, unit",
            ),
        ),
    ]
