# Generated by Django 4.0.4 on 2022-05-19 13:57

from django.db import migrations, models

import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0013_operationalpointlayer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errorlayer",
            name="information",
            field=models.JSONField(
                validators=[
                    osrd_infra.utils.JSONSchemaValidator(
                        limit_value={
                            "anyOf": [
                                {"$ref": "#/definitions/InvalidReference"},
                                {"$ref": "#/definitions/OutOfRange"},
                                {"$ref": "#/definitions/ObjectOutsideOfPath"},
                                {"$ref": "#/definitions/EmptyObject"},
                            ],
                            "definitions": {
                                "EmptyObject": {
                                    "properties": {
                                        "error_type": {
                                            "default": "empty_object",
                                            "enum": ["empty_object"],
                                            "title": "Error Type",
                                            "type": "string",
                                        },
                                        "field": {"title": "Field", "type": "string"},
                                        "is_warning": {
                                            "default": True,
                                            "enum": [True],
                                            "title": "Is Warning",
                                            "type": "boolean",
                                        },
                                    },
                                    "required": ["field"],
                                    "title": "EmptyObject",
                                    "type": "object",
                                },
                                "InvalidReference": {
                                    "properties": {
                                        "error_type": {
                                            "default": "invalid_reference",
                                            "enum": ["invalid_reference"],
                                            "title": "Error Type",
                                            "type": "string",
                                        },
                                        "field": {"title": "Field", "type": "string"},
                                        "is_warning": {
                                            "default": False,
                                            "enum": [False],
                                            "title": "Is Warning",
                                            "type": "boolean",
                                        },
                                        "reference": {"$ref": "#/definitions/ObjectReference"},
                                    },
                                    "required": ["field", "reference"],
                                    "title": "InvalidReference",
                                    "type": "object",
                                },
                                "ObjectOutsideOfPath": {
                                    "properties": {
                                        "error_type": {
                                            "default": "object_outside_of_path",
                                            "enum": ["object_outside_of_path"],
                                            "title": "Error Type",
                                            "type": "string",
                                        },
                                        "field": {"title": "Field", "type": "string"},
                                        "is_warning": {
                                            "default": False,
                                            "enum": [False],
                                            "title": "Is Warning",
                                            "type": "boolean",
                                        },
                                        "position": {"title": "Position", "type": "number"},
                                        "track": {"title": "Track", "type": "string"},
                                    },
                                    "required": ["field", "position", "track"],
                                    "title": "ObjectOutsideOfPath",
                                    "type": "object",
                                },
                                "ObjectReference": {
                                    "properties": {
                                        "id": {"maxLength": 255, "title": "Id", "type": "string"},
                                        "type": {"title": "Type", "type": "string"},
                                    },
                                    "required": ["id", "type"],
                                    "title": "ObjectReference",
                                    "type": "object",
                                },
                                "OutOfRange": {
                                    "properties": {
                                        "error_type": {
                                            "default": "out_of_range",
                                            "enum": ["out_of_range"],
                                            "title": "Error Type",
                                            "type": "string",
                                        },
                                        "expected_range": {
                                            "items": [{"type": "number"}, {"type": "number"}],
                                            "maxItems": 2,
                                            "minItems": 2,
                                            "title": "Expected Range",
                                            "type": "array",
                                        },
                                        "field": {"title": "Field", "type": "string"},
                                        "is_warning": {
                                            "default": False,
                                            "enum": [False],
                                            "title": "Is Warning",
                                            "type": "boolean",
                                        },
                                        "position": {"title": "Position", "type": "number"},
                                    },
                                    "required": ["field", "position", "expected_range"],
                                    "title": "OutOfRange",
                                    "type": "object",
                                },
                            },
                            "discriminator": {
                                "mapping": {
                                    "empty_object": "#/definitions/EmptyObject",
                                    "invalid_reference": "#/definitions/InvalidReference",
                                    "object_outside_of_path": "#/definitions/ObjectOutsideOfPath",
                                    "out_of_range": "#/definitions/OutOfRange",
                                },
                                "propertyName": "error_type",
                            },
                            "title": "InfraError",
                        }
                    )
                ]
            ),
        ),
    ]
