# Generated by Django 4.1.4 on 2022-12-12 16:44

from django.db import migrations, models


def apply_migration(apps, schema_editor):
    """Update infra from v3.0.1 to v3.1.0"""
    Infra = apps.get_model("osrd_infra", "Infra")
    RouteModel = apps.get_model("osrd_infra", "RouteModel")
    updated_infra = []

    for infra in Infra.objects.all():
        if infra.railjson_version == "3.0.1":
            infra.railjson_version = "3.1.0"
            updated_infra.append(infra)
    Infra.objects.bulk_update(updated_infra, ["railjson_version"])
    RouteModel.objects.filter(infra__in=updated_infra).delete()


def revert_migration(apps, schema_editor):
    """Revert infra from v3.1.0 to v3.0.1"""
    Infra = apps.get_model("osrd_infra", "Infra")
    RouteModel = apps.get_model("osrd_infra", "RouteModel")
    updated_infra = []

    for infra in Infra.objects.all():
        if infra.railjson_version == "3.1.0":
            infra.railjson_version = "3.0.1"
            updated_infra.append(infra)
    Infra.objects.bulk_update(updated_infra, ["railjson_version"])
    RouteModel.objects.filter(infra__in=updated_infra).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0014_rollingstock_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infra",
            name="railjson_version",
            field=models.CharField(default="3.1.0", editable=False, max_length=16),
        ),
        migrations.DeleteModel(
            name="RouteLayer",
        ),
        migrations.RunPython(code=apply_migration, reverse_code=revert_migration),
    ]
