# Generated by Django 4.1.2 on 2023-01-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0015_railjson_v3_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollingstock",
            name="power_class",
            field=models.CharField(
                help_text="The power usage class of the train (optional because it is specific to SNCF)",
                max_length=255,
                null=True,
            ),
        ),
    ]
