# Generated by Django 4.1.3 on 2022-12-19 16:26

from django.db import migrations
from osrd_infra.migrations import run_sql_create_infra_search_table, SearchTableType


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0016_rollingstock_power_class"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION osrd_to_like_search(query text) RETURNS text
                LANGUAGE 'sql'
                IMMUTABLE PARALLEL SAFE 
            AS $BODY$
            SELECT '%' || replace(replace(replace(lower(coalesce(query, '')), '%', '\\%'), '_', '\\_'), '\\', '\\\\') || '%'
            $BODY$;
            CREATE OR REPLACE FUNCTION osrd_prepare_for_search(input_text text) RETURNS text
                LANGUAGE 'sql'
                IMMUTABLE PARALLEL SAFE 
            AS $BODY$
            SELECT lower(coalesce(input_text, ''))
            $BODY$;
            """,
            reverse_sql="""
            DROP FUNCTION IF EXISTS osrd_to_like_search;
            DROP FUNCTION IF EXISTS osrd_prepare_for_search;
            """,
        ),
        run_sql_create_infra_search_table(
            name="osrd_search_operationalpoint",
            source_table="osrd_infra_operationalpointmodel AS opm",
            table_type=SearchTableType.MATERIALIZED_VIEW,
            columns={
                "name": "data#>>'{extensions,identifier,name}'",
                "uic": "data#>>'{extensions,identifier,uic}'",
                "trigram": "data#>>'{extensions,sncf,trigram}'",
            },
            extra_columns={"infra_id": "infra_id"},
            result="""
                SELECT to_jsonb(result)
                FROM (
                    SELECT
                        opm.obj_id AS obj_id,
                        opm.infra_id AS infra_id,
                        opm.data#>>'{extensions,identifier,uic}' AS uic,
                        opm.data#>>'{extensions,identifier,name}' AS localite,
                        opm.data#>>'{extensions,sncf,trigram}' AS code,
                        tsm.data#>'{geo,coordinates}'->0->>0 AS lon,
                        tsm.data#>'{geo,coordinates}'->0->>1 AS lat,
                        tsm.data#>>'{extensions,sncf,line_code}' AS ligne,
                        opm.data#>>'{extensions,sncf,ch}' AS chantier,
                        tsm.data#>>'{extensions,sncf,line_name}' AS libelle
                    FROM osrd_infra_tracksectionmodel AS tsm
                    WHERE tsm.infra_id = opm.infra_id AND tsm.obj_id = opm.data->'parts'->0->>'track'
                ) AS result
            """,
        ),
        # run_sql_create_view(
        #     name="osrd_search_signal",
        #     materialized=True,
        #     sql="""
        #         SELECT id, obj_id, infra_id,
        #             osrd_prepare_for_search(sig.data#>>'{extensions,sncf,label}') AS label,
        #             osrd_prepare_for_search(track.data#>>'{extensions,sncf,track_name}') AS track_name,
        #             osrd_prepare_for_search(track.data#>>'{extensions,sncf,track_number}') AS track_number,
        #             osrd_prepare_for_search(track.data#>>'{extensions,sncf,line_code}') AS track_line_code,
        #             osrd_prepare_for_search(track.data#>>'{extensions,sncf,line_name}') AS track_line_name
        #         FROM osrd_infra_signalmodel AS sig
        #         INNER JOIN osrd_infra_tracksectionmodel AS track
        #     """,
        # ),
    ]
