# Generated by Django 4.1.5 on 2023-01-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0016_rollingstock_power_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lpvpanellayer",
            name="obj",
        ),
        migrations.AddField(
            model_name="lpvpanellayer",
            name="obj_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
