# Generated by Django 4.0.5 on 2022-07-07 09:42

from django.db import migrations, models

import osrd_infra.utils


def apply_migration(apps, schema_editor):
    """Update infra from v2.2.5 to v2.3.0"""
    Infra = apps.get_model("osrd_infra", "Infra")
    SpeedSectionModel = apps.get_model("osrd_infra", "SpeedSectionModel")

    updated_infra = []
    updated_speed_sections = []

    for infra in Infra.objects.all():
        if infra.railjson_version == "2.2.5":
            infra.railjson_version = "2.3.0"
            updated_infra.append(infra)

            for speed_section in SpeedSectionModel.objects.filter(infra=infra):
                speed_section.data["speed_limit"] = speed_section.data.pop("speed")
                speed_section.data["speed_limit_by_tag"] = {}
                updated_speed_sections.append(speed_section)

    Infra.objects.bulk_update(updated_infra, ["railjson_version"])
    SpeedSectionModel.objects.bulk_update(updated_speed_sections, ["data"])


def revert_migration(apps, schema_editor):
    """Revert infra from v2.3.0 to v2.2.5"""
    Infra = apps.get_model("osrd_infra", "Infra")
    SpeedSectionModel = apps.get_model("osrd_infra", "SpeedSectionModel")

    updated_infra = []
    updated_speed_sections = []

    for infra in Infra.objects.all():
        if infra.railjson_version == "2.3.0":
            infra.railjson_version = "2.2.5"
            updated_infra.append(infra)

            for speed_section in SpeedSectionModel.objects.filter(infra=infra):
                speed_section.data["speed"] = speed_section.data.pop("speed_limit")
                speed_section.pop("speed_limit_by_tag")
                updated_speed_sections.append(speed_section)

    Infra.objects.bulk_update(updated_infra, ["railjson_version"])
    SpeedSectionModel.objects.bulk_update(updated_speed_sections, ["data"])


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0019_add_signal_default_aspect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infra",
            name="railjson_version",
            field=models.CharField(default="2.3.0", editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name="speedsectionmodel",
            name="data",
            field=models.JSONField(
                validators=[
                    osrd_infra.utils.JSONSchemaValidator(
                        limit_value={
                            "definitions": {
                                "ApplicableDirections": {
                                    "description": "An enumeration.",
                                    "enum": ["START_TO_STOP", "STOP_TO_START", "BOTH"],
                                    "title": "ApplicableDirections",
                                    "type": "string",
                                },
                                "ApplicableDirectionsTrackRange": {
                                    "properties": {
                                        "applicable_directions": {"$ref": "#/definitions/ApplicableDirections"},
                                        "begin": {"title": "Begin", "type": "number"},
                                        "end": {"title": "End", "type": "number"},
                                        "track": {"$ref": "#/definitions/ObjectReference"},
                                    },
                                    "required": ["track", "begin", "end", "applicable_directions"],
                                    "title": "ApplicableDirectionsTrackRange",
                                    "type": "object",
                                },
                                "ObjectReference": {
                                    "properties": {
                                        "id": {"maxLength": 255, "title": "Id", "type": "string"},
                                        "type": {"title": "Type", "type": "string"},
                                    },
                                    "required": ["id", "type"],
                                    "title": "ObjectReference",
                                    "type": "object",
                                },
                            },
                            "properties": {
                                "id": {"maxLength": 255, "title": "Id", "type": "string"},
                                "speed_limit": {
                                    "description": "Speed limit (m/s) applied by default to all trains",
                                    "title": "Speed Limit",
                                    "type": "number",
                                },
                                "speed_limit_by_tag": {
                                    "additionalProperties": {"type": "number"},
                                    "description": "Speed limit (m/s) applied to trains with a given tag",
                                    "title": "Speed Limit By Tag",
                                    "type": "object",
                                },
                                "track_ranges": {
                                    "items": {"$ref": "#/definitions/ApplicableDirectionsTrackRange"},
                                    "title": "Track Ranges",
                                    "type": "array",
                                },
                            },
                            "required": ["id", "speed_limit_by_tag", "track_ranges"],
                            "title": "SpeedSection",
                            "type": "object",
                        }
                    )
                ]
            ),
        ),
        migrations.RunPython(code=apply_migration, reverse_code=revert_migration),
    ]
