# Generated by Django 4.0.6 on 2022-08-05 14:04

from django.db import migrations, models

import osrd_infra.utils


def apply_migration(apps, schema_editor):
    # Delete all existing rolling stock
    RollingStock = apps.get_model("osrd_infra", "RollingStock")
    RollingStock.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0023_alter_operational_points"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rollingstock",
            old_name="capabilities",
            new_name="features",
        ),
        migrations.RemoveField(
            model_name="rollingstock",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="rollingstock",
            name="timetable_gamma",
        ),
        migrations.RemoveField(
            model_name="rollingstock",
            name="traction_mode",
        ),
        migrations.RemoveField(
            model_name="rollingstock",
            name="tractive_effort_curves",
        ),
        migrations.AddField(
            model_name="rollingstock",
            name="effort_curve",
            field=models.JSONField(
                help_text="A curve mapping speed (in m/s) to maximum traction (in newtons)",
                default={},
                validators=[
                    osrd_infra.utils.JSONSchemaValidator(
                        limit_value={
                            "properties": {
                                "max_efforts": {
                                    "items": {"minimum": 0, "type": "number"},
                                    "minItems": 2,
                                    "title": "Max Efforts",
                                    "type": "array",
                                },
                                "speeds": {
                                    "items": {"minimum": 0, "type": "number"},
                                    "minItems": 2,
                                    "title": "Speeds",
                                    "type": "array",
                                },
                            },
                            "required": ["speeds", "max_efforts"],
                            "title": "EffortCurve",
                            "type": "object",
                        }
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rollingstock",
            name="gamma",
            field=models.JSONField(
                default={},
                help_text="The const or max braking coefficient, for timetabling purposes, in m/s^2",
                validators=[
                    osrd_infra.utils.JSONSchemaValidator(
                        limit_value={
                            "definitions": {
                                "GammaType": {
                                    "description": "An enumeration.",
                                    "enum": ["CONST", "MAX"],
                                    "title": "GammaType",
                                    "type": "string",
                                }
                            },
                            "properties": {
                                "type": {"$ref": "#/definitions/GammaType"},
                                "value": {"exclusiveMinimum": 0, "title": "Value", "type": "number"},
                            },
                            "required": ["type", "value"],
                            "title": "Gamma",
                            "type": "object",
                        }
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rollingstock",
            name="version",
            field=models.CharField(default="2.1", editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name="rollingstock",
            name="rolling_resistance",
            field=models.JSONField(
                help_text="The formula to use to compute rolling resistance",
                validators=[
                    osrd_infra.utils.JSONSchemaValidator(
                        limit_value={
                            "properties": {
                                "A": {"minimum": 0, "title": "A", "type": "number"},
                                "B": {"minimum": 0, "title": "B", "type": "number"},
                                "C": {"minimum": 0, "title": "C", "type": "number"},
                                "type": {"enum": ["davis"], "title": "Type", "type": "string"},
                            },
                            "required": ["type", "A", "B", "C"],
                            "title": "RollingResistance",
                            "type": "object",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rollingstock",
            name="loading_gauge",
            field=models.CharField(
                choices=[
                    ("G1", "G1"),
                    ("G2", "G2"),
                    ("GA", "GA"),
                    ("GB", "GB"),
                    ("GB1", "GB1"),
                    ("GC", "GC"),
                    ("FR3_3", "FR3_3"),
                    ("FR3_3_GB_G2", "FR3_3_GB_G2"),
                    ("GLOTT", "GLOTT"),
                ],
                max_length=16,
            ),
        ),
        migrations.RunPython(code=apply_migration),
    ]
