# Generated by Django 4.0.6 on 2022-08-10 10:46

import django.contrib.postgres.fields
from django.db import migrations, models
import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0024_rolling_stok_v2_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingstock',
            name='effort_curve',
            field=models.JSONField(help_text='A curve mapping speed (in m/s) to maximum traction (in newtons)', validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'max_efforts': {'items': {'minimum': 0, 'type': 'number'}, 'minItems': 2, 'title': 'Max Efforts', 'type': 'array'}, 'speeds': {'items': {'minimum': 0, 'type': 'number'}, 'minItems': 2, 'title': 'Speeds', 'type': 'array'}}, 'required': ['speeds', 'max_efforts'], 'title': 'EffortCurve', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='A list of features the train exhibits, such as ERTMS support', size=None),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='gamma',
            field=models.JSONField(help_text='The const or max braking coefficient, for timetabling purposes, in m/s^2', validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'additionalProperties': False, 'definitions': {'GammaType': {'description': 'An enumeration.', 'enum': ['CONST', 'MAX'], 'title': 'GammaType', 'type': 'string'}}, 'properties': {'type': {'$ref': '#/definitions/GammaType'}, 'value': {'exclusiveMinimum': 0, 'title': 'Value', 'type': 'number'}}, 'required': ['type', 'value'], 'title': 'Gamma', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='loading_gauge',
            field=models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('GA', 'GA'), ('GB', 'GB'), ('GB1', 'GB1'), ('GC', 'GC'), ('FR3.3', 'FR3_3'), ('FR3.3/GB/G2', 'FR3_3_GB_G2'), ('GLOTT', 'GLOTT')], max_length=16),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='rolling_resistance',
            field=models.JSONField(help_text='The formula to use to compute rolling resistance', validators=[osrd_infra.utils.JSONSchemaValidator(limit_value={'additionalProperties': False, 'properties': {'A': {'minimum': 0, 'title': 'A', 'type': 'number'}, 'B': {'minimum': 0, 'title': 'B', 'type': 'number'}, 'C': {'minimum': 0, 'title': 'C', 'type': 'number'}, 'type': {'enum': ['davis'], 'title': 'Type', 'type': 'string'}}, 'required': ['type', 'A', 'B', 'C'], 'title': 'RollingResistance', 'type': 'object'})]),
        ),
    ]
