# Generated by Django 4.0.7 on 2022-08-09 16:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0025_alter_rollingstock_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatenaryLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.CharField(max_length=255)),
                ('geographic', django.contrib.gis.db.models.fields.MultiLineStringField(srid=3857)),
                ('schematic', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('infra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osrd_infra.infra')),
            ],
            options={
                'verbose_name_plural': 'generated catenary layer',
                'unique_together': {('infra', 'obj_id')},
            },
        ),
    ]
