# Generated by Django 4.0.7 on 2022-08-11 08:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osrd_infra', '0026_catenarylayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catenarylayer',
            name='schematic',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=3857),
        ),
    ]
