-- DO NOT EDIT THIS FILE MANUALLY!

DROP TABLE IF EXISTS "search_group";
DROP TRIGGER IF EXISTS search_group__ins_trig ON "authn_group";
DROP TRIGGER IF EXISTS search_group__upd_trig ON "authn_group";
DROP FUNCTION IF EXISTS search_group__ins_trig_fun;
DROP FUNCTION IF EXISTS search_group__upd_trig_fun;
