-- DO NOT EDIT THIS FILE MANUALLY!
-- To change the migration's content, use `editoast search make-migration`.
-- To add custom SQL code, check out `#[derive(Search)]` attributes `prepend_sql` and `append_sql`.

DROP TABLE IF EXISTS "search_group";

CREATE TABLE "search_group" (
    id BIGINT PRIMARY KEY REFERENCES "authn_group"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "name" TEXT
);

CREATE INDEX "search_group_name" ON "search_group" USING gin ("name" gin_trgm_ops);

CREATE OR REPLACE FUNCTION search_group__ins_trig_fun()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO "search_group" (id, name)
        SELECT "authn_group".id AS id, osrd_prepare_for_search(authn_group.name) AS name
        FROM (SELECT NEW.*) AS "authn_group"
        ;
    RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER search_group__ins_trig
AFTER INSERT ON "authn_group"
FOR EACH ROW EXECUTE FUNCTION search_group__ins_trig_fun();


CREATE OR REPLACE FUNCTION search_group__upd_trig_fun()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE "search_group"
        SET "name" = osrd_prepare_for_search(authn_group.name)
        FROM (SELECT NEW.*) AS "authn_group"

        WHERE "authn_group".id = "search_group".id;
    RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER search_group__upd_trig
AFTER UPDATE ON "authn_group"
FOR EACH ROW EXECUTE FUNCTION search_group__upd_trig_fun();



INSERT INTO "search_group" (id, "name")
SELECT
    "authn_group"."id" AS id,
    osrd_prepare_for_search(authn_group.name) AS name
FROM "authn_group"
    ;-- Your SQL goes here
