-- DO NOT EDIT THIS FILE MANUALLY!
-- To change the migration's content, use `editoast search make-migration`.
-- To add custom SQL code, check out `#[derive(Search)]` attributes `prepend_sql` and `append_sql`.

DROP TABLE IF EXISTS "search_operational_point";

CREATE TABLE "search_operational_point" (
    id BIGINT PRIMARY KEY REFERENCES "infra_object_operational_point"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "obj_id" varchar(255),
    "infra_id" integer,
    "uic" integer,
    "trigram" varchar(3),
    "ci" integer,
    "ch" text,
    "name" text
);

CREATE INDEX "search_operational_point_obj_id" ON "search_operational_point" ("obj_id");
CREATE INDEX "search_operational_point_infra_id" ON "search_operational_point" ("infra_id");
CREATE INDEX "search_operational_point_uic" ON "search_operational_point" ("uic");
CREATE INDEX "search_operational_point_trigram" ON "search_operational_point" ("trigram");
CREATE INDEX "search_operational_point_ci" ON "search_operational_point" ("ci");
CREATE INDEX "search_operational_point_ch" ON "search_operational_point" ("ch");
CREATE INDEX "search_operational_point_name" ON "search_operational_point" USING gin ("name" gin_trgm_ops);

CREATE OR REPLACE FUNCTION search_operational_point__ins_trig_fun()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO "search_operational_point" (id, obj_id, infra_id, uic, trigram, ci, ch, name)
        SELECT "infra_object_operational_point".id AS id, (infra_object_operational_point.obj_id) AS obj_id,
    (infra_object_operational_point.infra_id) AS infra_id,
    ((infra_object_operational_point.data->'extensions'->'identifier'->>'uic')::integer) AS uic,
    (infra_object_operational_point.data->'extensions'->'sncf'->>'trigram') AS trigram,
    ((infra_object_operational_point.data->'extensions'->'sncf'->>'ci')::integer) AS ci,
    (infra_object_operational_point.data->'extensions'->'sncf'->>'ch') AS ch,
    osrd_prepare_for_search(infra_object_operational_point.data->'extensions'->'identifier'->>'name') AS name
        FROM (SELECT NEW.*) AS "infra_object_operational_point"
        ;
    RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER search_operational_point__ins_trig
AFTER INSERT ON "infra_object_operational_point"
FOR EACH ROW EXECUTE FUNCTION search_operational_point__ins_trig_fun();


CREATE OR REPLACE FUNCTION search_operational_point__upd_trig_fun()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE "search_operational_point"
        SET "obj_id" = (infra_object_operational_point.obj_id),
        "infra_id" = (infra_object_operational_point.infra_id),
        "uic" = ((infra_object_operational_point.data->'extensions'->'identifier'->>'uic')::integer),
        "trigram" = (infra_object_operational_point.data->'extensions'->'sncf'->>'trigram'),
        "ci" = ((infra_object_operational_point.data->'extensions'->'sncf'->>'ci')::integer),
        "ch" = (infra_object_operational_point.data->'extensions'->'sncf'->>'ch'),
        "name" = osrd_prepare_for_search(infra_object_operational_point.data->'extensions'->'identifier'->>'name')
        FROM (SELECT NEW.*) AS "infra_object_operational_point"
        
        WHERE "infra_object_operational_point".id = "search_operational_point".id;
    RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER search_operational_point__upd_trig
AFTER UPDATE ON "infra_object_operational_point"
FOR EACH ROW EXECUTE FUNCTION search_operational_point__upd_trig_fun();



INSERT INTO "search_operational_point"
SELECT
    "infra_object_operational_point"."id" AS id,
    (infra_object_operational_point.obj_id) AS obj_id
,    (infra_object_operational_point.infra_id) AS infra_id
,    ((infra_object_operational_point.data->'extensions'->'identifier'->>'uic')::integer) AS uic
,    (infra_object_operational_point.data->'extensions'->'sncf'->>'trigram') AS trigram
,    ((infra_object_operational_point.data->'extensions'->'sncf'->>'ci')::integer) AS ci
,    (infra_object_operational_point.data->'extensions'->'sncf'->>'ch') AS ch
,    osrd_prepare_for_search(infra_object_operational_point.data->'extensions'->'identifier'->>'name') AS name
FROM "infra_object_operational_point"
    ;
