name: Build and push to dockerhub

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
      context:
        type: string
        required: false
        default: "."
      dockerfile:
        type: string
        required: false
        default: "Dockerfile"
      build-args:
        type: string
        required: false
        default: ""
    secrets:
      DOCKERHUB_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ image_name }}
        id: docker_meta

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "${{ context }}"
          file: "${{ context }}/${{ dockerfile }}"
          build-args: "${{ build-args }}"
          push: true
          tags: |
            ${{ image_name }}
            ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
