-- This recreate the stdcm_logs table that was removed in the up migration
CREATE TABLE IF NOT EXISTS stdcm_logs (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    trace_id VARCHAR(32) UNIQUE NOT NULL,
    request jsonb NOT NULL,
    response jsonb NOT NULL,
	created timestamptz NOT NULL DEFAULT NOW(),
    user_id bigint REFERENCES authn_user ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS stdcm_logs_trace_id ON stdcm_logs (trace_id);
CREATE INDEX pga_idx_fk_stdcm_logs_user_id ON public.stdcm_logs (user_id);
