CREATE TABLE stdcm_request (
    -- internal id of the request, generated by editoast
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    -- external id of the request's response, sent by rmi and untouched by editoast
    rmi_id text UNIQUE NOT NULL,
    -- id of the user that sent the request
    created_by int8 NOT NULL REFERENCES authn_user(id) ON DELETE CASCADE,
    -- trace id of the initial stdcm request made to editoast/core, for debug purposes
    trace_id text NULL
);
CREATE INDEX pga_idx_stdcm_request_created_by on public.stdcm_request (created_by);
