create table authn_user_identity (
    id bigint primary key generated by default as identity,
    user_id bigint references authn_user on delete cascade not null,
    identity TEXT not null,
    unique (identity)
);

insert into authn_user_identity (user_id, identity)
select id as user_id, identity_id as identity from authn_user;

alter table authn_user drop column if exists identity_id;

create index idx_authn_user_identity_user_id on authn_user_identity using btree (user_id);

create function delete_associated_authn_user()
returns trigger as $$
begin
    if not exists (
        select *
        from authn_user
        inner join authn_user_identity on authn_user.id = authn_user_identity.user_id
        where authn_user.id = old.user_id
    ) then
        delete from authn_user where id = old.user_id;
    end if;
    return old;
end;
$$ language plpgsql;

create trigger authn_user_delete_trigger
after delete on authn_user_identity
for each row execute function delete_associated_authn_user();

create function check_user_has_at_least_one_identity_after_delete()
returns trigger as $$
begin
    if not (
        select count(*) > 0
        from authn_user_identity
        where user_id = new.id
    ) then
        raise exception 'Inserting user with no associated identity';
    end if;
    return old;
end;
$$ language plpgsql;

create constraint trigger check_authn_user_has_at_least_one_identity_after_delete
after insert on authn_user
deferrable initially deferred
for each row execute function check_user_has_at_least_one_identity_after_delete();

create function check_authn_user_identity_update_does_not_leave_user_without_identity()
returns trigger as $$
begin
    if not exists (
        select * from authn_user_identity
        where user_id = old.user_id
    ) then
        raise exception 'Updating the user associated with an identity would leave its prior user without any identity';
    end if;
    return old;
end;
$$ language plpgsql;

create trigger check_authn_user_identity_update
after update of user_id on authn_user_identity
for each row execute function check_authn_user_identity_update_does_not_leave_user_without_identity();
