CREATE TABLE train_schedule_linking (
    id INT8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timetable_id INT8 NOT NULL REFERENCES timetable(id) ON DELETE CASCADE,
    source_train_schedule_id INT8 REFERENCES train_schedule(id) ON DELETE CASCADE NOT NULL,
    source_occurrence_index INT8,
    source_added_exception_id INT8 REFERENCES train_schedule_exception(id) ON DELETE CASCADE,
    source_train_schedule_instance_index INT8,
    target_train_schedule_id INT8 REFERENCES train_schedule(id) ON DELETE CASCADE NOT NULL,
    target_occurrence_index INT8,
    target_added_exception_id INT8 REFERENCES train_schedule_exception(id) ON DELETE CASCADE,
    target_train_schedule_instance_index INT8,
    CHECK (source_occurrence_index IS NULL OR source_added_exception_id IS NULL),
    CHECK (target_occurrence_index IS NULL OR target_added_exception_id IS NULL),
    UNIQUE NULLS NOT DISTINCT (timetable_id, source_train_schedule_id, source_occurrence_index, source_added_exception_id),
    UNIQUE NULLS NOT DISTINCT (timetable_id, target_train_schedule_id, target_occurrence_index, target_added_exception_id)
);

-- No need to create indexes because the UNIQUES cover them
