[package]
name = "osrd_containers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rangemap.workspace = true
serde.workspace = true
serde_derive.workspace = true
