-- Your SQL goes here

CREATE TABLE towed_rolling_stock (
	id INT8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255) NOT NULL UNIQUE,
	railjson_version VARCHAR(16) NOT NULL,
	locked BOOL NOT NULL,

	mass FLOAT8 NOT NULL,
	length FLOAT8 NOT NULL,
	comfort_acceleration FLOAT8 NOT NULL,
	startup_acceleration FLOAT8 NOT NULL,
	inertia_coefficient FLOAT8 NOT NULL,
	rolling_resistance JSONB NOT NULL,
	gamma JSONB NOT NULL,

	version INT8 NOT NULL
);
