CREATE TABLE scenario_v2 (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    infra_id int8 NOT NULL REFERENCES infra(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    name varchar(128) NOT NULL,
    description varchar(1024) NOT NULL,
    creation_date timestamptz NOT NULL,
    last_modification timestamptz NOT NULL,
    tags text [] NOT NULL,
    timetable_id int8 NOT NULL UNIQUE REFERENCES timetable_v2(id) ON DELETE CASCADE,
    study_id int8 NOT NULL REFERENCES study(id) ON DELETE CASCADE
);
