-- DO NOT EDIT THIS FILE MANUALLY!

DROP TABLE IF EXISTS "search_signal";
DROP TRIGGER IF EXISTS search_signal__ins_trig ON "infra_object_signal";
DROP TRIGGER IF EXISTS search_signal__upd_trig ON "infra_object_signal";
DROP FUNCTION IF EXISTS search_signal__ins_trig;
DROP FUNCTION IF EXISTS search_signal__upd_trig;
