CREATE INDEX idx_fkey_train_schedule_linking_source_train_schedule_id ON train_schedule_linking (source_train_schedule_id);
CREATE INDEX idx_fkey_train_schedule_linking_target_train_schedule_id ON train_schedule_linking (target_train_schedule_id);
CREATE INDEX idx_fkey_train_schedule_linking_source_added_exception_id ON train_schedule_linking (source_added_exception_id);
CREATE INDEX idx_fkey_train_schedule_linking_target_added_exception_id ON train_schedule_linking (target_added_exception_id);
