[package]
name = "editoast_schemas"
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0"

[dependencies]
chrono.workspace = true
derivative.workspace = true
editoast_common.workspace = true
enum-map.workspace = true
geojson.workspace = true
iso8601 = "0.6.1"
rand.workspace = true
rangemap.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
strum.workspace = true
thiserror.workspace = true
utoipa.workspace = true
uuid.workspace = true
