import type { TimesStopsTableRow } from '../../../utils/times-stops-table-types';

export const expectedOutputsCellsData: TimesStopsTableRow[] = [
  {
    index: 1,
    status: 'success-schedule',
    stationName: 'West_station',
    stationCh: 'BV',
    trackName: 'V2',
    requestedArrival: '11:22:40',
    calculatedArrival: '11:22:40',
    stopTime: '',
    requestedDeparture: '',
    calculatedDeparture: '•',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: {
      requestedTheoretical: '5%',
      computedTheoretical: '00m18s',
      real: '19m00s',
      difference: '+18m42s',
    },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
  },
  {
    index: 2,
    status: 'success-schedule',
    stationName: 'Mid_West_station',
    stationCh: 'BV',
    trackName: 'V1',
    requestedArrival: '11:47:40',
    calculatedArrival: '11:47:40',
    stopTime: '00h05m00s',
    requestedDeparture: '11:52:40',
    calculatedDeparture: '11:52:40',
    signalReceptionClosed: true,
    shortSlipDistance: true,
    powerRestriction: '',
    margin: {
      requestedTheoretical: '1min/100km',
      computedTheoretical: '00m09s',
      real: '04m13s',
      difference: '+04m04s',
    },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
  },
  {
    index: 3,
    status: 'success-schedule',
    stationName: 'Mid_East_station',
    stationCh: 'BV',
    trackName: 'V1',
    requestedArrival: '12:05:21',
    calculatedArrival: '12:05:21',
    stopTime: '00h02m04s',
    requestedDeparture: '12:07:25',
    calculatedDeparture: '12:07:25',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: {
      requestedTheoretical: '1min/100km',
      computedTheoretical: '00m12s',
      real: '00m12s',
      difference: '00m00s',
    },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
  },
  {
    index: 4,
    status: '',
    stationName: 'North_East_station',
    stationCh: 'BV',
    trackName: 'V1',
    requestedArrival: '',
    calculatedArrival: '12:16:23',
    stopTime: '00h00m00s',
    requestedDeparture: '',
    calculatedDeparture: '12:16:23',
    signalReceptionClosed: false,
    shortSlipDistance: false,
    powerRestriction: '',
    margin: { requestedTheoretical: '', computedTheoretical: '', real: '', difference: '' },
    timeFromAboveWaypoint: '',
    totalArrivalTime: '',
  },
];
