# Build Storybook with node
FROM node:18-alpine as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# build dependencies
COPY package.json yarn.lock /app/
RUN yarn

# build the storybook
COPY . /app
RUN yarn build-storybook

# Copy & serve app
FROM nginx:alpine

ARG NGINX_CONFIG=nginx.conf
COPY --from=build /app/storybook-static /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/$NGINX_CONFIG /etc/nginx/conf.d

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
