/** @type {import("stylelint").Config} */
export default {
  extends: ['stylelint-config-standard-scss'],
  rules: {
    'alpha-value-notation': null,
    'at-rule-no-vendor-prefix': null,
    'color-function-alias-notation': null,
    'color-function-notation': null,
    'color-hex-length': null,
    'custom-property-pattern': null,
    'declaration-block-no-redundant-longhand-properties': null,
    'keyframes-name-pattern': null,
    'media-feature-range-notation': null,
    'scss/at-extend-no-missing-placeholder': null,
    'scss/at-mixin-argumentless-call-parentheses': null,
    'scss/at-mixin-pattern': null,
    'scss/at-rule-no-unknown': null,
    'scss/dollar-variable-colon-space-after': null,
    'scss/dollar-variable-pattern': null,
    'scss/load-no-partial-leading-underscore': null,
    'scss/load-partial-extension': null,
    'scss/no-global-function-names': null,
    'scss/operator-no-newline-after': null,
    'selector-class-pattern': null,
    'shorthand-property-no-redundant-values': null,
  },
};
