# Generated by Django 4.1.3 on 2022-12-19 16:26

from django.db import migrations

from osrd_infra.migrations import run_sql_create_infra_search_table


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0004_trainschedulemodel_options"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION osrd_prepare_for_search(input_text text)
                RETURNS text
                LANGUAGE 'sql'
                IMMUTABLE PARALLEL SAFE 
            AS $BODY$
                SELECT array_to_string(
                        tsvector_to_array(
                            to_tsvector('simple', unaccent(coalesce(input_text, '')))
                        ),
                        E'\\n'
                    )
            $BODY$;
            CREATE OR REPLACE FUNCTION osrd_to_ilike_search(query text)
                RETURNS text
                LANGUAGE 'sql'
                IMMUTABLE PARALLEL SAFE 
            AS $BODY$
                SELECT '%' || array_to_string(
                        tsvector_to_array(
                            to_tsvector(
                                'simple',
                                unaccent(
                                    replace(
                                        coalesce(query, ''),
                                        '-',
                                        ' '
                                    )
                                )
                            )
                        ),
                        '%'
                    ) || '%'
            $BODY$;
            """,
            reverse_sql="""
            DROP FUNCTION IF EXISTS osrd_prepare_for_search;
            DROP FUNCTION IF EXISTS osrd_to_like_search;
            """,
        ),
        run_sql_create_infra_search_table(
            name="osrd_search_operationalpoint",
            source_table="osrd_infra_operationalpointmodel",
            search_columns={
                "name": "{source}.data#>>'{{extensions,identifier,name}}'",
                "uic": "{source}.data#>>'{{extensions,identifier,uic}}'",
                "trigram": "{source}.data#>>'{{extensions,sncf,trigram}}'",
            },
            extra_columns={
                "infra_id": ("{source}.infra_id", "INT"),
                "obj_id": ("{source}.obj_id", "VARCHAR(255)"),
            },
            triggers=True,
            phony_model_name="OsrdSearchOperationalPoint",
        ),
    ]
