# Generated by Django 4.1.5 on 2023-03-02 08:58

import django.db.models.deletion
import osrd_schemas.rolling_stock
import osrd_schemas.train_schedule
from django.db import migrations, models

import osrd_infra.utils
from osrd_infra.migrations import run_sql_add_foreign_key, run_sql_add_one_to_one_key


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0011_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationOutput",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "mrsp",
                    models.JSONField(validators=[osrd_infra.utils.PydanticValidator(osrd_schemas.train_schedule.MRSP)]),
                ),
                ("base_simulation", models.JSONField()),
                ("eco_simulation", models.JSONField(null=True)),
                ("modes_and_profiles", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="TrainSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("train_name", models.CharField(max_length=128)),
                (
                    "labels",
                    models.JSONField(
                        default=list,
                        validators=[
                            osrd_infra.utils.PydanticValidator(osrd_schemas.train_schedule.TrainScheduleLabels)
                        ],
                    ),
                ),
                ("departure_time", models.FloatField()),
                ("initial_speed", models.FloatField()),
                (
                    "allowances",
                    models.JSONField(
                        default=list,
                        validators=[osrd_infra.utils.PydanticValidator(osrd_schemas.train_schedule.Allowances)],
                    ),
                ),
                (
                    "comfort",
                    models.CharField(
                        choices=[("STANDARD", "STANDARD"), ("AC", "AC"), ("HEATING", "HEATING")],
                        default=osrd_schemas.rolling_stock.ComfortType["STANDARD"],
                        max_length=8,
                    ),
                ),
                ("speed_limit_tags", models.CharField(max_length=128, null=True)),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[
                            osrd_infra.utils.PydanticValidator(osrd_schemas.train_schedule.TrainScheduleOptions)
                        ],
                    ),
                ),
            ],
        ),
        run_sql_add_foreign_key("trainschedule", "path", "pathmodel"),
        run_sql_add_foreign_key("trainschedule", "rolling_stock", "rollingstock"),
        run_sql_add_foreign_key("trainschedule", "timetable", "timetable", related_name="train_schedules"),
        migrations.DeleteModel(
            name="TrainScheduleModel",
        ),
        run_sql_add_one_to_one_key("simulationoutput", "train_schedule", "trainschedule", "simulation_output"),
    ]
