# Generated by Django 4.1.5 on 2023-03-01 20:53

import django.db.models.deletion
from django.db import migrations, models

from osrd_infra.migrations import run_sql_add_foreign_key


class Migration(migrations.Migration):
    dependencies = [
        ("osrd_infra", "0013_simulationoutput_trainschedule_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.OneToOneField(
                null=True, on_delete=models.PROTECT, related_name="project", to="osrd_infra.document"
            ),
        ),
    ]
