# Generated by Django 4.1.5 on 2023-03-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("osrd_infra", "0017_migrate_integer_reference_to_bigint"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    f"""ALTER TABLE osrd_infra_rollingstocklivery
                    DROP CONSTRAINT osrd_rollingstockcompoundimage_rollingstocklivery_fkey,
                    ADD CONSTRAINT osrd_rollingstockcompoundimage_rollingstocklivery_fkey
                    FOREIGN KEY (compound_image_id)
                    REFERENCES osrd_infra_rollingstockimage(id)
                    ON DELETE SET NULL
                    """
                )
            ],
            reverse_sql=[
                (
                    f"""ALTER TABLE osrd_infra_rollingstocklivery
                    DROP CONSTRAINT osrd_rollingstockcompoundimage_rollingstocklivery_fkey,
                    ADD CONSTRAINT osrd_rollingstockcompoundimage_rollingstocklivery_fkey
                    FOREIGN KEY (compound_image_id)
                    REFERENCES osrd_infra_rollingstockimage(id)
                    ON DELETE CASCADE
                    """
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="rollingstocklivery",
                    name="compound_image",
                    field=models.OneToOneField(
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        to="osrd_infra.rollingstockcompoundimage",
                    ),
                ),
            ],
        ),
    ]
