# Generated by Django 4.1.5 on 2023-03-22 17:05

import django.db.models.deletion
from django.db import migrations, models

from osrd_infra.migrations import run_sql_add_one_to_one_key


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0019_rename_type_study_study_type"),
    ]

    operations = [
        # in RollingStockLivery, drop constraint FK rollingStockLivery <--> rollingStockCompoundImage
        migrations.RunSQL(
            sql=[
                (
                    f"""ALTER TABLE osrd_infra_rollingstocklivery
                    DROP CONSTRAINT osrd_rollingstockcompoundimage_rollingstocklivery_fkey
                    """
                )
            ],
            reverse_sql=[
                (
                    f"""ALTER TABLE osrd_infra_rollingstocklivery
                    ADD CONSTRAINT osrd_rollingstockcompoundimage_rollingstocklivery_fkey
                    FOREIGN KEY (compound_image_id)
                    REFERENCES osrd_infra_rollingstockimage(id)
                    ON DELETE SET NULL
                    """
                )
            ],
        ),
        # delete RollingStockCompoundImage model
        migrations.DeleteModel(
            name="RollingStockCompoundImage",
        ),
        # in RollingStockLivery, drop field compound_image
        migrations.RemoveField(
            model_name="rollingstocklivery",
            name="compound_image",
        ),
        # add new FK 1to1 rollingStockLivery <--> document (field compound_image_id)
        run_sql_add_one_to_one_key(
            model_name="rollingstocklivery",
            field_name="compound_image",
            link_model="document",
            nullable=True,
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.SET_NULL,
                to="osrd_infra.document",
                null=True,
            ),
        ),
        # in RollingStockSeparatedImage, drop field image
        migrations.RemoveField(
            model_name="rollingstockseparatedimage",
            name="image",
        ),
        # rename table osrd_infra_rollingstockimage -> osrd_infra_rollingstockseparatedimage
        migrations.AlterModelTable(
            name="rollingstockseparatedimage",
            table="osrd_infra_rollingstockseparatedimage",
        ),
        # in RollingStockSeparatedImage, add new FK 1to1 image_id  rollingStockSeparatedImage <--> document
        run_sql_add_one_to_one_key(
            model_name="rollingstockseparatedimage",
            field_name="image",
            link_model="document",
        ),
    ]
