# Generated by Django 4.1.5 on 2023-03-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0020_search_signals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infra",
            name="railjson_version",
            field=models.CharField(default="3.2.0", editable=False, max_length=16),
        ),
        migrations.RunSQL(
            sql=[("UPDATE osrd_infra_infra SET railjson_version = '3.2.0'")],
            reverse_sql=[("UPDATE osrd_infra_infra SET railjson_version = '3.1.0'")],
        ),
        migrations.RunSQL(
            sql=[("UPDATE osrd_infra_bufferstopmodel SET data = data - 'applicable_directions'")],
            reverse_sql=[
                (
                    "UPDATE osrd_infra_bufferstopmodel SET data = data || jsonb_build_object('applicable_directions', 'START_TO_STOP')"
                )
            ],
        ),
    ]
