# Generated by Django 4.1.5 on 2023-03-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0021_railjson_3_2_0"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="actual_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="study",
            name="expected_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="study",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
