# Generated by Django 4.1.5 on 2023-04-05 13:06

from django.db import migrations, models

from osrd_infra.migrations import run_sql_create_infra_search_table


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0022_alter_study_actual_end_date_and_more"),
    ]

    operations = [
        run_sql_create_infra_search_table(
            name="osrd_search_project",
            source_table="osrd_infra_project",
            search_columns={
                "name": "{source}.name",
                "description": "{source}.description",
            },
            extra_columns={ 
                "tags": ("{source}.tags", "TEXT[]"), 
                },
            triggers=True,
            phony_model_name="OsrdSearchProject",
        ),
    ]
