# Generated by Django 4.1.5 on 2023-04-05 08:55

import osrd_schemas.rolling_stock
from django.db import migrations, models

import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0022_alter_study_actual_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollingstock",
            name="energy_sources",
            field=models.JSONField(
                help_text="A list of energy sources (e.g. catenaries, batteries, power packs)",
                null=True,
                validators=[osrd_infra.utils.PydanticValidator(osrd_schemas.rolling_stock.EnergySource)],
            ),
        ),
    ]
