# Generated by Django 4.1.5 on 2023-04-11 09:14

from django.db import migrations

from osrd_infra.migrations import run_sql_create_infra_search_table


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0023_alter_rollingstocklivery_compound_image_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE osrd_search_operationalpoint DROP CONSTRAINT IF EXISTS osrd_search_operationalpoint_pkey;
                ALTER TABLE osrd_search_operationalpoint ADD PRIMARY KEY(id);
                ALTER TABLE osrd_search_signal DROP CONSTRAINT IF EXISTS osrd_search_signal_pkey;
                ALTER TABLE osrd_search_signal ADD PRIMARY KEY(id);
                ALTER TABLE osrd_search_track ADD COLUMN id BIGSERIAL PRIMARY KEY;
            """,
            reverse_sql="""
                ALTER TABLE osrd_search_operationalpoint DROP PRIMARY KEY;
                ALTER TABLE osrd_search_signal DROP PRIMARY KEY;
                ALTER TABLE osrd_search_track DROP COLUMN id;
            """,
        ),
    ]
