# Generated by Django 4.1.5 on 2023-04-07 12:39

from django.db import migrations, models

from osrd_infra.migrations import run_sql_create_infra_search_table


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0023_osrdsearchproject_alter_infra_railjson_version"),
    ]

    operations = [
        run_sql_create_infra_search_table(
            name="osrd_search_study",
            source_table="osrd_infra_study",
            search_columns={
                "name": "{source}.name",
                "description": "{source}.description",
            },
            triggers=True,
            phony_model_name="OsrdSearchStudy",
        ),

        run_sql_create_infra_search_table(
            name="osrd_search_scenario",
            source_table="osrd_infra_scenario",
            search_columns={
                "name": "{source}.name",
                "description": "{source}.description",
            },
            triggers=True,
            phony_model_name="OsrdSearchScenario",
        ),
    ]
