# Generated by Django 4.1.5 on 2023-04-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0023_alter_rollingstocklivery_compound_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simulationoutput",
            old_name="modes_and_profiles",
            new_name="electrification_conditions",
        ),
    ]
