# Generated by Django 4.1.5 on 2023-04-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0024_rollingstock_energy_sources"),
        ("osrd_infra", "0026_osrdsearchproject_study_scenario"),
    ]

    operations = []
