# Generated by Django 4.1.5 on 2023-04-06 15:27

import django.contrib.postgres.fields
import osrd_schemas.rolling_stock
from django.db import migrations, models

import osrd_infra.utils


class Migration(migrations.Migration):
    dependencies = [
        ("osrd_infra", "0026_osrdsearchproject_study_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollingstock",
            name="energy_sources",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(
                    help_text="A list of energy sources (e.g. catenaries, batteries, power packs)",
                    null=True,
                    validators=[osrd_infra.utils.PydanticValidator(osrd_schemas.rolling_stock.EnergySource)],
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
