# Generated by Django 4.1.5 on 2023-05-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0026_osrdsearchproject_study_scenario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infra",
            name="railjson_version",
            field=models.CharField(default="3.2.1", editable=False, max_length=16),
        ),
        migrations.RunSQL(
            sql=[
                (
                    """
                    UPDATE osrd_infra_signalmodel SET data = data #- '{extensions, sncf, angle_geo}'
                                                                  #- '{extensions, sncf, angle_sch}'
                    """
                )
            ],
            reverse_sql=[
                (
                    """
                    UPDATE osrd_infra_signalmodel SET data =
                        jsonb_set(
                            jsonb_set(data,  '{extensions, sncf, angle_sch}', '0'),
                            '{extensions, sncf, angle_geo}', '0')
                    """
                )
            ],
        ),
        migrations.RunSQL(
            sql=[("UPDATE osrd_infra_infra SET railjson_version = '3.2.1'")],
            reverse_sql=[("UPDATE osrd_infra_infra SET railjson_version = '3.2.0'")],
        ),
        migrations.AddField(
            model_name="signallayer",
            name="angle_geo",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="signallayer",
            name="angle_sch",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
