# Generated by Django 4.1.5 on 2023-05-22 09:13

import osrd_schemas.rolling_stock
from django.db import migrations, models

import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0027_railjson_3_2_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollingstock",
            name="energy_sources",
            field=models.JSONField(
                default=list,
                help_text="A list of energy sources (e.g. catenaries, batteries, power packs)",
                validators=[osrd_infra.utils.PydanticValidator(osrd_schemas.rolling_stock.EnergySourcesList)],
            ),
        ),
    ]
