# Generated by Django 4.1.5 on 2023-05-22 08:19

import django.db.models.deletion
import osrd_schemas.infra
from django.db import migrations, models

import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0027_railjson_3_2_1"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeadSectionModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("obj_id", models.CharField(max_length=255)),
                (
                    "data",
                    models.JSONField(validators=[osrd_infra.utils.PydanticValidator(osrd_schemas.infra.DeadSection)]),
                ),
                ("infra", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="osrd_infra.infra")),
            ],
            options={
                "verbose_name_plural": "dead sections",
                "unique_together": {("infra", "obj_id")},
            },
        ),
    ]
