# Generated by Django 4.1.5 on 2023-05-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0029_railjson_3_2_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infra",
            name="railjson_version",
            field=models.CharField(default="3.3.1", editable=False, max_length=16),
        ),
    ]
