# Generated by Django 4.1.5 on 2023-05-24 14:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("osrd_infra", "0031_railjson_3_3_1"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeadSectionLayer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("obj_id", models.CharField(max_length=255)),
                ("geographic", django.contrib.gis.db.models.fields.MultiLineStringField(srid=3857)),
                ("schematic", django.contrib.gis.db.models.fields.MultiLineStringField(srid=3857)),
                ("infra", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="osrd_infra.infra")),
            ],
            options={
                "verbose_name_plural": "generated dead section layer",
                "unique_together": {("infra", "obj_id")},
            },
        ),
        migrations.CreateModel(
            name="BacksidePantographDeadSectionLayer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("obj_id", models.CharField(max_length=255)),
                ("geographic", django.contrib.gis.db.models.fields.MultiLineStringField(srid=3857)),
                ("schematic", django.contrib.gis.db.models.fields.MultiLineStringField(srid=3857)),
                ("infra", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="osrd_infra.infra")),
            ],
            options={
                "verbose_name_plural": "generated back side pantograph dead section layer",
                "unique_together": {("infra", "obj_id")},
            },
        ),
    ]
