# Generated by Django 4.1.5 on 2023-06-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0032_dead_sections_layer"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollingstock",
            name="locked",
            field=models.BooleanField(
                default=False, help_text="Whether the rolling stock can be edited/deleted or not."
            ),
        ),
    ]
