# Generated by Django 4.1.5 on 2023-06-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("osrd_infra", "0036_search_op_add_ch"),
    ]

    operations = [
        migrations.AddField(
            model_name="pathmodel",
            name="length",
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.RunSQL(
            sql=[("DELETE FROM osrd_infra_pathmodel")],
        ),
    ]
