# Generated by Django 4.1.5 on 2023-07-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0038_update_simulationoutput"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rollingstock",
            old_name="version",
            new_name="railjson_version",
        ),
        migrations.AddField(
            model_name="rollingstock",
            name="rollingstock_version",
            field=models.BigIntegerField(default=0, help_text="Rolling stock version"),
        ),
    ]
