# Generated by Django 4.1.5 on 2023-07-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("osrd_infra", "0039_rename_version_rollingstock_railjson_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainschedule",
            name="infra_version",
            field=models.CharField(default="1", editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name="trainschedule",
            name="rollingstock_version",
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
