# Generated by Django 4.1.5 on 2023-08-01 13:12

from django.db import migrations, models


def rename_drop_to_lower(apps, schema_editor):
    NeutralSection = apps.get_model("osrd_infra", "NeutralSectionModel")
    for neutral_section in NeutralSection.objects.all():
        neutral_section.data["lower_pantograph"] = neutral_section.data.pop("is_pantograph_drop_zone", False)
        neutral_section.save()


def rename_lower_to_drop(apps, schema_editor):
    NeutralSection = apps.get_model("osrd_infra", "NeutralSectionModel")
    for neutral_section in NeutralSection.objects.all():
        neutral_section.data["is_pantograph_drop_zone"] = neutral_section.data.pop("lower_pantograph", False)
        neutral_section.save()


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0043_rename_dead_section_to_neutral_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infra",
            name="railjson_version",
            field=models.CharField(default="3.6.0", editable=False, max_length=16),
        ),
        migrations.RunPython(rename_drop_to_lower, rename_lower_to_drop),
    ]
