# Generated by Django 4.2.3 on 2023-08-09 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("osrd_infra", "0046_fill_rolling_stock_system_times"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE osrd_infra_scenario
                DROP CONSTRAINT osrd_infra_scenario_infra_id_1f77a8c1_fk_osrd_infra_infra_id,
                ADD CONSTRAINT osrd_infra_scenario_infra_id
                FOREIGN KEY (infra_id)
                REFERENCES osrd_infra_infra(id)
                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
                """
            ],
            reverse_sql=[
                """
                ALTER TABLE osrd_infra_scenario
                DROP CONSTRAINT osrd_infra_scenario_infra_id,
                ADD CONSTRAINT osrd_infra_scenario_infra_id_1f77a8c1_fk_osrd_infra_infra_id
                FOREIGN KEY (infra_id)
                REFERENCES osrd_infra_infra(id)
                """
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="scenario",
                    name="infra",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="osrd_infra.infra"),
                ),
            ],
        ),
    ]
