# Generated by Django 4.1.5 on 2023-08-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("osrd_infra", "0047_alter_scenario_infra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infra",
            name="railjson_version",
            field=models.CharField(default="3.4.1", editable=False, max_length=16),
        ),
        migrations.RunSQL(
            sql=["UPDATE osrd_infra_infra SET railjson_version = '3.4.1'"],
            reverse_sql=["UPDATE osrd_infra_infra SET railjson_version = '3.4.0'"],
        ),
        migrations.RunSQL(
            sql=["""UPDATE osrd_infra_neutralsectionmodel SET data['announcement_track_ranges'] = '[]'::jsonb"""],
            reverse_sql=["""UPDATE osrd_infra_neutralsectionmodel SET data = data - 'announcement_track_ranges'"""],
        ),
    ]
