# Generated by Django 4.2.3 on 2023-09-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("osrd_infra", "0048_railjson_3_4_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infra",
            name="railjson_version",
            field=models.CharField(default="3.4.2", editable=False, max_length=16),
        ),
        migrations.RunSQL(
            sql=["UPDATE osrd_infra_infra SET railjson_version = '3.4.2'"],
            reverse_sql=["UPDATE osrd_infra_infra SET railjson_version = '3.4.1'"],
        ),
        migrations.RenameModel(
            old_name="LPVPanelLayer",
            new_name="PSLSignLayer",
        ),
        migrations.RunSQL(
            sql=["""UPDATE osrd_infra_speedsectionmodel SET data['extensions']['psl_sncf'] = data['extensions']['lpv_sncf']""",
                 """UPDATE osrd_infra_speedsectionmodel SET data['extensions'] = data['extensions'] - 'lpv_sncf'"""
            ],
            reverse_sql=["""UPDATE osrd_infra_speedsectionmodel SET data['extensions']['lpv_sncf'] = data['extensions']['psl_sncf']""",
                         """UPDATE osrd_infra_speedsectionmodel SET data['extensions'] = data['extensions'] - 'psl_sncf'"""
            ],
        ),
    ]
