-- DO NOT EDIT THIS FILE MANUALLY!
-- To change the migration's content, use `editoast search make-migration`.
-- To add custom SQL code, check out `#[derive(Search)]` attributes `prepend_sql` and `append_sql`.

DROP TABLE IF EXISTS "search_user";

CREATE TABLE "search_user" (
    id BIGINT PRIMARY KEY REFERENCES "authn_user"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "identity_id" TEXT,
    "name" TEXT
);

CREATE INDEX "search_user_identity_id" ON "search_user" ("identity_id");
CREATE INDEX "search_user_name" ON "search_user" USING gin ("name" gin_trgm_ops);

CREATE OR REPLACE FUNCTION search_user__ins_trig_fun()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO "search_user" (id, identity_id, name)
        SELECT "authn_user".id AS id, (authn_user.identity_id) AS identity_id,
    osrd_prepare_for_search(authn_user.name) AS name
        FROM (SELECT NEW.*) AS "authn_user"
        ;
    RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER search_user__ins_trig
AFTER INSERT ON "authn_user"
FOR EACH ROW EXECUTE FUNCTION search_user__ins_trig_fun();


CREATE OR REPLACE FUNCTION search_user__upd_trig_fun()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE "search_user"
        SET "identity_id" = (authn_user.identity_id),
        "name" = osrd_prepare_for_search(authn_user.name)
        FROM (SELECT NEW.*) AS "authn_user"
        
        WHERE "authn_user".id = "search_user".id;
    RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER search_user__upd_trig
AFTER UPDATE ON "authn_user"
FOR EACH ROW EXECUTE FUNCTION search_user__upd_trig_fun();



INSERT INTO "search_user" (id, "identity_id", "name")
SELECT
    "authn_user"."id" AS id,
    (authn_user.identity_id) AS identity_id
,    osrd_prepare_for_search(authn_user.name) AS name
FROM "authn_user"
    ;
