ALTER TABLE infra
ALTER COLUMN owner
DROP DEFAULT;

ALTER TABLE infra
ALTER COLUMN version
DROP DEFAULT;

ALTER TABLE infra
ALTER COLUMN generated_version
DROP DEFAULT;

ALTER TABLE infra
ALTER COLUMN locked
DROP DEFAULT;

ALTER TABLE infra
ALTER COLUMN created
DROP DEFAULT;

ALTER TABLE infra
ALTER COLUMN modified
DROP DEFAULT;

ALTER TABLE infra
ALTER COLUMN railjson_version
SET DEFAULT '3.4.11';
