[package]
name = "uniffi-bindgen"
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0"

[dependencies]
uniffi = { workspace = true, features = ["cli"] }

[[bin]]
name = "uniffi-bindgen"
path = "src/main.rs"
