CREATE TABLE train_schedule_round_trips (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    left_id int8 UNIQUE NOT NULL REFERENCES train_schedule(id) ON DELETE CASCADE,
    right_id int8 UNIQUE REFERENCES train_schedule(id) ON DELETE CASCADE,
    CONSTRAINT id_order CHECK (
        right_id IS NULL
        OR left_id < right_id
    )
);

CREATE TABLE paced_train_round_trips (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    left_id int8 UNIQUE NOT NULL REFERENCES paced_train(id) ON DELETE CASCADE,
    right_id int8 UNIQUE REFERENCES paced_train(id) ON DELETE CASCADE,
    CONSTRAINT id_order CHECK (
        right_id IS NULL
        OR left_id < right_id
    )
);
