#!/usr/bin/env just --justfile

# Display available recipes
help:
    @just --list --unsorted

# Generate small infra
run:
    mkdir -p small_infra_out
    uv run scripts/small_infra.py small_infra_out

# Install required dependencies
install:
    uv sync --all-extras

# Run the tests
test:
    uv run pytest

# Format the source code
format:
    uv run ruff format

# Verify code lints without applying any fix
lint:
    uv run ruff check
    uv run pyright .

# Fix all the lints that can be automatically applied
fix-lint:
    uv run ruff check --fix
