#!/usr/bin/env just --justfile

# Display available recipes
help:
    @just --list --unsorted

# Run the application; does not start other services
run *args:
    cargo run {{ args }}

# Install required dependencies
install:
    cargo build

# Run the tests
test:
    cargo test

# Format the source code
format:
    cargo fmt --all
    taplo fmt

# Verify code lints without applying any fix
lint:
    cargo clippy --all-features --all-targets

# Fix all the lints that can be automatically applied
fix-lint:
    cargo clippy --all-features --all-targets --fix
