[package]
name = "osrdyne"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "15.1.0"
smol_str = "0.2.2"
smallvec = { version = "1.13.2", features = ["serde"] }
tokio = { version = "1.37.0", features = ["full"] }
log = "0.4.21"
thunderdome = "0.6.1"
priority-queue = "2.0.3"
env_logger = "0.11.3"
reqwest = { version = "0.12.4", features = ["json"] }
lapin = "2.3.4"
url = "2.5.0"
figment = { version = "0.10.19", features = ["env", "toml"] }
serde = "1.0.203"
serde_json = "1.0.117"
anyhow = "1.0.86"
percent-encoding = "2.3.1"
futures-lite = "2.3.0"
bollard = "0.16"
kube = { version = "0.89", features = ["client"] }
k8s-openapi = { version = "0.21", features = ["v1_29"] }
uuid = { version = "1.8.0", features = ["v4", "serde"] }
