[package]
edition = "2024"
name = "osrdyne"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.102"
axum = "0.8.9"
axum-extra = { version = "0.12.6", features = ["query"] }
axum-tracing-opentelemetry = "0.38.0"
bollard = "0.21"
figment = { version = "0.10.19", features = ["env", "yaml"] }
futures-lite = "2.6.1"
hex = "0.4.3"
http = "1.4.0"
humantime-serde = "1.1.1"
im = "15.1.0"
k8s-openapi = { version = "0.27", features = ["v1_35"] }
kube = { version = "3.1", default-features = false, features = [
  "client",
  "derive",
  "rustls-tls",
] }
lapin = { version = "4.8.0", default-features = false, features = [
  "default-runtime",
  "rustls--ring",
] }
opentelemetry = "0.32.0"
opentelemetry-otlp = { version = "0.32.0", features = ["grpc-tonic"] }
opentelemetry_sdk = { version = "0.32.0", features = ["rt-tokio"] }
percent-encoding = "2.3.2"
priority-queue = "2.7.0"
reqwest = { version = "0.12.28", default-features = false, features = [
  "json",
  "rustls-tls",
] }
schemars = "1.2.1"
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = "1.0.150"
sha2 = "0.11.0"
smol_str = { version = "0.3.6", features = ["serde"] }
thiserror = "2.0.18"
thunderdome = "0.6.1"
tokio = { version = "1.52.3", features = ["full"] }
tracing = "0.1.44"
tracing-opentelemetry = "0.33.0"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
url = { version = "2.5.8", features = ["serde"] }
uuid = { version = "1.23.1", features = ["serde", "v4"] }
