-- DO NOT EDIT THIS FILE MANUALLY!

DROP TABLE IF EXISTS "search_operational_point";
DROP TRIGGER IF EXISTS search_operational_point__ins_trig ON "infra_object_operational_point";
DROP TRIGGER IF EXISTS search_operational_point__upd_trig ON "infra_object_operational_point";
DROP FUNCTION IF EXISTS search_operational_point__ins_trig_fun;
DROP FUNCTION IF EXISTS search_operational_point__upd_trig_fun;
