plugins {
    alias(libs.plugins.kotlin.multiplatform)
}


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

kotlin {
    jvm()
    linuxX64()

    sourceSets {
        commonMain.dependencies {
            // PLEASE ADD AND UPDATE DEPENDENCIES USING libs.versions.toml
            api libs.kotlin.reflect
        }
        commonMain.kotlin.srcDirs = ['src/main/kotlin']
    }
}
