name: Template build & push

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
      cache_scope:
        type: string
        required: true
      context:
        type: string
        required: false
        default: "."
      dockerfile:
        type: string
        required: false
        default: "Dockerfile"
      build_args:
        type: string
        required: false
        default: ""

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        uses: docker/metadata-action@v4
        with:
          images: "${{ inputs.image_name }}"
          tags: |
            type=raw,value=$(date +%s%3N) # Unix timestamp in milliseconds
        id: docker_meta

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "${{ inputs.context }}"
          file: "${{ inputs.context }}/${{ inputs.dockerfile }}"
          build-args: |
            OSRD_GIT_DESCRIBE=${{ github.sha }}
            ${{ inputs.build_args }}
          push: true
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=gha,scope=${{ inputs.cache_scope }}
          cache-to: type=gha,mode=max,scope=${{ inputs.cache_scope }}
