name: Build & Push to DockerHub

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - staging
  release:
    types:
      - published

jobs:
  build_push_core:
    name: Core
    uses: osrd-project/osrd/.github/workflows/docker-build-push-template.yml@dev
    with:
      context: core
      image_name: osrd/core
      cache_scope: core
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_push_gateway:
    name: Gateway
    uses: osrd-project/osrd/.github/workflows/docker-build-push-template.yml@dev
    with:
      context: docker
      dockerfile: gateway-embedded-front.dockerfile
      image_name: osrd/gateway
      cache_scope: gateway
      build_contexts: |
        gateway=./gateway
        front=./front
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_push_editoast:
    name: Editoast
    uses: osrd-project/osrd/.github/workflows/docker-build-push-template.yml@dev
    with:
      context: editoast
      image_name: osrd/editoast
      cache_scope: editoast
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
