on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build_push_core:
    uses: DGEXSolutions/osrd/.github/workflows/docker-build-push-template.yml@dev
    with:
      context: core
      image_name: osrd/osrd-core
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_push_api:
    uses: DGEXSolutions/osrd/.github/workflows/docker-build-push-template.yml@dev
    with:
      context: api
      image_name: osrd/osrd-api
      build_args: |
        environment=test
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_push_chartos:
    uses: DGEXSolutions/osrd/.github/workflows/docker-build-push-template.yml@dev
    with:
      context: chartos
      image_name: osrd/chartos
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_push_front:
    uses: DGEXSolutions/osrd/.github/workflows/docker-build-push-template.yml@dev
    with:
      context: front
      image_name: osrd/osrd-front
      build_args: |
        NGINX_CONFIG=nginx-dev.conf
        REACT_APP_LOCAL_BACKEND=True
        REACT_APP_API_URL=http://localhost:8000
        REACT_APP_CHARTIS_URL=http://localhost:7000

    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
