name: Build & Push to DockerHub

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - staging
  release:
    types:
      - published

jobs:
  build_push_core:
    name: Core
    uses: DGEXSolutions/osrd/.github/workflows/docker-build-push-template.yml@dev
    with:
      context: core
      image_name: osrd/core
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_push_api:
    name: API
    uses: DGEXSolutions/osrd/.github/workflows/docker-build-push-template.yml@dev
    with:
      context: api
      image_name: osrd/api
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_push_chartos:
    name: Chartos
    uses: DGEXSolutions/osrd/.github/workflows/docker-build-push-template.yml@dev
    with:
      context: chartos
      image_name: osrd/chartos
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_push_front:
    name: Front
    uses: DGEXSolutions/osrd/.github/workflows/docker-build-push-template.yml@dev
    with:
      context: front
      image_name: osrd/front
      build_args: |
        NGINX_CONFIG=nginx-dev.conf
        REACT_APP_LOCAL_BACKEND=True
        REACT_APP_API_URL=http://localhost:8000
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_push_editoast:
    name: Editoast
    uses: DGEXSolutions/osrd/.github/workflows/docker-build-push-template.yml@dev
    with:
      context: editoast
      image_name: osrd/editoast
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_push_storybook:
    name: Storybook
    uses: DGEXSolutions/osrd/.github/workflows/docker-build-push-template.yml@dev
    with:
      context: front
      dockerfile: Dockerfile.storybook
      image_name: osrd/storybook
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
