name: Build and push to dockerhub

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build_push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the containers
        uses: docker/bake-action@v1.6.0
        with:
          files: "docker-compose.yml"
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
            osrd/osrd-*.output=type=registry
