name: Test Front

on:
  workflow_dispatch:
  pull_request:
    paths:
      - front/**
  push:
    branches:
      - dev
      - staging
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: front/yarn.lock
      - run: yarn --cwd front install
      - run: yarn --cwd front build
        env:
          CI: false
      - run: yarn --cwd front --passWithNoTests test
