name: Test Front

on:
  workflow_dispatch:
  pull_request:
    paths:
      - front/**
      - .github/workflows/front.yml
  merge_group:
    paths:
      - front/**
      - .github/workflows/front.yml
  push:
    branches:
      - dev
      - staging
      - prod

jobs:
  front_tests:
    name: Tests front
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: front/yarn.lock

      - name: Install dependencies
        run: yarn --cwd front install

      - name: Build project
        run: yarn --cwd front build
        env:
          CI: false

      - name: Run front test suite
        run: yarn --cwd front test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: codecov
          flags: front
          directory: ./front/tests/unit/coverage
          files: clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
