name: api_change

on:
  pull_request:
    paths:
      - "editoast/openapi.yaml"

jobs:
  openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Get reference OpenAPI
        run: git show ${{ github.event.pull_request.base.sha }}:editoast/openapi.yaml > base-openapi.yaml
      - name: Get new OpenAPI
        run: git show ${{ github.event.pull_request.head.sha }}:editoast/openapi.yaml > new-openapi.yaml
      - name: Find comment
        uses: peter-evans/find-comment@v4.0.0
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: API changes
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v5.0.0
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # :warning: API changes
            This Pull Request introduces some changes in the API:
            - [ ] please own it: notify or even prepare dedicated PR(s) to consumer projects
          edit-mode: replace

