name: Check integration tests quality

on:
  workflow_dispatch:
  pull_request:
    paths:
      - tests/**
      - .github/workflows/integration_tests_quality.yml
  merge_group:
  push:
    branches:
      - dev
      - staging
      - prod

jobs:
  integration_tests_quality:
    name: Integration tests quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # run the CI on the actual latest commit of the PR, not the attempted merge
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"
      - name: Install dependencies
        run: |
          cd tests
          poetry install
      - name: Flake8
        run: |
          cd tests
          poetry run pflake8 --config ./pyproject.toml
      - name: Black
        run: |
          cd tests
          poetry run black . --check
      - name: Isort
        run: |
          cd tests
          poetry run isort . --check
      - name: Pytype
        run: |
          cd tests
          poetry run pytype -j auto