name: Clean up old unstable images

on:
  schedule:
    # Run every day at midnight to check for old images
    - cron: '0 0 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run cleanup script
      run: ./.github/scripts/cleanup-ghcr.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RETENTION_PERIOD_DAYS: 30
        PACKAGE_FILTER_REGEX: "^unstable/"
        EXCLUDE_TAGS_REGEX: "^(dev|staging|prod)$"
