CREATE TABLE timetable_v2 (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    electrical_profile_set_id int8 NULL REFERENCES electrical_profile_set(id) ON DELETE CASCADE
);
CREATE TABLE train_schedule_v2 (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    train_name varchar(128) NOT NULL,
    labels text [] NOT NULL,
    rolling_stock_name varchar(128) NOT NULL,
    timetable_id int8 NOT NULL REFERENCES timetable_v2(id) ON DELETE CASCADE,
    start_time timestamptz NOT NULL,
    schedule jsonb NOT NULL,
    margins jsonb NOT NULL,
    initial_speed float8 NOT NULL,
    comfort smallint NOT NULL,
    path jsonb NOT NULL,
    constraint_distribution smallint NOT NULL,
    speed_limit_tag varchar(128),
    power_restrictions jsonb NOT NULL,
    options jsonb NOT NULL
);
