CREATE TABLE timetable_train_schedule_set (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timetable_id int8 NOT NULL REFERENCES timetable(id) ON DELETE CASCADE,
    train_schedule_set_id int8 NOT NULL REFERENCES train_schedule_set(id) ON DELETE CASCADE,
    UNIQUE (timetable_id, train_schedule_set_id)
);

ALTER TABLE paced_train
ADD COLUMN train_schedule_set_id int8 REFERENCES train_schedule_set(id) ON DELETE CASCADE;

-- Create train_schedule_sets with the same IDs as their timetables
INSERT INTO train_schedule_set (id, name, published)
SELECT id, NULL, false
FROM timetable;

-- Update the train_schedule_set sequence to avoid future conflicts
SELECT setval('train_schedule_set_id_seq', (SELECT MAX(id) FROM train_schedule_set));

-- Link timetables to their corresponding train_schedule_sets (same IDs)
INSERT INTO timetable_train_schedule_set (timetable_id, train_schedule_set_id)
SELECT id, id
FROM timetable;

-- Link paced_trains directly using timetable_id (which is now the same as train_schedule_set_id)
UPDATE paced_train
SET train_schedule_set_id = timetable_id;

ALTER TABLE paced_train
    ALTER COLUMN train_schedule_set_id
    SET NOT NULL;
ALTER TABLE paced_train DROP COLUMN timetable_id;
